//! Registered semantic guide formatters, independent of positional scale ownership.
use super::{ExtensionDescriptor, ExtensionRegistry, OperationRef, extensions};
use crate::{ChartResult, DiagnosticCode, Limits, composition::ScaleValue};
use std::{collections::BTreeMap, sync::Arc};

/// Exact temporal interpretation of origin-relative numeric guide values.
#[derive(Clone, Copy, Debug)]
pub struct GuideTemporalContext<'a> {
    /// Origin, source unit, and Date versus datetime semantics.
    pub normalization: crate::scales::GgplotTimestampNormalization,
    /// Explicit immutable calendar rules; no ambient timezone lookup is needed.
    pub zone: &'a crate::scales::CalendarZone,
}

/// Exact inputs to one native label callback. The list precedes mapping/omission.
pub struct GuideFormatInput<'a> {
    /// Source value; origin-relative temporal numbers use the supplied context.
    pub value: &'a ScaleValue,
    /// Authored occurrence index, even when values or labels repeat.
    pub index: usize,
    /// Complete selected semantic values in their authored/generated order.
    pub values: &'a [ScaleValue],
    /// Temporal context when numeric values represent timestamp offsets.
    pub temporal: Option<GuideTemporalContext<'a>>,
    /// Explicit bounded declarative configuration.
    pub parameters: &'a serde_json::Value,
    /// Remaining text budget and the destination's other resource bounds.
    pub limits: Limits,
}

/// Complete source-space vector for a registered label function.
pub struct GuideLabelsInput<'a> {
    /// Selected values, before guide visibility filtering.
    pub values: &'a [ScaleValue],
    /// Optional names retained or generated by reference break selection.
    pub names: Option<&'a [String]>,
    /// Temporal context when numeric values represent timestamp offsets.
    pub temporal: Option<GuideTemporalContext<'a>>,
    /// Explicit bounded declarative configuration.
    pub parameters: &'a serde_json::Value,
    /// Destination resource bounds.
    pub limits: Limits,
}

/// Trusted native label callback behind an explicitly installed versioned identity.
/// Implementations must honor the supplied resource bounds and perform no implicit
/// locale, calendar or host-object lookup. Native code cannot be preempted by core.
pub trait CustomGuideFormatter: Send + Sync {
    /// Identity and portability captured once at registration.
    fn descriptor(&self) -> ExtensionDescriptor;
    /// Check bounded parameters without invoking per-value callbacks.
    fn validate(&self, parameters: &serde_json::Value) -> ChartResult<()>;
    /// Format one original semantic value. Empty and repeated strings are valid.
    /// Override this method or `format_labels`; the default reports unsupported use.
    fn format(&self, _input: GuideFormatInput<'_>) -> ChartResult<String> {
        Err(super::error(
            DiagnosticCode::UnsupportedCapability,
            "This guide formatter only supports complete label vectors.",
        ))
    }
    /// Format a complete vector once. Missing labels are distinct from empty text.
    /// The default preserves the per-value API and its decreasing text budget.
    /// Consumers own reference-specific result-length and missing-label policies.
    /// Continuous positional guides require one result per value; reference discrete
    /// guides use the shared recycling rule. Missing positional labels draw as empty
    /// text, retaining their ticks.
    fn format_labels(&self, input: GuideLabelsInput<'_>) -> ChartResult<Vec<Option<String>>> {
        let mut limits = input.limits;
        let mut labels = Vec::with_capacity(input.values.len());
        for (index, value) in input.values.iter().enumerate() {
            let label = self.format(GuideFormatInput {
                value,
                index,
                values: input.values,
                temporal: input.temporal,
                parameters: input.parameters,
                limits,
            })?;
            crate::limits::require_within(
                label.len() <= limits.max_text_bytes,
                "registered guide label byte",
            )?;
            limits.max_text_bytes -= label.len();
            labels.push(Some(label));
        }
        Ok(labels)
    }
}

#[derive(Clone)]
struct Registration {
    descriptor: ExtensionDescriptor,
    implementation: Arc<dyn CustomGuideFormatter>,
}
impl std::fmt::Debug for Registration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.descriptor.fmt(f)
    }
}
#[derive(Clone, Debug, Default)]
pub(crate) struct GuideRegistrations {
    entries: BTreeMap<(String, u64), Registration>,
}
impl GuideRegistrations {
    fn registration(&self, operation: &OperationRef) -> ChartResult<&Registration> {
        self.entries
            .get(&(operation.id.clone(), operation.version.get()))
            .ok_or_else(|| {
                super::error(
                    DiagnosticCode::UnsupportedCapability,
                    format!(
                        "Guide formatter {} version {} is not registered.",
                        operation.id,
                        operation.version.get()
                    ),
                )
            })
    }
    pub(crate) fn validate(
        &self,
        operation: &OperationRef,
        parameters: &serde_json::Value,
        portable: bool,
    ) -> ChartResult<()> {
        extensions::parameter_size(parameters)?;
        let registration = self.registration(operation)?;
        if portable && !registration.descriptor.portable {
            return Err(super::error(
                DiagnosticCode::UnsupportedCapability,
                "A native-only guide formatter cannot serialize or execute in headless publication.",
            ));
        }
        registration.implementation.validate(parameters)
    }
    pub(crate) fn labels(
        &self,
        operation: &OperationRef,
        input: GuideLabelsInput<'_>,
        portable: bool,
    ) -> ChartResult<Vec<String>> {
        let count = input.values.len();
        let labels = self.label_vector(operation, input, portable)?;
        if labels.len() != count {
            return Err(super::error(
                DiagnosticCode::SchemaConflict,
                "Registered guide labels must match the complete selected value list.",
            ));
        }
        Ok(labels.into_iter().map(Option::unwrap_or_default).collect())
    }
    pub(crate) fn label_vector(
        &self,
        operation: &OperationRef,
        input: GuideLabelsInput<'_>,
        portable: bool,
    ) -> ChartResult<Vec<Option<String>>> {
        let GuideLabelsInput {
            values,
            names,
            temporal,
            parameters,
            mut limits,
        } = input;
        self.validate(operation, parameters, portable)?;
        if names.is_some_and(|names| names.len() != values.len()) {
            return Err(super::error(
                DiagnosticCode::SchemaConflict,
                "Guide break names must match the selected value list.",
            ));
        }
        crate::limits::require_within(values.len() <= limits.max_items, "registered guide input")?;
        let registration = self.registration(operation)?;
        let labels = registration
            .implementation
            .format_labels(GuideLabelsInput {
                values,
                names,
                temporal,
                parameters,
                limits,
            })?;
        crate::limits::require_within(labels.len() <= limits.max_items, "registered guide output")?;
        for label in labels.iter().flatten() {
            crate::limits::require_within(
                label.len() <= limits.max_text_bytes,
                "registered guide label byte",
            )?;
            limits.max_text_bytes -= label.len();
        }
        Ok(labels)
    }
}
impl ExtensionRegistry {
    /// Install one checked version; snapshots retain their previous registrations.
    pub fn register_guide_formatter(
        &mut self,
        implementation: Arc<dyn CustomGuideFormatter>,
    ) -> ChartResult<()> {
        let descriptor = implementation.descriptor();
        extensions::validate_descriptor(&descriptor)?;
        let key = (
            descriptor.operation.id.clone(),
            descriptor.operation.version.get(),
        );
        let entries = &mut Arc::make_mut(&mut self.guides).entries;
        if entries.contains_key(&key) {
            return Err(super::error(
                DiagnosticCode::SchemaConflict,
                "A guide formatter version is already registered.",
            ));
        }
        crate::limits::require_within(entries.len() < 64, "registered guide formatter")?;
        entries.insert(
            key,
            Registration {
                descriptor,
                implementation,
            },
        );
        Ok(())
    }
    /// Captured identity and portability; does not invoke callback code.
    pub fn guide_formatter_descriptor(
        &self,
        operation: &OperationRef,
    ) -> ChartResult<ExtensionDescriptor> {
        Ok(self.guides.registration(operation)?.descriptor.clone())
    }
    pub(crate) fn validate_guide_selections(
        &self,
        definition: &super::ChartDefinition,
        portable: bool,
    ) -> ChartResult<()> {
        if let Some(call) = definition
            .facets
            .as_ref()
            .and_then(|s| s.reference.as_ref())
            .and_then(|p| p.labeller.registered.as_ref())
        {
            self.guides
                .validate(&call.operation, &call.parameters, portable)?;
        }
        for axis in &definition.axes {
            if let crate::layout::AxisScale::Binned { spec, .. } = &axis.scale
                && let Some(call) = &spec.breaks_function
            {
                if definition.profile() != super::Profile::Ggplot2_4_0_3 {
                    return Err(super::error(
                        DiagnosticCode::UnsupportedCapability,
                        "Binned break functions require the reference profile.",
                    ));
                }
                self.breaks_function.validate(call, portable)?;
            }
        }
        for labels in scale_label_policies(definition) {
            if let crate::scales::GgplotGuideLabels::Registered {
                operation,
                parameters,
            } = labels
            {
                self.guides.validate(operation, parameters, portable)?;
            }
        }
        for style in definition
            .axes
            .iter()
            .map(|axis| &axis.guide)
            .chain(definition.guides.iter().map(|guide| &guide.style))
        {
            for call in
                style
                    .breaks_function
                    .as_deref()
                    .into_iter()
                    .chain(match &style.minor_breaks {
                        Some(crate::layout::MinorBreaks::Registered(call)) => Some(call),
                        _ => None,
                    })
            {
                if definition.profile() != super::Profile::Ggplot2_4_0_3
                    || style.profile != crate::layout::GuideProfile::LibraryV1
                {
                    return Err(super::error(
                        DiagnosticCode::UnsupportedCapability,
                        "Positional break functions require the reference guide profile.",
                    ));
                }
                self.breaks_function.validate(call, portable)?;
            }
            if let Some(crate::layout::GuideFormatter::Registered {
                operation,
                parameters,
            }) = &style.tick_format
            {
                self.guides.validate(operation, parameters, portable)?;
            }
        }
        Ok(())
    }
}

pub(crate) fn scale_label_policies(
    definition: &super::ChartDefinition,
) -> impl Iterator<Item = &crate::scales::GgplotGuideLabels> {
    super::interpolation_extensions::mapped_scales(definition)
        .filter_map(|scale| {
            scale
                .guide
                .as_deref()
                .and_then(crate::scales::GgplotScaleGuide::labels)
        })
        .chain(definition.axes.iter().flat_map(|axis| {
            axis.discrete
                .iter()
                .map(|policy| &policy.guide.labels)
                .chain(match &axis.scale {
                    crate::layout::AxisScale::Binned { spec, .. } => Some(&spec.labels),
                    _ => None,
                })
        }))
}

pub(crate) fn validate_parameters(parameters: &serde_json::Value) -> ChartResult<()> {
    extensions::parameter_size(parameters).map(|_| ())
}
