"""GG06–GG09 and GG12 primary factory and fluent method declarations."""
import finstack_chart as c
c.bin().ggplot_bin({'closed':'Right','pad':True}).bin_weight('w')
c.count().ggplot_count().count_weight('w').count_width(.9)
c.summary().summary_helper({'MeanSe':{'mult':1.}}).summary_bins({'bins':3})
c.points().position(c.ggplot_stack().vjust(.5).reverse(True))
c.points().position(c.ggplot_fill().reverse(True))
c.points().position(c.dodge2().width(.8).padding(.2).preserve('Single'))
c.points().position(c.jitter_dodge(42).displacement(.2,.1))
c.points().position(c.nudge(.2,-.1))
c.points().text_label('label')

data=c.Data.columns({'x':[1.], 'y':[2.]})
c.errorbar().recipe_value('Lower',data.field('y')).recipe_value('Upper',c.source_expr(data.field('y')))
c.pointrange().recipe_stat_value('Lower','Lower')
c.points().recipe({'Raster': {'interpolate':True}})
c.count().sum_count().x('x').y('y').count_partition(data.field('x'))
c.step('Mid')
c.abline(1.,0.)
c.hline(0.)
c.vline(1.)
c.bin().bin_weight(c.source_expr(data.field('y')))
c.count().count_weight(c.source_expr(data.field('y')))

c.segment().lineend('Round').linejoin('Bevel')
c.crossbar().recipe({'Interval':{'kind':'Crossbar','fatten':3.,'middle':{'linewidth':2.}}})
c.boxplot().stat(c.boxplot_stat().input(data.field('y')).weight(c.source_expr(data.field('x'))).width(.75))
c.violin().stat(c.violin_stat().distribution_options({'Violin':{'trim':True}}))
c.dotplot().stat(c.dotplot_stat())
c.ecdf().stat(c.ecdf_stat().univariate_options({'Ecdf':{'n':10,'pad':True}}))
c.qq_line().stat(c.qq_line_stat())

c.density().recipe({'Density': {'outline': 'Both'}}).stat(c.density_stat().input('x'))
c.qq().stat(c.qq_stat())
c.function_curve({'Expression': {'nodes': [{'Read': 'Value'}], 'output': 0}})
c.function_stat({'Expression': {'nodes': [{'Read': 'Value'}], 'output': 0}})
c.distribution_stat({'Boxplot': {'coefficient': 1.5}})
c.unique_stat().x(data.field('x'))
c.align_stat().x('x').y('y')
c.connect_stat('Hv').x('x').y('y')
c.univariate_stat('Unique')
c.facet_wrap('x').fields(['x', 'y']).columns(2).reference({'drop': False, 'direction': 'Tr', 'strip_position': 'Left', 'axes': 'All', 'axis_labels': 'Margins'})
c.facet_grid('x', 'y').fields(['x', 'y']).row_fields(1).free_x(True).free_y(True).reference({'space': 'Free', 'margins': [0, 1], 'shrink': False, 'switch': 'Both', 'as_table': False})
