"""GG06–GG09 and GG12 primary factory and fluent method declarations."""
import finstack_chart as c
c.bin().ggplot_bin({'closed':'Right','pad':True}).bin_weight('w')
c.count().ggplot_count().count_weight('w').count_width(.9)
c.summary().summary_helper({'MeanSe':{'mult':1.}}).summary_bins({'bins':3})
c.points().position(c.ggplot_stack().vjust(.5).reverse(True))
c.points().position(c.ggplot_fill().reverse(True))
c.points().position(c.dodge2().width(.8).padding(.2).preserve('Single'))
c.points().position(c.jitter_dodge(42).displacement(.2,.1))
c.points().position(c.nudge(.2,-.1))
c.points().text_label('label')

data=c.Data.columns({'x':[1.], 'y':[2.]})
c.errorbar().recipe_value('Lower',data.field('y')).recipe_value('Upper',c.source_expr(data.field('y')))
c.pointrange().recipe_stat_value('Lower','Lower')
c.points().recipe({'Raster': {'interpolate':True}})
c.count().sum_count().x('x').y('y').count_partition(data.field('x'))
c.step('Mid')
c.abline(1.,0.)
c.hline(0.)
c.vline(1.)
c.bin().bin_weight(c.source_expr(data.field('y')))
c.count().count_weight(c.source_expr(data.field('y')))

c.segment().lineend('Round').linejoin('Bevel')
c.crossbar().recipe({'Interval':{'kind':'Crossbar','fatten':3.,'middle':{'linewidth':2.}}})
c.boxplot().stat(c.boxplot_stat().input(data.field('y')).weight(c.source_expr(data.field('x'))).width(.75))
c.violin().stat(c.violin_stat().distribution_options({'Violin':{'trim':True}}))
c.dotplot().stat(c.dotplot_stat())
c.ecdf().stat(c.ecdf_stat().univariate_options({'Ecdf':{'n':10,'pad':True}}))
c.qq_line().stat(c.qq_line_stat())

c.density().recipe({'Density': {'outline': 'Both'}}).stat(c.density_stat().input('x'))
c.qq().stat(c.qq_stat())
c.function_curve({'Expression': {'nodes': [{'Read': 'Value'}], 'output': 0}})
c.function_stat({'Expression': {'nodes': [{'Read': 'Value'}], 'output': 0}})
c.distribution_stat({'Boxplot': {'coefficient': 1.5}})
c.unique_stat().x(data.field('x'))
c.align_stat().x('x').y('y')
c.connect_stat('Hv').x('x').y('y')
c.univariate_stat('Unique')
c.facet_wrap('x').fields(['x', 'y']).columns(2).reference({'drop': False, 'direction': 'Tr', 'strip_position': 'Left', 'axes': 'All', 'axis_labels': 'Margins'})
c.facet_grid('x', 'y').fields(['x', 'y']).row_fields(1).free_x(True).free_y(True).reference({'space': 'Free', 'margins': [0, 1], 'shrink': False, 'switch': 'Both', 'as_table': False})

c.smooth().stat(c.model_stat({'method':'Linear','n':12}).model_options({'method':'Linear'}).input('x').y('y').weight('w'))
c.quantile().stat(c.quantile_stat())
c.smooth_stat()
c.bin2d().stat(c.bin2d_stat().spatial_options({'Rectangular':{'axes':[{},{}],'drop':True}}))
c.hex().stat(c.hex_stat())
c.density2d().stat(c.density2d_stat())
c.contour().stat(c.contour_stat())
c.contour_filled().stat(c.contour_filled_stat())
c.ellipse().stat(c.ellipse_stat())
c.spatial_stat({'Ellipse':{'level':.95,'segments':51,'kind':'Normal'}})
c.plot(data).coordinate({'Cartesian':{'flip':True}})

c.cut_interval([1.,None,3.],n=2).copy().column()
c.cut_number([1.,2.,3.],2).value()
c.cut_width([1.,2.,3.],1.,boundary=0.).dispose()
c.resolution([1.,2.],zero=False)
c.summarize([1.,None,3.],{'MeanSe':{'mult':2.}})
c.points().key_glyph('example.diamond_key',1,{'padding':.1})
registry=c.ExtensionRegistry.example()
materialized=registry.materialize('example.xy_recipe',1,{'x':[1.], 'y':[2.]})
c.autoplot(materialized,'example.xy_recipe',1,{'line':True},registry)
c.plot(data).with_registry(registry).autolayer('example.xy_recipe',1,{'line':True})

c.legend().scale("groups").registered("example.strip_guide",1,{})
c.facet_wrap("group").registered("example.reverse_facets",1,{"columns":2})

c.plot(data).registered_coordinate("example.wave_coordinate",1,{"amplitude":.1})

save_output=c.Output(b'font')
save_options:c.SaveOptions={'width':2.,'height':1.,'units':'in','dpi':'retina'}
save_plan:c.SavePlan=save_output.resolve_save('plot-%03d.png',save_options,page_number=2)
save_output.save_figure(c.plot(data).layer(c.points()).build(),'plot.png',save_options,device=lambda frame:frame.export('png'))
c.points().text_defaults()

reference_theme=c.theme().reference_preset('Minimal',{'base_size':13.}).fonts([])
reference_theme=reference_theme.update_elements({'complete':False,'elements':{'axis.text':'Blank'}}).replace_elements({'complete':False,'elements':{}})
theme_context=c.ThemeContext(reference_theme)
previous_theme:c.Theme=theme_context.set(theme_context.get())
previous_theme.dispose()
theme_context.update({'complete':False,'elements':{}})
theme_context.replace({'complete':False,'elements':{}})
c.plot(data).theme(theme_context.get())
theme_context.dispose()


def retained_page_documents(frame: c.FigureSnapshot) -> tuple[bytes, bytes, bytes]:
    with frame.pages() as pages:
        pages.append(frame)
        return pages.export('pdf'), pages.export('ps'), pages.export('tiff')
