# Primary host contract. Small options retain the core enum/field spellings.
from ._scales import (ScaleKey as ScaleKey, StandaloneScale as StandaloneScale, ScaleFamily as ScaleFamily, ScaleArgument as ScaleArgument, CalendarInterval as CalendarInterval, NumericLocale as NumericLocale, TimeLocale as TimeLocale, TimeZoneRules as TimeZoneRules, CalendarZone as CalendarZone, InterpolationFactorySpec as InterpolationFactorySpec, InverseExtent as InverseExtent)
from collections.abc import Callable, Iterable, Mapping, Sequence
from os import PathLike
from typing import Literal, Self, TypeAlias, TypedDict, NotRequired, overload

JSONValue: TypeAlias = None | bool | int | float | str | Sequence["JSONValue"] | Mapping[str, "JSONValue"]
Options: TypeAlias = Mapping[str, object]
Color: TypeAlias = str | Options | ColorValue
Panel: TypeAlias = Sequence[str | int | bool | Options] | Options
ScaleValue: TypeAlias = float | str | Options
MappingValue: TypeAlias = str | float | Field | Options
Format: TypeAlias = Literal["svg", "pdf", "png"]
ColumnKind: TypeAlias = Literal["float64", "int64", "uint64", "bool", "string", "category", "s", "ms", "us", "ns"]
class ActionOutcome(TypedDict):
    changed: bool
    revision: str
    viewport_changed: bool
class DispatchOutcome(TypedDict):
    outcome: ActionOutcome
    event: dict[str, object] | None
class SelectionResult(TypedDict):
    targets: list[dict[str, object]]
class WindowResult(TypedDict):
    windows: dict[str, object]
class Revisions(TypedDict):
    definition: int
    state: int
    epoch: int
    store: int
class ChartError(Exception):
    code: str
    message: str
    correction: str
    context: dict[str, object]
    diagnostic: dict[str, object]
class _Owned:
    def dispose(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
ColorSpace: TypeAlias = Literal["Rgb", "Hsl", "Lab", "Hcl", "Cubehelix", "rgb", "hsl", "lab", "hcl", "lch", "cubehelix"]
class ColorValue(_Owned):
    @classmethod
    def from_json(cls, value: str) -> ColorValue: ...
    def to_json(self) -> str: ...
    def value(self) -> dict[str, object]: ...
    def space(self) -> str: ...
    def channels(self) -> dict[str, float]: ...
    def channel(self, name: str) -> float: ...
    def with_channel(self, name: str, value: float) -> ColorValue: ...
    def copy(self, channels: Mapping[str, float] | None = ...) -> ColorValue: ...
    def convert(self, space: ColorSpace) -> ColorValue: ...
    def rgb(self) -> ColorValue: ...
    def brighter(self, k: float | None = ...) -> ColorValue: ...
    def darker(self, k: float | None = ...) -> ColorValue: ...
    def displayable(self) -> bool: ...
    def clamp(self) -> ColorValue: ...
    def format_hex(self) -> str: ...
    def format_hex8(self) -> str: ...
    def format_rgb(self) -> str: ...
    def format_hsl(self) -> str: ...
    def hex(self) -> str: ...
def color(css: str) -> ColorValue | None: ...
@overload
def rgb(value: str | ColorValue) -> ColorValue: ...
@overload
def rgb(r: float, g: float, b: float, opacity: float = ...) -> ColorValue: ...
@overload
def hsl(value: str | ColorValue) -> ColorValue: ...
@overload
def hsl(h: float, s: float, l: float, opacity: float = ...) -> ColorValue: ...
@overload
def lab(value: str | ColorValue) -> ColorValue: ...
@overload
def lab(l: float, a: float, b: float, opacity: float = ...) -> ColorValue: ...
@overload
def hcl(value: str | ColorValue) -> ColorValue: ...
@overload
def hcl(h: float, c: float, l: float, opacity: float = ...) -> ColorValue: ...
@overload
def lch(value: str | ColorValue) -> ColorValue: ...
@overload
def lch(l: float, c: float, h: float, opacity: float = ...) -> ColorValue: ...
@overload
def cubehelix(value: str | ColorValue) -> ColorValue: ...
@overload
def cubehelix(h: float, s: float, l: float, opacity: float = ...) -> ColorValue: ...
def gray(l: float, opacity: float = ...) -> ColorValue: ...
class Field(_Owned): ...
class Column(_Owned):
    def nullable(self, value: bool = ...) -> Column: ...
    def validity(self, values: Iterable[bool]) -> Column: ...
    def formatted(self, values: Iterable[str | None]) -> Column: ...
    def unit(self, value: str) -> Column: ...
    def label(self, value: str) -> Column: ...
def column(values: Iterable[float | int | bool | str | None], *, kind: ColumnKind | None = ..., timezone: str = ...) -> Column: ...
def categorical(values: Iterable[str | None]) -> Column: ...
def timestamps(values: Iterable[int | None], unit: Literal["s","ms","us","ns"] = ..., timezone: str = ...) -> Column: ...
class Data(_Owned):
    @staticmethod
    def columns(columns: Mapping[str, Column | Iterable[float | int | bool | str | None]], *, name: str = ..., keys: Iterable[int] | None = ..., limits: Options | None = ..., schema_version: int | None = ..., identity: int | None = ...) -> Data: ...
    @staticmethod
    def rows(rows: Iterable[object], *, fields: Mapping[str, Callable[..., object]] | None = ..., name: str = ..., keys: Iterable[int] | Callable[..., int] | None = ..., limits: Options | None = ..., schema_version: int | None = ..., identity: int | None = ...) -> Data: ...
    def field(self, name: str) -> Field: ...
    @property
    def name(self) -> str: ...
class Component(_Owned): ...

class _Expression(Component):
    def add(self, value: Self | float) -> Self: ...
    def sub(self, value: Self | float) -> Self: ...
    def mul(self, value: Self | float) -> Self: ...
    def div(self, value: Self | float) -> Self: ...
    def pow(self, value: Self | float) -> Self: ...
    def less(self, value: Self | float) -> Self: ...
    def equal(self, value: Self | float) -> Self: ...
    def coalesce(self, value: Self | float) -> Self: ...
    def concat(self, value: Self | float) -> Self: ...
    def __add__(self, value: Self | float) -> Self: ...
    def __sub__(self, value: Self | float) -> Self: ...
    def __mul__(self, value: Self | float) -> Self: ...
    def __truediv__(self, value: Self | float) -> Self: ...
    def __pow__(self, value: Self | float) -> Self: ...
    def negate(self) -> Self: ...
    def abs(self) -> Self: ...
    def sqrt(self) -> Self: ...
    def log(self) -> Self: ...
    def log10(self) -> Self: ...
    def exp(self) -> Self: ...
    def floor(self) -> Self: ...
    def ceil(self) -> Self: ...
    def is_missing(self) -> Self: ...
    def __neg__(self) -> Self: ...
    def sum(self, remove_missing: bool = ...) -> Self: ...
    def mean(self, remove_missing: bool = ...) -> Self: ...
    def min(self, remove_missing: bool = ...) -> Self: ...
    def max(self, remove_missing: bool = ...) -> Self: ...
    def count(self, remove_missing: bool = ...) -> Self: ...
class SourceExpression(_Expression): ...
class StatExpression(_Expression): ...
class BinExpression(_Expression): ...
class ScaleExpression(_Expression): ...
class ScaleAes(Component):
    def size(self, value: ScaleExpression) -> Self: ...
    def color(self, value: ScaleExpression) -> Self: ...
def source_expr(field: str | Field | Options) -> SourceExpression: ...
def stat_expr(field: str | Options) -> StatExpression: ...
def bin_expr(field: str) -> BinExpression: ...
def after_scale_expr(aesthetic: Literal["Size","Color"]) -> ScaleExpression: ...
def from_theme(token: Literal["Ink","Paper","Accent","PointSize","LineWidth"]) -> ScaleExpression: ...
def scale_aes() -> ScaleAes: ...

class Aes(Component):
    def x(self, value: MappingValue | SourceExpression) -> Self: ...
    def y(self, value: MappingValue | SourceExpression) -> Self: ...
    def x2(self, value: MappingValue | SourceExpression) -> Self: ...
    def y2(self, value: MappingValue | SourceExpression) -> Self: ...
    def low(self, value: MappingValue | SourceExpression) -> Self: ...
    def high(self, value: MappingValue | SourceExpression) -> Self: ...
    def size(self, value: MappingValue | SourceExpression) -> Self: ...
    def group(self, value: MappingValue) -> Self: ...
    def color(self, value: MappingValue) -> Self: ...
    def group_all(self) -> Self: ...
    def color_scale(self, name: str) -> Self: ...

NumericAesthetic: TypeAlias = Literal['Size', 'Opacity', 'StrokeWidth', 'AreaSize','Angle','Radius','InnerRadius', 'OuterRadius', 'StartAngle', 'EndAngle', 'PadAngle', 'PadRadius', 'CornerRadius', 'PieValue']
ShapeChannel: TypeAlias = Literal['AreaSize','Angle','Radius','InnerRadius', 'OuterRadius', 'StartAngle', 'EndAngle', 'PadAngle', 'PadRadius', 'CornerRadius', 'PieValue']
class Layer(Component):
    def shape_protocol(self, family: ShapeFamily, selection: ShapeOperation) -> Self: ...
    def shape_value(self, target: ShapeChannel, source: str | float | Field | SourceExpression | Options) -> Self: ...
    def arc_parameters(self, parameters: ArcParameters) -> Self: ...
    def radial_parameters(self, parameters: RadialParameters) -> Self: ...
    def pie_angles(self, angles: PieAngles) -> Self: ...
    def pie_grouped(self, grouped: bool) -> Self: ...
    def pie_order(self, order: Literal['ValuesDescending','ValuesAscending','Input']) -> Self: ...
    def curve(self, value: CurveSpec) -> Self: ...
    def numeric_scale(self, target: NumericAesthetic, source: str | float | Field | SourceExpression | Options, scale: StandaloneScale | Options) -> Self: ...
    def orientation(self, value: Literal["Vertical","Horizontal"]) -> Self: ...
    def color_group(self, scale: str) -> Self: ...
    def name(self, name: str) -> Self: ...
    def data(self, data: Data) -> Self: ...
    def aes(self, mapping: Aes) -> Self: ...
    def stat(self, value: Stat) -> Self: ...
    def after_stat(self, mapping: StatAes) -> Self: ...
    def after_bin(self, mapping: BinAes) -> Self: ...
    def after_scale(self, mapping: ScaleAes) -> Self: ...
    def filter(self, value: Filter) -> Self: ...
    def position(self, value: Position) -> Self: ...
    def style(self, value: Style) -> Self: ...
    def from_transform(self, value: str | Transform) -> Self: ...
    def independent(self) -> Self: ...
    def size(self, value: float) -> Self: ...
    def width(self, value: float) -> Self: ...
    def baseline(self, value: float) -> Self: ...
    def color(self, value: Color) -> Self: ...
    def axes(self, x: str, y: str) -> Self: ...
    def scope(self, value: str) -> Self: ...
    def facet_target(self, value: Options) -> Self: ...
    def clip(self, value: bool) -> Self: ...
    def connect_gaps(self, value: bool) -> Self: ...
    def invalid(self, value: str) -> Self: ...
    def order(self, value: str) -> Self: ...
    def candle_colors(self, value: Options) -> Self: ...
    def bins(self, count: int) -> Self: ...
    def breaks(self, values: Sequence[float]) -> Self: ...
    def geometry(self, name: str, version: int, parameters: JSONValue) -> Self: ...
    def symbol_kind(self, kind: SymbolKind) -> Layer: ...
    def symbol_size(self, size: float) -> Layer: ...
    def symbol_paint(self, paint: Literal['Auto','Fill','Stroke']) -> Layer: ...
    def symbol_types(self, field: str | Field, domain: Sequence[str], palette: Sequence[SymbolKind]) -> Layer: ...
    def symbol_groups(self, domain: Sequence[str], palette: Sequence[SymbolKind]) -> Layer: ...
    def symbol_missing(self, kind: SymbolKind | None) -> Layer: ...
    def symbol_title(self, title: str) -> Layer: ...
    def symbol_size_guide(self, title: str, values: Sequence[float]) -> Layer: ...

class Stat(Component):
    def field_parameter(self, name: str, value: MappingValue) -> Self: ...
    def x(self, value: MappingValue | SourceExpression) -> Self: ...
    def y(self, value: MappingValue | SourceExpression) -> Self: ...
    def group(self, value: MappingValue) -> Self: ...
    def group_all(self) -> Self: ...
    def bins(self, count: int) -> Self: ...
    def breaks(self, values: Sequence[float]) -> Self: ...
    def quantiles(self, values: Sequence[float]) -> Self: ...
    def required(self, values: Sequence[str | float | Options]) -> Self: ...
    def outliers(self, value: str) -> Self: ...
    def empty_sum_zero(self, value: bool) -> Self: ...
    def transform(self, factor: float, offset: float) -> Self: ...
    def y_transform(self, factor: float, offset: float) -> Self: ...

class StatAes(Component):
    def x(self, value: str | float | Options | StatExpression) -> Self: ...
    def y(self, value: str | float | Options | StatExpression) -> Self: ...
    def x2(self, value: str | float | Options | StatExpression) -> Self: ...
    def y2(self, value: str | float | Options | StatExpression) -> Self: ...
    def size(self, value: str | float | Options | StatExpression) -> Self: ...
    def color(self, value: str | Options) -> Self: ...
    def color_scale(self, name: str) -> Self: ...
    def color_group(self, name: str) -> Self: ...

class BinAes(Component):
    def x(self, value: str | float | Options | BinExpression) -> Self: ...
    def y(self, value: str | float | Options | BinExpression) -> Self: ...
    def x2(self, value: str | float | Options | BinExpression) -> Self: ...
    def y2(self, value: str | float | Options | BinExpression) -> Self: ...
    def color_group(self, name: str) -> Self: ...

    def size(self, value: str | float | Options | BinExpression) -> Self: ...

class Position(Component):
    def stack_order(self, value: StackOrder) -> Self: ...
    def stack_offset(self, value: StackOffset) -> Self: ...
    def stack_missing(self, value: StackMissing) -> Self: ...
    def normalize(self, value: bool) -> Self: ...
    def width(self, value: float) -> Self: ...
    def displacement(self, x: float, y: float) -> Self: ...
    def units(self, value: str) -> Self: ...

class Filter(Component):
    def minimum(self, value: float) -> Self: ...
    def maximum(self, value: float) -> Self: ...

class Transform(Component):
    def data(self, data: Data) -> Self: ...
    def aes(self, value: Aes) -> Self: ...
    def filter(self, value: Filter) -> Self: ...
    def from_transform(self, value: str | Transform) -> Self: ...
    def scope(self, value: str) -> Self: ...
    def invalid(self, value: str) -> Self: ...
    def facet_target(self, value: Options) -> Self: ...

class Scale(Component):
    def calendar_interval(self, value: CalendarInterval) -> Self: ...
    def domain(self, start: float, end: float) -> Self: ...
    def band_padding(self, start: float, end: float) -> Self: ...
    def baseline(self, value: str) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def point_padding(self, value: float) -> Self: ...
    def nice(self, value: bool) -> Self: ...
    def nice_ticks(self, value: int) -> Self: ...
    def categories(self, values: Sequence[str]) -> Self: ...
    def time_domain(self, start: int, end: int) -> Self: ...
    def interval(self, value: Options) -> Self: ...

class Axis(Component):
    def numeric_format(self, value: NumericAxisFormat) -> Self: ...
    def time_format(self, value: TimeAxisFormat) -> Self: ...
    def name(self, value: str) -> Self: ...
    def label(self, value: str) -> Self: ...
    def side(self, value: str) -> Self: ...
    def outside(self, value: str) -> Self: ...
    def visible(self, value: bool) -> Self: ...
    def rotation(self, value: float) -> Self: ...
    def viewport(self, start: float, end: float) -> Self: ...
    def range(self, start: float, end: float) -> Self: ...
    def scale(self, value: Scale) -> Self: ...
    def coordinate_scale(self, value: Scale) -> Self: ...
    def oob(self, value: Literal["Censor","Squish","Keep"]) -> Self: ...
    def text_style(self, value: TextStyle) -> Self: ...
    def rich_label(self, value: RichText) -> Self: ...
    def format(self, value: NumberFormat) -> Self: ...
    def ticks(self, values: Sequence[tuple[ScaleValue, str]]) -> Self: ...
    def secondary(self, source: str, factor: float, offset: float) -> Self: ...

class ColorScale(Component):
    def palette_scheme(self, spec: SchemeSpec) -> Self: ...
    def palette(self, values: Sequence[Color]) -> Self: ...
    def domain(self, values: Sequence[str]) -> Self: ...
    def missing(self, value: Color) -> Self: ...
    def clamp(self, value: bool) -> Self: ...

class Legend(Component):
    def untitled(self) -> Self: ...
    def generic_title(self) -> Self: ...
    def scale(self, value: str) -> Self: ...
    def title(self, value: str) -> Self: ...

class Facet(Component):
    def columns(self, value: int) -> Self: ...
    def empty(self, value: str) -> Self: ...
    def free_x(self, value: bool) -> Self: ...
    def free_y(self, value: bool) -> Self: ...
    def collect_guides(self, value: bool) -> Self: ...
    def gap(self, value: float) -> Self: ...
    def order(self, values: Sequence[Panel]) -> Self: ...

class Style(Component):
    def background(self, value: Color) -> Self: ...
    def panel(self, value: Color) -> Self: ...
    def foreground(self, value: Color) -> Self: ...
    def grid(self, value: Color) -> Self: ...
    def mark(self, value: Color) -> Self: ...
    def annotation(self, value: Color) -> Self: ...
    def focus(self, value: Color) -> Self: ...
    def selection(self, value: Color) -> Self: ...
    def font_size(self, value: float) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def gap(self, value: float) -> Self: ...
    def tick_length(self, value: float) -> Self: ...
    def stroke_width(self, value: float) -> Self: ...
    def dashes(self, values: Sequence[float]) -> Self: ...
    def color_mode(self, value: str) -> Self: ...
    def gradient(self, value: str | Options) -> Self: ...
    def symbol(self, value: str | Options) -> Self: ...

class Theme(Component):
    def geometry(self, *, ink: Color = ..., paper: Color = ..., accent: Color = ..., point_size: float = ..., line_width: float = ...) -> Self: ...
    def preset(self, value: str) -> Self: ...
    def style(self, value: Style) -> Self: ...
    def layer(self, layer: Layer, style: Style) -> Self: ...

class TextStyle(Component):
    def size(self, value: float) -> Self: ...
    def weight(self, value: int) -> Self: ...
    def font(self, value: Options) -> Self: ...
    def fallback(self, value: Options) -> Self: ...
    def color(self, value: Color) -> Self: ...
    def language(self, value: str) -> Self: ...
    def direction(self, value: str) -> Self: ...
    def tabular(self, value: bool) -> Self: ...

class TextRun(Component):
    def style(self, value: TextStyle) -> Self: ...

class RichText(Component):
    def style(self, value: TextStyle) -> Self: ...
    def run(self, value: TextRun) -> Self: ...
    def line(self, value: TextRun) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Title(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Subtitle(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Caption(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class SourceNote(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Footnote(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Labels(Component):
    def id(self, value: str) -> Self: ...
    def text(self, value: str) -> Self: ...
    def at(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def figure_at(self, x: float, y: float) -> Self: ...
    def output_at(self, x: float, y: float) -> Self: ...
    def offset(self, x: float, y: float) -> Self: ...
    def panel_at(self, panel: Panel | None, x: float, y: float) -> Self: ...
    def panel(self, value: Panel) -> Self: ...
    def axes(self, x: str, y: str) -> Self: ...
    def priority(self, value: int) -> Self: ...
    def collision(self, value: str) -> Self: ...
    def overflow(self, value: str) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...

class Callout(Component):
    def label(self, value: Labels) -> Self: ...
    def at(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def to_data(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def to(self, value: Options) -> Self: ...
    def text(self, value: str) -> Self: ...
    def connector_origin(self, value: str) -> Self: ...
    def offset(self, x: float, y: float) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...

class PanelLetter(Component):
    def panel(self, value: Panel) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...

class Inset(Component):
    def id(self, value: str) -> Self: ...
    def panel(self, value: Panel) -> Self: ...
    def rectangle(self, x: float, y: float, width: float, height: float) -> Self: ...
    def x_view(self, start: float, end: float) -> Self: ...
    def y_view(self, start: float, end: float) -> Self: ...
    def guides(self, value: bool) -> Self: ...
    def layer(self, value: Layer) -> Self: ...

class NumberFormat(Component):
    def notation(self, value: str | Options) -> Self: ...
    def precision(self, value: int) -> Self: ...
    def locale(self, value: Options) -> Self: ...
    def grouping(self, value: bool) -> Self: ...
    def prefix(self, value: str) -> Self: ...
    def suffix(self, value: str) -> Self: ...

class LayoutOptions(Component):
    def font_size(self, value: float) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def tick_length(self, value: float) -> Self: ...
    def label_gap(self, value: float) -> Self: ...
    def minimum_plot(self, value: tuple[float, float]) -> Self: ...
    def target_ticks(self, value: int) -> Self: ...
    def max_ticks(self, value: int) -> Self: ...
    def max_categories(self, value: int) -> Self: ...
    def max_vertices(self, value: int) -> Self: ...
    def limits(self, value: Options) -> Self: ...
    def host_theme(self, value: Options) -> Self: ...
    def output_theme(self, value: Options) -> Self: ...
    def interaction_theme(self, value: Options) -> Self: ...
    def figure_bounds(self, value: tuple[float, float, float, float] | None) -> Self: ...
    def host_style(self, value: Style) -> Self: ...
    def output_style(self, value: Style) -> Self: ...

class RenderOptions(Component):
    def line_bucket_width(self, value: float | None) -> Self: ...
    def candle_bucket_width(self, value: float | None) -> Self: ...
    def max_columns(self, value: int) -> Self: ...
    def candle_volume(self, layer: Layer, field: Field) -> Self: ...

class StreamOptions(Component):
    def transactions(self, value: int) -> Self: ...
    def rows(self, value: int) -> Self: ...
    def bytes(self, value: int) -> Self: ...
    def overload(self, value: str) -> Self: ...

class AnnotationEdit(Component):
    def part(self, value: str) -> Self: ...
    def horizontal(self, value: bool) -> Self: ...
    def vertical(self, value: bool) -> Self: ...
    def x(self, value: Options) -> Self: ...
    def y(self, value: Options) -> Self: ...
    def preserve_order(self, horizontal: bool | None) -> Self: ...

class Link(Component):
    def axis(self, source: Axis, destination: Axis) -> Self: ...
    def selection(self, value: bool) -> Self: ...
    def source_panel(self, value: Panel) -> Self: ...
    def destination_panel(self, value: Panel) -> Self: ...
    def missing(self, value: str) -> Self: ...
def aes() -> Aes: ...
def points() -> Layer: ...
def line() -> Layer: ...
def area() -> Layer: ...
def ribbon() -> Layer: ...
def bars() -> Layer: ...
def volume() -> Layer: ...
def ohlc() -> Layer: ...
def rule() -> Layer: ...
def rectangle() -> Layer: ...
def cells() -> Layer: ...
def histogram() -> Layer: ...
def identity_stat() -> Stat: ...
def bin() -> Stat: ...
def count() -> Stat: ...
def summary() -> Stat: ...
def fit() -> Stat: ...
def custom_stat(name: str, version: int, parameters: JSONValue) -> Stat: ...
def stat_aes() -> StatAes: ...
def bin_aes() -> BinAes: ...
def shape_stack(groups: Sequence[str | int | bool | Options]) -> Position: ...
def stack(order: Sequence[str | int | bool | Options]) -> Position: ...
def dodge(order: Sequence[str | int | bool | Options]) -> Position: ...
def jitter(seed: int) -> Position: ...
def filter(field: str | float | Field | SourceExpression | Options) -> Filter: ...
def transform(name: str, stat: Stat) -> Transform: ...
def scale_linear() -> Scale: ...
def scale_log(base: float) -> Scale: ...
def scale_symlog(threshold: float) -> Scale: ...
def scale_band() -> Scale: ...
def scale_point() -> Scale: ...
def scale_utc() -> Scale: ...
def scale_session(calendar: Options) -> Scale: ...
class BandAxisOptions(TypedDict, total=False):
    domain: Sequence[str] | None
    padding_inner: float
    padding_outer: float
    align: float
    round: bool
class PointAxisOptions(TypedDict, total=False):
    domain: Sequence[str] | None
    padding: float
    align: float
    round: bool
class NumericAxisFormat(TypedDict):
    specifier: str
    locale: NotRequired[NumericLocale]
class TimeAxisFormat(TypedDict, total=False):
    pattern: str | None
    locale: TimeLocale
def scale_numeric(spec: StandaloneScale | Options) -> Scale: ...
def scale_registered(name: str, version: int, parameters: JSONValue) -> Scale: ...
def scale_calendar(spec: StandaloneScale | Options) -> Scale: ...
def scale_band_d3(spec: BandAxisOptions) -> Scale: ...
def scale_point_d3(spec: PointAxisOptions) -> Scale: ...
def color_mapped(name: str, scale: StandaloneScale | Options, training: Literal["Authored", "Eligible"] = ...) -> ColorScale: ...
class Guide(Component):
    def scale(self, name: str) -> Self: ...
    def side(self, side: str) -> Self: ...
    def translate(self, x: float, y: float) -> Self: ...
    def label(self, label: str) -> Self: ...
    def rich_label(self, text: RichText) -> Self: ...
    def text_style(self, style: TextStyle) -> Self: ...
    def rotation(self, degrees: float) -> Self: ...
    def visible(self, visible: bool) -> Self: ...
    def ticks(self, ticks: Sequence[tuple[ScaleValue, str]]) -> Self: ...
    def format(self, format: NumberFormat) -> Self: ...
    def numeric_format(self, format: Options) -> Self: ...
    def time_format(self, format: Options) -> Self: ...
def axis_guide(name: str, scale: str) -> Guide: ...
def x_axis() -> Axis: ...
def y_axis() -> Axis: ...
def color_discrete(name: str) -> ColorScale: ...
def color_continuous(name: str, start: float, end: float) -> ColorScale: ...
def legend() -> Legend: ...
def facet_wrap(field: str) -> Facet: ...
def facet_grid(row: str, column: str) -> Facet: ...
def style() -> Style: ...
def theme() -> Theme: ...
def text_style() -> TextStyle: ...
def text_run(text: str) -> TextRun: ...
def rich_text(text: str) -> RichText: ...
def title(text: str) -> Title: ...
def subtitle(text: str) -> Subtitle: ...
def caption(text: str) -> Caption: ...
def source_note(text: str) -> SourceNote: ...
def footnote(text: str) -> Footnote: ...
def labels() -> Labels: ...
def callout() -> Callout: ...
def panel_letter(text: str) -> PanelLetter: ...
def inset() -> Inset: ...
def number_format() -> NumberFormat: ...
def layout_options() -> LayoutOptions: ...
def render_options() -> RenderOptions: ...
def stream_options() -> StreamOptions: ...
def annotation_edit(id: str) -> AnnotationEdit: ...
def link(origin: str) -> Link: ...

class PlotBuilder(_Owned):
    def with_shape_registry(self, registry: ShapeRegistry) -> Self: ...
    def with_registry(self, registry: ShapeRegistry) -> Self: ...
    def data(self, value: Data) -> Self: ...
    def aes(self, value: Aes) -> Self: ...
    def layer(self, value: Layer | Labels | Callout | VectorPath) -> Self: ...
    def title(self, value: Title) -> Self: ...
    def subtitle(self, value: Subtitle) -> Self: ...
    def caption(self, value: Caption) -> Self: ...
    def source_note(self, value: SourceNote) -> Self: ...
    def footnote(self, value: Footnote) -> Self: ...
    def guide(self, value: Guide) -> Self: ...
    def x_axis(self, value: Axis) -> Self: ...
    def y_axis(self, value: Axis) -> Self: ...
    def axis(self, value: Axis) -> Self: ...
    def scale(self, value: ColorScale) -> Self: ...
    def legend(self, value: Legend) -> Self: ...
    def facet(self, value: Facet) -> Self: ...
    def theme(self, value: Theme) -> Self: ...
    def panel_letter(self, value: PanelLetter) -> Self: ...
    def inset(self, value: Inset) -> Self: ...
    def transform(self, value: Transform) -> Self: ...
    def profile(self, value: Literal["LibraryV1","Ggplot2_4_0_3"]) -> Self: ...
    def compile_limits(self, value: Options) -> Self: ...
    def data_limits(self, value: Options) -> Self: ...
    def build(self) -> Plot: ...
class PlotEdit(_Owned):
    def profile(self, value: Literal["LibraryV1","Ggplot2_4_0_3"]) -> Self: ...
    def layer(self, name: str, value: Layer) -> Self: ...
    def annotation(self, value: Labels | Callout | VectorPath) -> Self: ...
    def remove_layer(self, name: str) -> Self: ...
    def remove_annotation(self, id: str) -> Self: ...
    def clear_facets(self) -> Self: ...
    def title(self, value: Title) -> Self: ...
    def subtitle(self, value: Subtitle) -> Self: ...
    def caption(self, value: Caption) -> Self: ...
    def source_note(self, value: SourceNote) -> Self: ...
    def footnote(self, value: Footnote) -> Self: ...
    def guide(self, value: Guide) -> Self: ...
    def x_axis(self, value: Axis) -> Self: ...
    def y_axis(self, value: Axis) -> Self: ...
    def axis(self, value: Axis) -> Self: ...
    def scale(self, value: ColorScale) -> Self: ...
    def legend(self, value: Legend) -> Self: ...
    def facet(self, value: Facet) -> Self: ...
    def theme(self, value: Theme) -> Self: ...
    def panel_letter(self, value: PanelLetter) -> Self: ...
    def inset(self, value: Inset) -> Self: ...
    def transform(self, value: Transform) -> Self: ...
    def build(self) -> Plot: ...
def plot(data: Data) -> PlotBuilder: ...
class Plot(_Owned):
    def edit(self) -> PlotEdit: ...
    def chart(self) -> Chart: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str, registry: ShapeRegistry | None = ...) -> Plot: ...
class ExportOptions(_Owned):
    def dpi(self, value: int) -> Self: ...
    def page(self, width: float, height: float, unit: Literal["pt", "mm"]) -> Self: ...
    def precision(self, value: int) -> Self: ...
    def max_raster_pixels(self, value: int) -> Self: ...
    def max_output_bytes(self, value: int) -> Self: ...
    def background(self, value: Color) -> Self: ...
    def interaction(self, value: Options) -> Self: ...
    def basis(self, value: Literal["presented", "current", "Presented", "Current"]) -> Self: ...
    def view(self, value: Literal["visible", "full_domain", "VisibleView", "FullDomain"]) -> Self: ...
    def text(self, value: Literal["preserve", "outline", "Preserve", "Outline"]) -> Self: ...
    def layout(self, value: LayoutOptions) -> Self: ...
def export_options(width: float, height: float, unit: Literal["pt", "mm"] = ...) -> ExportOptions: ...
class FigureRequest(_Owned):
    def prepare(self) -> FigureSnapshot: ...
    def manifest(self) -> dict[str, object]: ...
class FigureSnapshot(_Owned):
    def scene(self) -> dict[str, object]: ...
    def manifest(self) -> dict[str, object]: ...
    def export(self, format: Format) -> bytes: ...
    def save(self, path: str | PathLike[str], format: Format) -> None: ...
class Output(_Owned):
    def __init__(self, font: bytes | bytearray | Iterable[int]) -> None: ...
    def primary_font(self) -> dict[str, object]: ...
    def register_font(self, font: bytes | bytearray | Iterable[int]) -> dict[str, object]: ...
    def request(self, source: Plot | Chart, options: ExportOptions) -> FigureRequest: ...
    def export(self, source: Plot | Chart, format: Format, options: ExportOptions) -> bytes: ...
    def save(self, source: Plot | Chart, path: str | PathLike[str], format: Format, options: ExportOptions) -> None: ...
class ExportJob(_Owned):
    def cancel(self) -> bool: ...
    def run(self) -> bytes: ...
class ExportQueue(_Owned):
    def __init__(self, *, max_jobs: int = ..., max_input_bytes: int = ..., max_rows: int = ...) -> None: ...
    def submit(self, request: FigureRequest, format: Format) -> ExportJob: ...
    def metrics(self) -> dict[str, object]: ...
class Transaction(_Owned): ...
class Updates(_Owned):
    def id(self, value: str) -> Updates: ...
    def append(self, target: Data | str, data: Data) -> Updates: ...
    def upsert(self, target: Data | str, data: Data) -> Updates: ...
    def replace(self, target: Data | str, data: Data) -> Updates: ...
    def remove(self, target: Data | str, keys: Iterable[int]) -> Updates: ...
    def retain_count(self, target: Data | str, count: int | None) -> Updates: ...
    def retain_event_time(self, target: Data | str, field: str, width: int, watermark: int, *, allowed_lateness: int = ..., late: Literal["Reject", "Drop"] = ...) -> Updates: ...
    def retention(self, target: Data | str, policy: str | Options) -> Updates: ...
    def watermark(self, target: Data | str, ticks: int) -> Updates: ...
    def reset_categories(self, target: Data | str, field: str) -> Updates: ...
    def build(self) -> Transaction: ...
class Editor(_Owned):
    def original(self) -> dict[str, object]: ...
    def preview(self, dx: float, dy: float) -> dict[str, object]: ...
    def nudge(self, *, horizontal: bool = ..., forward: bool = ..., steps: int = ...) -> dict[str, object]: ...
class Chart(_Owned):
    def __init__(self, plot: Plot) -> None: ...
    def external_view(self) -> Chart: ...
    def accept_from(self, source: Chart) -> dict[str, object]: ...
    def revisions(self) -> Revisions: ...
    def semantics(self) -> dict[str, object]: ...
    def state(self) -> dict[str, object]: ...
    def apply_plot(self, plot: Plot, expected: int) -> bool: ...
    def restore_state(self, state: Options, expected: int) -> None: ...
    def act(self, action: str | Options, *, origin: str | Options = ..., expected: int | None = ...) -> DispatchOutcome: ...
    def query(self, operation: Options, *, gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def layer_visible(self, layer: str, visible: bool, *, expected: int | None = ...) -> DispatchOutcome: ...
    def legend_visible(self, visible: bool, *, expected: int | None = ...) -> DispatchOutcome: ...
    def follow(self, mode: Literal["FollowLatest", "InspectHistory", "FreezePresentation"] = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def freeze(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def resume(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def reset(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def undo(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def redo(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def clear_inspection(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def select(self, targets: Sequence[Options], change: Literal["Replace", "Add", "Remove", "Toggle"] = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def hover(self, targets: Sequence[Options], *, expected: int | None = ...) -> DispatchOutcome: ...
    def focus(self, target: Options | None = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def pin(self, target: Options | None = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def set_annotation(self, annotation: Options, *, expected: int | None = ...) -> DispatchOutcome: ...
    def remove_annotation(self, id: str, *, expected: int | None = ...) -> DispatchOutcome: ...
    def set_windows(self, windows: Options, *, expected: int | None = ...) -> DispatchOutcome: ...
    def editor(self, options: AnnotationEdit) -> Editor: ...
    def describe(self, offset: int = ..., limit: int = ..., *, gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def inspect(self, x: float, y: float, *, radius: float = ..., max_grouped: int = ..., mode: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def select_region(self, region: Options, *, limit: int = ..., gesture: bool = ..., stamp: Options | None = ...) -> SelectionResult: ...
    def select_series(self, layer: str, *, panel: Panel | None = ..., limit: int = ..., gesture: bool = ..., stamp: Options | None = ...) -> SelectionResult: ...
    def navigate(self, action: str | Options, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def zoom(self, x: float, y: float, factor: float, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def pan(self, dx: float, dy: float, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def range(self, axis: str, window: str | Options, *, panel: Panel | None = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def present(self, output: Output, options: ExportOptions) -> FigureSnapshot: ...
    def request(self, output: Output, options: ExportOptions) -> FigureRequest: ...
    def stream(self, options: StreamOptions) -> Self: ...
    def transaction(self) -> Updates: ...
    def commit(self, transaction: Transaction) -> dict[str, object]: ...
    def enqueue(self, transaction: Transaction) -> dict[str, object] | str: ...
    def stream_status(self) -> dict[str, object]: ...
    def pinned(self) -> dict[str, object] | None: ...
    def queue_status(self) -> dict[str, object]: ...
    def commit_next(self) -> dict[str, object] | None: ...
    def reset_epoch(self) -> dict[str, object]: ...
    def dense(self, frame: FigureSnapshot, options: RenderOptions) -> dict[str, object]: ...
    def link_capture(self, component: Link, event: Options) -> dict[str, object] | None: ...
    def link_resolve(self, component: Link, message: Options) -> dict[str, object]: ...
# Explicit compatibility entry point; the primary API above does not require envelopes.
class LegacyChart:
    def __init__(self, definition: str, data: str, profile: str, font: list[int] | bytes) -> None: ...
    def semantics(self) -> str: ...
    def scene(self) -> str: ...
    def export(self, format: str) -> list[int]: ...
    def transaction(self, input: str) -> str: ...
    def dense_preview(self, request: str) -> str: ...
    def stream(self, input: str) -> str: ...
    def export_control(self, input: str) -> str: ...
    def export_job(self, job: str) -> list[int]: ...
    def action(self, input: str) -> str: ...
    def definition(self) -> str: ...
    def present(self) -> str: ...
    def query(self, input: str) -> str: ...
    def dispatch(self, input: str) -> str: ...
    def state(self) -> str: ...
    def restore_state(self, input: str, expected: str) -> None: ...
    def dispose(self) -> None: ...

class Path(_Owned):
    def __init__(self, digits: float | None = ..., *, limits: Options | None = ...) -> None: ...
    @classmethod
    def from_json(cls, request: str) -> Path: ...
    def copy(self) -> Path: ...
    def move_to(self, x: float, y: float) -> Self: ...
    def line_to(self, x: float, y: float) -> Self: ...
    def quadratic_curve_to(self, cx: float, cy: float, x: float, y: float) -> Self: ...
    def bezier_curve_to(self, cx1: float, cy1: float, cx2: float, cy2: float, x: float, y: float) -> Self: ...
    def arc_to(self, x1: float, y1: float, x2: float, y2: float, r: float) -> Self: ...
    def arc(self, x: float, y: float, r: float, a0: float, a1: float, anticlockwise: bool = ...) -> Self: ...
    def rect(self, x: float, y: float, w: float, h: float) -> Self: ...
    def close_path(self) -> Self: ...
    def apply_batch(self, operations: Sequence[Options]) -> Self: ...
    def to_svg(self) -> str: ...
    def result(self) -> dict[str, JSONValue]: ...
    def replay(self, sink: Callable[[JSONValue], object]) -> None: ...
def path() -> Path: ...
def path_round(digits: float = ...) -> Path: ...
class VectorPath(Component):
    def transform(self, matrix: Sequence[float], *, max_error: float = ..., max_commands: int = ...) -> Self: ...
    def anchor(self, value: Options) -> Self: ...
    def fill(self, value: Options | None) -> Self: ...
    def stroke(self, value: Options | None) -> Self: ...
    def overflow(self, value: bool) -> Self: ...
def vector_path(id: str, path: Path) -> VectorPath: ...

from ._interpolation import (
    NumericArrayKind as NumericArrayKind,
    InterpolationInput as InterpolationInput,
    InterpolationResult as InterpolationResult,
    NumericInterpolationInput as NumericInterpolationInput,
    ColorInterpolationInput as ColorInterpolationInput,
    ArrayInterpolationInput as ArrayInterpolationInput,
    MissingValue as MissingValue,
    MISSING as MISSING,
    InterpolationDate as InterpolationDate,
    NumericArray as NumericArray,
    Interpolator as Interpolator,
    date_value as date_value,
    numeric_array as numeric_array,
    piecewise as piecewise,
    quantize as quantize,
    interpolate as interpolate,
    interpolate_number as interpolate_number,
    interpolate_round as interpolate_round,
    interpolate_hue as interpolate_hue,
    interpolate_string as interpolate_string,
    interpolate_date as interpolate_date,
    interpolate_array as interpolate_array,
    interpolate_number_array as interpolate_number_array,
    interpolate_object as interpolate_object,
    interpolate_rgb as interpolate_rgb,
    interpolate_hsl as interpolate_hsl,
    interpolate_hsl_long as interpolate_hsl_long,
    interpolate_lab as interpolate_lab,
    interpolate_hcl as interpolate_hcl,
    interpolate_hcl_long as interpolate_hcl_long,
    interpolate_cubehelix as interpolate_cubehelix,
    interpolate_cubehelix_long as interpolate_cubehelix_long,
    interpolate_basis as interpolate_basis,
    interpolate_basis_closed as interpolate_basis_closed,
    interpolate_rgb_basis as interpolate_rgb_basis,
    interpolate_rgb_basis_closed as interpolate_rgb_basis_closed,
    interpolate_discrete as interpolate_discrete,
    interpolate_transform_css as interpolate_transform_css,
    interpolate_transform_svg as interpolate_transform_svg,
    interpolate_zoom as interpolate_zoom,
)

from ._interpolation import (ChromaticSchemeId as ChromaticSchemeId, ChromaticInterpolatorId as ChromaticInterpolatorId, SchemeSpec as SchemeSpec, SchemeInfo as SchemeInfo, ChromaticCatalog as ChromaticCatalog, chromatic_catalog as chromatic_catalog, chromatic_scheme as chromatic_scheme, chromatic as chromatic)

from ._shape import (CurveSpec as CurveSpec, ShapeCoordinate as ShapeCoordinate, ShapeLimits as ShapeLimits, ShapeLineConfig as ShapeLineConfig, ShapeAreaConfig as ShapeAreaConfig)
from ._shape import ShapeOperationId as ShapeOperationId, ShapeOperation as ShapeOperation, ShapeFamily as ShapeFamily
class ShapeRegistry(_Owned):
    def __init__(self) -> None: ...
    @staticmethod
    def example() -> ShapeRegistry: ...
    def copy(self) -> ShapeRegistry: ...
    def selection(self, selection: ShapeOperation, family: ShapeFamily) -> ShapeOperation: ...

class ShapeLine(_Owned):
    def generate_registered(self, data: Sequence[Sequence[float]], registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeLineConfig | None = ...) -> None: ...
    def copy(self) -> ShapeLine: ...
    def config(self) -> ShapeLineConfig: ...
    def generate(self, rows: Sequence[Sequence[float]]) -> Path: ...
class ShapeArea(_Owned):
    def generate_registered(self, data: Sequence[Sequence[float]], registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeAreaConfig | None = ...) -> None: ...
    def copy(self) -> ShapeArea: ...
    def config(self) -> ShapeAreaConfig: ...
    def generate(self, rows: Sequence[Sequence[float]]) -> Path: ...
    def boundary(self, which: Literal['X0','X1','Y0','Y1']) -> ShapeLine: ...
def shape_line() -> Layer: ...
def shape_area() -> Layer: ...

from ._shape import (ArcDatum as ArcDatum, ShapeArcConfig as ShapeArcConfig, PieAngles as PieAngles, ShapePieConfig as ShapePieConfig, PieSlice as PieSlice)
class ShapeArc(_Owned):
    def __init__(self, config: ShapeArcConfig | None = ...) -> None: ...
    def copy(self) -> ShapeArc: ...
    def config(self) -> ShapeArcConfig: ...
    def generate(self, datum: ArcDatum | None = ...) -> Path: ...
    def centroid(self, datum: ArcDatum | None = ...) -> list[float]: ...
class ShapePie(_Owned):
    def layout_registered(self, data: Sequence[JSONValue], values: Sequence[float], registry: ShapeRegistry, selection: ShapeOperation) -> list[PieSlice]: ...
    def __init__(self, config: ShapePieConfig | None = ...) -> None: ...
    def copy(self) -> ShapePie: ...
    def config(self) -> ShapePieConfig: ...
    @overload
    def layout(self, data: Sequence[float], values: None = ...) -> list[PieSlice]: ...
    @overload
    def layout(self, data: Sequence[object], values: Sequence[float]) -> list[PieSlice]: ...

def shape_arc() -> Layer: ...
def shape_pie() -> Layer: ...
from ._shape import ArcParameters as ArcParameters

from ._shape import SymbolKind as SymbolKind, ShapeSymbolConfig as ShapeSymbolConfig
class ShapeSymbol(_Owned):
    def generate_registered(self, registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeSymbolConfig | None = ...) -> None: ...
    def copy(self) -> ShapeSymbol: ...
    def config(self) -> ShapeSymbolConfig: ...
    def generate(self) -> Path: ...
    @staticmethod
    def palettes() -> tuple[tuple[SymbolKind, ...], tuple[SymbolKind, ...]]: ...

def shape_symbol() -> Layer: ...

from ._shape import ShapeStackConfig as ShapeStackConfig, StackOrder as StackOrder, StackOffset as StackOffset, StackMissing as StackMissing, StackLimits as StackLimits, StackPoint as StackPoint, StackSeries as StackSeries
class ShapeStack(_Owned):
    def layout_registered(self, data: Sequence[JSONValue], values: Sequence[Sequence[float | None]], registry: ShapeRegistry, order: ShapeOperation | None = ..., offset: ShapeOperation | None = ...) -> list[StackSeries]: ...
    def __init__(self, config: ShapeStackConfig | None = ...) -> None: ...
    def copy(self) -> ShapeStack: ...
    def config(self) -> ShapeStackConfig: ...
    @overload
    def layout(self, data: Sequence[Sequence[float | None]]) -> list[StackSeries]: ...
    @overload
    def layout(self, data: Sequence[object], values: Sequence[Sequence[float | None]]) -> list[StackSeries]: ...

from ._shape import (ShapeLineRadialConfig as ShapeLineRadialConfig, ShapeAreaRadialConfig as ShapeAreaRadialConfig, ShapeLinkConfig as ShapeLinkConfig, ShapeLinkRadialConfig as ShapeLinkRadialConfig, RadialBoundary as RadialBoundary, LinkEndpoint as LinkEndpoint, LinkDatum as LinkDatum)
class ShapeLineRadial(_Owned):
    def generate_registered(self, data: Sequence[Sequence[float]], registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeLineRadialConfig | None = ...) -> None: ...
    def copy(self) -> ShapeLineRadial: ...
    def config(self) -> ShapeLineRadialConfig: ...
    def generate(self, data: Sequence[Sequence[float]]) -> Path: ...
class ShapeAreaRadial(_Owned):
    def generate_registered(self, data: Sequence[Sequence[float]], registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeAreaRadialConfig | None = ...) -> None: ...
    def copy(self) -> ShapeAreaRadial: ...
    def config(self) -> ShapeAreaRadialConfig: ...
    def generate(self, data: Sequence[Sequence[float]]) -> Path: ...
    def boundary(self, which: RadialBoundary) -> ShapeLineRadial: ...
class ShapeLink(_Owned):
    def generate_registered(self, data: LinkDatum, registry: ShapeRegistry, selection: ShapeOperation) -> Path: ...
    def __init__(self, config: ShapeLinkConfig | None = ...) -> None: ...
    def copy(self) -> ShapeLink: ...
    def config(self) -> ShapeLinkConfig: ...
    def generate(self, data: LinkDatum) -> Path: ...
class ShapeLinkRadial(_Owned):
    def __init__(self, config: ShapeLinkRadialConfig | None = ...) -> None: ...
    def copy(self) -> ShapeLinkRadial: ...
    def config(self) -> ShapeLinkRadialConfig: ...
    def generate(self, data: LinkDatum) -> Path: ...
def point_radial(angle: float, radius: float) -> tuple[float, float]: ...

from ._shape import RadialParameters as RadialParameters
def shape_line_radial() -> Layer: ...
def shape_area_radial() -> Layer: ...
def shape_link_horizontal() -> Layer: ...
def shape_link_vertical() -> Layer: ...
def shape_link_radial() -> Layer: ...
def shape_link(curve: CurveSpec) -> Layer: ...

# General extension registry; the prior shape-specific spelling remains an alias.
ExtensionRegistry = ShapeRegistry
