# Primary host contract. Small options retain the core enum/field spellings.
from collections.abc import Callable, Iterable, Mapping, Sequence
from os import PathLike
from typing import Literal, Self, TypeAlias, TypedDict, overload

JSONValue: TypeAlias = None | bool | int | float | str | Sequence["JSONValue"] | Mapping[str, "JSONValue"]
Options: TypeAlias = Mapping[str, object]
Color: TypeAlias = str | Options
Panel: TypeAlias = Sequence[str | int | bool | Options] | Options
ScaleValue: TypeAlias = float | str | Options
MappingValue: TypeAlias = str | float | Field | Options
Format: TypeAlias = Literal["svg", "pdf", "png"]
ColumnKind: TypeAlias = Literal["float64", "int64", "uint64", "bool", "string", "category", "s", "ms", "us", "ns"]
class ActionOutcome(TypedDict):
    changed: bool
    revision: str
    viewport_changed: bool
class DispatchOutcome(TypedDict):
    outcome: ActionOutcome
    event: dict[str, object] | None
class SelectionResult(TypedDict):
    targets: list[dict[str, object]]
class WindowResult(TypedDict):
    windows: dict[str, object]
class Revisions(TypedDict):
    definition: int
    state: int
    epoch: int
    store: int
class ChartError(Exception):
    code: str
    message: str
    correction: str
    context: dict[str, object]
    diagnostic: dict[str, object]
class _Owned:
    def dispose(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
class Field(_Owned): ...
class Column(_Owned):
    def nullable(self, value: bool = ...) -> Column: ...
    def validity(self, values: Iterable[bool]) -> Column: ...
    def formatted(self, values: Iterable[str | None]) -> Column: ...
    def unit(self, value: str) -> Column: ...
    def label(self, value: str) -> Column: ...
def column(values: Iterable[float | int | bool | str | None], *, kind: ColumnKind | None = ..., timezone: str = ...) -> Column: ...
def categorical(values: Iterable[str | None]) -> Column: ...
def timestamps(values: Iterable[int | None], unit: Literal["s","ms","us","ns"] = ..., timezone: str = ...) -> Column: ...
class Data(_Owned):
    @staticmethod
    def columns(columns: Mapping[str, Column | Iterable[float | int | bool | str | None]], *, name: str = ..., keys: Iterable[int] | None = ..., limits: Options | None = ..., schema_version: int | None = ..., identity: int | None = ...) -> Data: ...
    @staticmethod
    def rows(rows: Iterable[object], *, fields: Mapping[str, Callable[..., object]] | None = ..., name: str = ..., keys: Iterable[int] | Callable[..., int] | None = ..., limits: Options | None = ..., schema_version: int | None = ..., identity: int | None = ...) -> Data: ...
    def field(self, name: str) -> Field: ...
    @property
    def name(self) -> str: ...
class Component(_Owned): ...

class Aes(Component):
    def x(self, value: MappingValue) -> Self: ...
    def y(self, value: MappingValue) -> Self: ...
    def x2(self, value: MappingValue) -> Self: ...
    def y2(self, value: MappingValue) -> Self: ...
    def low(self, value: MappingValue) -> Self: ...
    def high(self, value: MappingValue) -> Self: ...
    def size(self, value: MappingValue) -> Self: ...
    def group(self, value: MappingValue) -> Self: ...
    def color(self, value: MappingValue) -> Self: ...
    def group_all(self) -> Self: ...
    def color_scale(self, name: str) -> Self: ...

class Layer(Component):
    def color_group(self, scale: str) -> Self: ...
    def name(self, name: str) -> Self: ...
    def data(self, data: Data) -> Self: ...
    def aes(self, mapping: Aes) -> Self: ...
    def stat(self, value: Stat) -> Self: ...
    def after_stat(self, mapping: StatAes) -> Self: ...
    def after_bin(self, mapping: BinAes) -> Self: ...
    def filter(self, value: Filter) -> Self: ...
    def position(self, value: Position) -> Self: ...
    def style(self, value: Style) -> Self: ...
    def from_transform(self, value: str | Transform) -> Self: ...
    def independent(self) -> Self: ...
    def size(self, value: float) -> Self: ...
    def width(self, value: float) -> Self: ...
    def baseline(self, value: float) -> Self: ...
    def color(self, value: Color) -> Self: ...
    def axes(self, x: str, y: str) -> Self: ...
    def scope(self, value: str) -> Self: ...
    def facet_target(self, value: Options) -> Self: ...
    def clip(self, value: bool) -> Self: ...
    def connect_gaps(self, value: bool) -> Self: ...
    def invalid(self, value: str) -> Self: ...
    def order(self, value: str) -> Self: ...
    def candle_colors(self, value: Options) -> Self: ...
    def bins(self, count: int) -> Self: ...
    def breaks(self, values: Sequence[float]) -> Self: ...
    def geometry(self, name: str, version: int, parameters: JSONValue) -> Self: ...

class Stat(Component):
    def field_parameter(self, name: str, value: MappingValue) -> Self: ...
    def x(self, value: MappingValue) -> Self: ...
    def y(self, value: MappingValue) -> Self: ...
    def group(self, value: MappingValue) -> Self: ...
    def group_all(self) -> Self: ...
    def bins(self, count: int) -> Self: ...
    def breaks(self, values: Sequence[float]) -> Self: ...
    def quantiles(self, values: Sequence[float]) -> Self: ...
    def required(self, values: Sequence[str | float | Options]) -> Self: ...
    def outliers(self, value: str) -> Self: ...
    def empty_sum_zero(self, value: bool) -> Self: ...
    def transform(self, factor: float, offset: float) -> Self: ...
    def y_transform(self, factor: float, offset: float) -> Self: ...

class StatAes(Component):
    def x(self, value: str | float | Options) -> Self: ...
    def y(self, value: str | float | Options) -> Self: ...
    def x2(self, value: str | float | Options) -> Self: ...
    def y2(self, value: str | float | Options) -> Self: ...
    def size(self, value: str | float | Options) -> Self: ...
    def color(self, value: str | Options) -> Self: ...
    def color_scale(self, name: str) -> Self: ...
    def color_group(self, name: str) -> Self: ...

class BinAes(Component):
    def x(self, value: str | float | Options) -> Self: ...
    def y(self, value: str | float | Options) -> Self: ...
    def x2(self, value: str | float | Options) -> Self: ...
    def y2(self, value: str | float | Options) -> Self: ...
    def color_group(self, name: str) -> Self: ...

    def size(self, value: str | float | Options) -> Self: ...

class Position(Component):
    def normalize(self, value: bool) -> Self: ...
    def width(self, value: float) -> Self: ...
    def displacement(self, x: float, y: float) -> Self: ...
    def units(self, value: str) -> Self: ...

class Filter(Component):
    def minimum(self, value: float) -> Self: ...
    def maximum(self, value: float) -> Self: ...

class Transform(Component):
    def data(self, data: Data) -> Self: ...
    def aes(self, value: Aes) -> Self: ...
    def filter(self, value: Filter) -> Self: ...
    def from_transform(self, value: str | Transform) -> Self: ...
    def scope(self, value: str) -> Self: ...
    def invalid(self, value: str) -> Self: ...
    def facet_target(self, value: Options) -> Self: ...

class Scale(Component):
    def domain(self, start: float, end: float) -> Self: ...
    def band_padding(self, start: float, end: float) -> Self: ...
    def baseline(self, value: str) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def point_padding(self, value: float) -> Self: ...
    def nice(self, value: bool) -> Self: ...
    def nice_ticks(self, value: int) -> Self: ...
    def categories(self, values: Sequence[str]) -> Self: ...
    def time_domain(self, start: int, end: int) -> Self: ...
    def interval(self, value: Options) -> Self: ...

class Axis(Component):
    def name(self, value: str) -> Self: ...
    def label(self, value: str) -> Self: ...
    def side(self, value: str) -> Self: ...
    def outside(self, value: str) -> Self: ...
    def visible(self, value: bool) -> Self: ...
    def rotation(self, value: float) -> Self: ...
    def viewport(self, start: float, end: float) -> Self: ...
    def range(self, start: float, end: float) -> Self: ...
    def scale(self, value: Scale) -> Self: ...
    def text_style(self, value: TextStyle) -> Self: ...
    def rich_label(self, value: RichText) -> Self: ...
    def format(self, value: NumberFormat) -> Self: ...
    def ticks(self, values: Sequence[tuple[ScaleValue, str]]) -> Self: ...
    def secondary(self, source: str, factor: float, offset: float) -> Self: ...

class ColorScale(Component):
    def palette(self, values: Sequence[Color]) -> Self: ...
    def domain(self, values: Sequence[str]) -> Self: ...
    def missing(self, value: Color) -> Self: ...
    def clamp(self, value: bool) -> Self: ...

class Legend(Component):
    def untitled(self) -> Self: ...
    def scale(self, value: str) -> Self: ...
    def title(self, value: str) -> Self: ...

class Facet(Component):
    def columns(self, value: int) -> Self: ...
    def empty(self, value: str) -> Self: ...
    def free_x(self, value: bool) -> Self: ...
    def free_y(self, value: bool) -> Self: ...
    def collect_guides(self, value: bool) -> Self: ...
    def gap(self, value: float) -> Self: ...
    def order(self, values: Sequence[Panel]) -> Self: ...

class Style(Component):
    def background(self, value: Color) -> Self: ...
    def panel(self, value: Color) -> Self: ...
    def foreground(self, value: Color) -> Self: ...
    def grid(self, value: Color) -> Self: ...
    def mark(self, value: Color) -> Self: ...
    def annotation(self, value: Color) -> Self: ...
    def focus(self, value: Color) -> Self: ...
    def selection(self, value: Color) -> Self: ...
    def font_size(self, value: float) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def gap(self, value: float) -> Self: ...
    def tick_length(self, value: float) -> Self: ...
    def stroke_width(self, value: float) -> Self: ...
    def dashes(self, values: Sequence[float]) -> Self: ...
    def color_mode(self, value: str) -> Self: ...
    def gradient(self, value: str | Options) -> Self: ...
    def symbol(self, value: str | Options) -> Self: ...

class Theme(Component):
    def preset(self, value: str) -> Self: ...
    def style(self, value: Style) -> Self: ...
    def layer(self, layer: Layer, style: Style) -> Self: ...

class TextStyle(Component):
    def size(self, value: float) -> Self: ...
    def weight(self, value: int) -> Self: ...
    def font(self, value: Options) -> Self: ...
    def fallback(self, value: Options) -> Self: ...
    def color(self, value: Color) -> Self: ...
    def language(self, value: str) -> Self: ...
    def direction(self, value: str) -> Self: ...
    def tabular(self, value: bool) -> Self: ...

class TextRun(Component):
    def style(self, value: TextStyle) -> Self: ...

class RichText(Component):
    def style(self, value: TextStyle) -> Self: ...
    def run(self, value: TextRun) -> Self: ...
    def line(self, value: TextRun) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Title(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Subtitle(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Caption(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class SourceNote(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Footnote(Component):
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...
    def line_spacing(self, value: float) -> Self: ...
    def rotation(self, value: float) -> Self: ...

class Labels(Component):
    def id(self, value: str) -> Self: ...
    def text(self, value: str) -> Self: ...
    def at(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def figure_at(self, x: float, y: float) -> Self: ...
    def output_at(self, x: float, y: float) -> Self: ...
    def offset(self, x: float, y: float) -> Self: ...
    def panel_at(self, panel: Panel | None, x: float, y: float) -> Self: ...
    def panel(self, value: Panel) -> Self: ...
    def axes(self, x: str, y: str) -> Self: ...
    def priority(self, value: int) -> Self: ...
    def collision(self, value: str) -> Self: ...
    def overflow(self, value: str) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...

class Callout(Component):
    def label(self, value: Labels) -> Self: ...
    def at(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def to_data(self, x: ScaleValue, y: ScaleValue) -> Self: ...
    def to(self, value: Options) -> Self: ...
    def text(self, value: str) -> Self: ...
    def connector_origin(self, value: str) -> Self: ...
    def offset(self, x: float, y: float) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...

class PanelLetter(Component):
    def panel(self, value: Panel) -> Self: ...
    def style(self, value: TextStyle) -> Self: ...
    def rich(self, value: RichText) -> Self: ...

class Inset(Component):
    def id(self, value: str) -> Self: ...
    def panel(self, value: Panel) -> Self: ...
    def rectangle(self, x: float, y: float, width: float, height: float) -> Self: ...
    def x_view(self, start: float, end: float) -> Self: ...
    def y_view(self, start: float, end: float) -> Self: ...
    def guides(self, value: bool) -> Self: ...
    def layer(self, value: Layer) -> Self: ...

class NumberFormat(Component):
    def notation(self, value: str | Options) -> Self: ...
    def precision(self, value: int) -> Self: ...
    def locale(self, value: Options) -> Self: ...
    def grouping(self, value: bool) -> Self: ...
    def prefix(self, value: str) -> Self: ...
    def suffix(self, value: str) -> Self: ...

class LayoutOptions(Component):
    def font_size(self, value: float) -> Self: ...
    def padding(self, value: float) -> Self: ...
    def tick_length(self, value: float) -> Self: ...
    def label_gap(self, value: float) -> Self: ...
    def minimum_plot(self, value: tuple[float, float]) -> Self: ...
    def target_ticks(self, value: int) -> Self: ...
    def max_ticks(self, value: int) -> Self: ...
    def max_categories(self, value: int) -> Self: ...
    def max_vertices(self, value: int) -> Self: ...
    def limits(self, value: Options) -> Self: ...
    def host_theme(self, value: Options) -> Self: ...
    def output_theme(self, value: Options) -> Self: ...
    def interaction_theme(self, value: Options) -> Self: ...
    def figure_bounds(self, value: tuple[float, float, float, float] | None) -> Self: ...
    def host_style(self, value: Style) -> Self: ...
    def output_style(self, value: Style) -> Self: ...

class RenderOptions(Component):
    def line_bucket_width(self, value: float | None) -> Self: ...
    def candle_bucket_width(self, value: float | None) -> Self: ...
    def max_columns(self, value: int) -> Self: ...
    def candle_volume(self, layer: Layer, field: Field) -> Self: ...

class StreamOptions(Component):
    def transactions(self, value: int) -> Self: ...
    def rows(self, value: int) -> Self: ...
    def bytes(self, value: int) -> Self: ...
    def overload(self, value: str) -> Self: ...

class AnnotationEdit(Component):
    def part(self, value: str) -> Self: ...
    def horizontal(self, value: bool) -> Self: ...
    def vertical(self, value: bool) -> Self: ...
    def x(self, value: Options) -> Self: ...
    def y(self, value: Options) -> Self: ...
    def preserve_order(self, horizontal: bool | None) -> Self: ...

class Link(Component):
    def axis(self, source: Axis, destination: Axis) -> Self: ...
    def selection(self, value: bool) -> Self: ...
    def source_panel(self, value: Panel) -> Self: ...
    def destination_panel(self, value: Panel) -> Self: ...
    def missing(self, value: str) -> Self: ...
def aes() -> Aes: ...
def points() -> Layer: ...
def line() -> Layer: ...
def area() -> Layer: ...
def ribbon() -> Layer: ...
def bars() -> Layer: ...
def volume() -> Layer: ...
def ohlc() -> Layer: ...
def rule() -> Layer: ...
def rectangle() -> Layer: ...
def cells() -> Layer: ...
def histogram() -> Layer: ...
def identity_stat() -> Stat: ...
def bin() -> Stat: ...
def count() -> Stat: ...
def summary() -> Stat: ...
def fit() -> Stat: ...
def custom_stat(name: str, version: int, parameters: JSONValue) -> Stat: ...
def stat_aes() -> StatAes: ...
def bin_aes() -> BinAes: ...
def stack(order: Sequence[str | int | bool | Options]) -> Position: ...
def dodge(order: Sequence[str | int | bool | Options]) -> Position: ...
def jitter(seed: int) -> Position: ...
def filter(field: str | float | Options) -> Filter: ...
def transform(name: str, stat: Stat) -> Transform: ...
def scale_linear() -> Scale: ...
def scale_log(base: float) -> Scale: ...
def scale_symlog(threshold: float) -> Scale: ...
def scale_band() -> Scale: ...
def scale_point() -> Scale: ...
def scale_utc() -> Scale: ...
def scale_session(calendar: Options) -> Scale: ...
def x_axis() -> Axis: ...
def y_axis() -> Axis: ...
def color_discrete(name: str) -> ColorScale: ...
def color_continuous(name: str, start: float, end: float) -> ColorScale: ...
def legend() -> Legend: ...
def facet_wrap(field: str) -> Facet: ...
def facet_grid(row: str, column: str) -> Facet: ...
def style() -> Style: ...
def theme() -> Theme: ...
def text_style() -> TextStyle: ...
def text_run(text: str) -> TextRun: ...
def rich_text(text: str) -> RichText: ...
def title(text: str) -> Title: ...
def subtitle(text: str) -> Subtitle: ...
def caption(text: str) -> Caption: ...
def source_note(text: str) -> SourceNote: ...
def footnote(text: str) -> Footnote: ...
def labels() -> Labels: ...
def callout() -> Callout: ...
def panel_letter(text: str) -> PanelLetter: ...
def inset() -> Inset: ...
def number_format() -> NumberFormat: ...
def layout_options() -> LayoutOptions: ...
def render_options() -> RenderOptions: ...
def stream_options() -> StreamOptions: ...
def annotation_edit(id: str) -> AnnotationEdit: ...
def link(origin: str) -> Link: ...

class PlotBuilder(_Owned):
    def data(self, value: Data) -> Self: ...
    def aes(self, value: Aes) -> Self: ...
    def layer(self, value: Layer | Labels | Callout) -> Self: ...
    def title(self, value: Title) -> Self: ...
    def subtitle(self, value: Subtitle) -> Self: ...
    def caption(self, value: Caption) -> Self: ...
    def source_note(self, value: SourceNote) -> Self: ...
    def footnote(self, value: Footnote) -> Self: ...
    def x_axis(self, value: Axis) -> Self: ...
    def y_axis(self, value: Axis) -> Self: ...
    def axis(self, value: Axis) -> Self: ...
    def scale(self, value: ColorScale) -> Self: ...
    def legend(self, value: Legend) -> Self: ...
    def facet(self, value: Facet) -> Self: ...
    def theme(self, value: Theme) -> Self: ...
    def panel_letter(self, value: PanelLetter) -> Self: ...
    def inset(self, value: Inset) -> Self: ...
    def transform(self, value: Transform) -> Self: ...
    def profile(self, value: str) -> Self: ...
    def compile_limits(self, value: Options) -> Self: ...
    def data_limits(self, value: Options) -> Self: ...
    def build(self) -> Plot: ...
class PlotEdit(_Owned):
    def layer(self, name: str, value: Layer) -> Self: ...
    def annotation(self, value: Labels | Callout) -> Self: ...
    def remove_layer(self, name: str) -> Self: ...
    def remove_annotation(self, id: str) -> Self: ...
    def clear_facets(self) -> Self: ...
    def title(self, value: Title) -> Self: ...
    def subtitle(self, value: Subtitle) -> Self: ...
    def caption(self, value: Caption) -> Self: ...
    def source_note(self, value: SourceNote) -> Self: ...
    def footnote(self, value: Footnote) -> Self: ...
    def x_axis(self, value: Axis) -> Self: ...
    def y_axis(self, value: Axis) -> Self: ...
    def axis(self, value: Axis) -> Self: ...
    def scale(self, value: ColorScale) -> Self: ...
    def legend(self, value: Legend) -> Self: ...
    def facet(self, value: Facet) -> Self: ...
    def theme(self, value: Theme) -> Self: ...
    def panel_letter(self, value: PanelLetter) -> Self: ...
    def inset(self, value: Inset) -> Self: ...
    def transform(self, value: Transform) -> Self: ...
    def build(self) -> Plot: ...
def plot(data: Data) -> PlotBuilder: ...
class Plot(_Owned):
    def edit(self) -> PlotEdit: ...
    def chart(self) -> Chart: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(value: str) -> Plot: ...
class ExportOptions(_Owned):
    def dpi(self, value: int) -> Self: ...
    def page(self, width: float, height: float, unit: Literal["pt", "mm"]) -> Self: ...
    def precision(self, value: int) -> Self: ...
    def max_raster_pixels(self, value: int) -> Self: ...
    def max_output_bytes(self, value: int) -> Self: ...
    def background(self, value: Color) -> Self: ...
    def interaction(self, value: Options) -> Self: ...
    def basis(self, value: Literal["presented", "current", "Presented", "Current"]) -> Self: ...
    def view(self, value: Literal["visible", "full_domain", "VisibleView", "FullDomain"]) -> Self: ...
    def text(self, value: Literal["preserve", "outline", "Preserve", "Outline"]) -> Self: ...
    def layout(self, value: LayoutOptions) -> Self: ...
def export_options(width: float, height: float, unit: Literal["pt", "mm"] = ...) -> ExportOptions: ...
class FigureRequest(_Owned):
    def prepare(self) -> FigureSnapshot: ...
    def manifest(self) -> dict[str, object]: ...
class FigureSnapshot(_Owned):
    def scene(self) -> dict[str, object]: ...
    def manifest(self) -> dict[str, object]: ...
    def export(self, format: Format) -> bytes: ...
    def save(self, path: str | PathLike[str], format: Format) -> None: ...
class Output(_Owned):
    def __init__(self, font: bytes | bytearray | Iterable[int]) -> None: ...
    def primary_font(self) -> dict[str, object]: ...
    def register_font(self, font: bytes | bytearray | Iterable[int]) -> dict[str, object]: ...
    def request(self, source: Plot | Chart, options: ExportOptions) -> FigureRequest: ...
    def export(self, source: Plot | Chart, format: Format, options: ExportOptions) -> bytes: ...
    def save(self, source: Plot | Chart, path: str | PathLike[str], format: Format, options: ExportOptions) -> None: ...
class ExportJob(_Owned):
    def cancel(self) -> bool: ...
    def run(self) -> bytes: ...
class ExportQueue(_Owned):
    def __init__(self, *, max_jobs: int = ..., max_input_bytes: int = ..., max_rows: int = ...) -> None: ...
    def submit(self, request: FigureRequest, format: Format) -> ExportJob: ...
    def metrics(self) -> dict[str, object]: ...
class Transaction(_Owned): ...
class Updates(_Owned):
    def id(self, value: str) -> Updates: ...
    def append(self, target: Data | str, data: Data) -> Updates: ...
    def upsert(self, target: Data | str, data: Data) -> Updates: ...
    def replace(self, target: Data | str, data: Data) -> Updates: ...
    def remove(self, target: Data | str, keys: Iterable[int]) -> Updates: ...
    def retain_count(self, target: Data | str, count: int | None) -> Updates: ...
    def retain_event_time(self, target: Data | str, field: str, width: int, watermark: int, *, allowed_lateness: int = ..., late: Literal["Reject", "Drop"] = ...) -> Updates: ...
    def retention(self, target: Data | str, policy: str | Options) -> Updates: ...
    def watermark(self, target: Data | str, ticks: int) -> Updates: ...
    def reset_categories(self, target: Data | str, field: str) -> Updates: ...
    def build(self) -> Transaction: ...
class Editor(_Owned):
    def original(self) -> dict[str, object]: ...
    def preview(self, dx: float, dy: float) -> dict[str, object]: ...
    def nudge(self, *, horizontal: bool = ..., forward: bool = ..., steps: int = ...) -> dict[str, object]: ...
class Chart(_Owned):
    def __init__(self, plot: Plot) -> None: ...
    def external_view(self) -> Chart: ...
    def accept_from(self, source: Chart) -> dict[str, object]: ...
    def revisions(self) -> Revisions: ...
    def semantics(self) -> dict[str, object]: ...
    def state(self) -> dict[str, object]: ...
    def apply_plot(self, plot: Plot, expected: int) -> bool: ...
    def restore_state(self, state: Options, expected: int) -> None: ...
    def act(self, action: str | Options, *, origin: str | Options = ..., expected: int | None = ...) -> DispatchOutcome: ...
    def query(self, operation: Options, *, gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def layer_visible(self, layer: str, visible: bool, *, expected: int | None = ...) -> DispatchOutcome: ...
    def legend_visible(self, visible: bool, *, expected: int | None = ...) -> DispatchOutcome: ...
    def follow(self, mode: Literal["FollowLatest", "InspectHistory", "FreezePresentation"] = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def freeze(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def resume(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def reset(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def undo(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def redo(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def clear_inspection(self, *, expected: int | None = ...) -> DispatchOutcome: ...
    def select(self, targets: Sequence[Options], change: Literal["Replace", "Add", "Remove", "Toggle"] = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def hover(self, targets: Sequence[Options], *, expected: int | None = ...) -> DispatchOutcome: ...
    def focus(self, target: Options | None = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def pin(self, target: Options | None = ..., *, expected: int | None = ...) -> DispatchOutcome: ...
    def set_annotation(self, annotation: Options, *, expected: int | None = ...) -> DispatchOutcome: ...
    def remove_annotation(self, id: str, *, expected: int | None = ...) -> DispatchOutcome: ...
    def set_windows(self, windows: Options, *, expected: int | None = ...) -> DispatchOutcome: ...
    def editor(self, options: AnnotationEdit) -> Editor: ...
    def describe(self, offset: int = ..., limit: int = ..., *, gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def inspect(self, x: float, y: float, *, radius: float = ..., max_grouped: int = ..., mode: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> dict[str, object]: ...
    def select_region(self, region: Options, *, limit: int = ..., gesture: bool = ..., stamp: Options | None = ...) -> SelectionResult: ...
    def select_series(self, layer: str, *, panel: Panel | None = ..., limit: int = ..., gesture: bool = ..., stamp: Options | None = ...) -> SelectionResult: ...
    def navigate(self, action: str | Options, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def zoom(self, x: float, y: float, factor: float, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def pan(self, dx: float, dy: float, *, axes: Sequence[str] = ..., panel: Panel | None = ..., boundary: str = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def range(self, axis: str, window: str | Options, *, panel: Panel | None = ..., gesture: bool = ..., stamp: Options | None = ...) -> WindowResult: ...
    def present(self, output: Output, options: ExportOptions) -> FigureSnapshot: ...
    def request(self, output: Output, options: ExportOptions) -> FigureRequest: ...
    def stream(self, options: StreamOptions) -> Self: ...
    def transaction(self) -> Updates: ...
    def commit(self, transaction: Transaction) -> dict[str, object]: ...
    def enqueue(self, transaction: Transaction) -> dict[str, object] | str: ...
    def stream_status(self) -> dict[str, object]: ...
    def pinned(self) -> dict[str, object] | None: ...
    def queue_status(self) -> dict[str, object]: ...
    def commit_next(self) -> dict[str, object] | None: ...
    def reset_epoch(self) -> dict[str, object]: ...
    def dense(self, frame: FigureSnapshot, options: RenderOptions) -> dict[str, object]: ...
    def link_capture(self, component: Link, event: Options) -> dict[str, object] | None: ...
    def link_resolve(self, component: Link, message: Options) -> dict[str, object]: ...
# Explicit compatibility entry point; the primary API above does not require envelopes.
class LegacyChart:
    def __init__(self, definition: str, data: str, profile: str, font: list[int] | bytes) -> None: ...
    def semantics(self) -> str: ...
    def scene(self) -> str: ...
    def export(self, format: str) -> list[int]: ...
    def transaction(self, input: str) -> str: ...
    def dense_preview(self, request: str) -> str: ...
    def stream(self, input: str) -> str: ...
    def export_control(self, input: str) -> str: ...
    def export_job(self, job: str) -> list[int]: ...
    def action(self, input: str) -> str: ...
    def definition(self) -> str: ...
    def present(self) -> str: ...
    def query(self, input: str) -> str: ...
    def dispatch(self, input: str) -> str: ...
    def state(self) -> str: ...
    def restore_state(self, input: str, expected: str) -> None: ...
    def dispose(self) -> None: ...
