from collections.abc import Mapping, Sequence, Iterable
from typing import Generic, Literal, Never, Self, TypeAlias, TypeVar, TypedDict, NotRequired, overload
from . import ColorValue, _Owned, ShapeRegistry

NumericArrayKind: TypeAlias = Literal["Float32Array","Float64Array","Int8Array","Uint8Array","Uint8ClampedArray","Int16Array","Uint16Array","Int32Array","Uint32Array"]
class MissingValue: ...
MISSING: MissingValue
class InterpolationDate:
    def __init__(self, milliseconds: float) -> None: ...
    @property
    def milliseconds(self) -> float: ...
    @property
    def valid(self) -> bool: ...
class NumericArray:
    def __init__(self, kind: NumericArrayKind, values: Iterable[float]) -> None: ...
    @property
    def kind(self) -> NumericArrayKind: ...
    @property
    def values(self) -> tuple[float, ...]: ...
def date_value(milliseconds: float) -> InterpolationDate: ...
def numeric_array(kind: NumericArrayKind, values: Iterable[float]) -> NumericArray: ...
InterpolationInput: TypeAlias = None | bool | float | str | MissingValue | InterpolationDate | NumericArray | ColorValue | Sequence["InterpolationInput"] | Mapping[str,"InterpolationInput"]
InterpolationResult: TypeAlias = None | bool | float | str | MissingValue | InterpolationDate | NumericArray | ColorValue | list["InterpolationResult"] | dict[str,"InterpolationResult"]
NumericInterpolationInput: TypeAlias = float | bool | str | None | MissingValue | InterpolationDate
ColorInterpolationInput: TypeAlias = str | ColorValue | None | MissingValue
ArrayInterpolationInput: TypeAlias = Sequence[InterpolationInput] | NumericArray | None | MissingValue
_T = TypeVar("_T", covariant=True)
_V = TypeVar("_V", bound=InterpolationInput)
class Interpolator(_Owned, Generic[_T]):
    def __init__(self, _inner: Never) -> None: ...
    @classmethod
    def from_json(cls, value: str, registry: ShapeRegistry | None = ...) -> Interpolator[InterpolationResult]: ...
    def to_json(self) -> str: ...
    def copy(self) -> Interpolator[_T]: ...
    def sample(self, t: float) -> _T: ...
    def __call__(self, t: float) -> _T: ...
    def sample_value(self, t: float) -> dict[str, object]: ...
    def sample_color(self, t: float) -> ColorValue: ...
    def sample_transform(self, t: float) -> list[float]: ...
    def quantize(self, count: int) -> list[_T]: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def scheduling_duration(self) -> float | None: ...
class _FactoryBase(Generic[_T]): ...
class _GenericFactory(_FactoryBase[InterpolationResult]):
    def __call__(self, a: InterpolationInput, b: InterpolationInput) -> Interpolator[InterpolationResult]: ...
class _NumericFactory(_FactoryBase[float]):
    def __call__(self, a: NumericInterpolationInput, b: NumericInterpolationInput) -> Interpolator[float]: ...
class _TextFactory(_FactoryBase[str]):
    def __call__(self, a: float | bool | str | None | MissingValue | ColorValue, b: float | bool | str | None | MissingValue | ColorValue) -> Interpolator[str]: ...
class _DateFactory(_FactoryBase[InterpolationDate]):
    def __call__(self, a: NumericInterpolationInput, b: NumericInterpolationInput) -> Interpolator[InterpolationDate]: ...
class _ArrayFactory(_FactoryBase[InterpolationResult]):
    @overload
    def __call__(self, a: ArrayInterpolationInput, b: NumericArray) -> Interpolator[NumericArray]: ...
    @overload
    def __call__(self, a: ArrayInterpolationInput, b: Sequence[InterpolationInput] | None | MissingValue) -> Interpolator[list[InterpolationResult]]: ...
class _ObjectFactory(_FactoryBase[dict[str,InterpolationResult]]):
    def __call__(self, a: InterpolationInput, b: InterpolationInput) -> Interpolator[dict[str,InterpolationResult]]: ...
class _ColorFactory(_FactoryBase[str]):
    def __call__(self, a: ColorInterpolationInput, b: ColorInterpolationInput) -> Interpolator[str]: ...
class _GammaFactory(_ColorFactory):
    def gamma(self, value: float) -> Self: ...
class _BasisFactory:
    def __call__(self, values: Sequence[float] | NumericArray) -> Interpolator[float]: ...
class _RgbBasisFactory:
    def __call__(self, values: Sequence[ColorInterpolationInput]) -> Interpolator[str]: ...
class _DiscreteFactory:
    def __call__(self, values: Sequence[_V]) -> Interpolator[_V]: ...
class _CssTransformFactory:
    @overload
    def __call__(self, a: str, b: str) -> Interpolator[str]: ...
    @overload
    def __call__(self, a: Sequence[float] | NumericArray, b: Sequence[float] | NumericArray) -> Interpolator[str]: ...
class _SvgTransformFactory:
    @overload
    def __call__(self, a: str | None | MissingValue, b: str | None | MissingValue) -> Interpolator[str]: ...
    @overload
    def __call__(self, a: Sequence[float] | NumericArray, b: Sequence[float] | NumericArray) -> Interpolator[str]: ...
class _ZoomFactory:
    def __call__(self, a: Sequence[float] | NumericArray, b: Sequence[float] | NumericArray) -> Interpolator[list[float]]: ...
    def rho(self, value: float) -> Self: ...
interpolate: _GenericFactory
interpolate_number: _NumericFactory
interpolate_round: _NumericFactory
interpolate_hue: _NumericFactory
interpolate_string: _TextFactory
interpolate_date: _DateFactory
interpolate_array: _ArrayFactory
interpolate_number_array: _ArrayFactory
interpolate_object: _ObjectFactory
interpolate_rgb: _GammaFactory
interpolate_hsl: _ColorFactory
interpolate_hsl_long: _ColorFactory
interpolate_lab: _ColorFactory
interpolate_hcl: _ColorFactory
interpolate_hcl_long: _ColorFactory
interpolate_cubehelix: _GammaFactory
interpolate_cubehelix_long: _GammaFactory
interpolate_basis: _BasisFactory
interpolate_basis_closed: _BasisFactory
interpolate_rgb_basis: _RgbBasisFactory
interpolate_rgb_basis_closed: _RgbBasisFactory
interpolate_discrete: _DiscreteFactory
interpolate_transform_css: _CssTransformFactory
interpolate_transform_svg: _SvgTransformFactory
interpolate_zoom: _ZoomFactory
@overload
def piecewise(values: Sequence[InterpolationInput]) -> Interpolator[InterpolationResult]: ...
@overload
def piecewise(factory: _FactoryBase[_T], values: Sequence[InterpolationInput]) -> Interpolator[_T]: ...
def quantize(interpolator: Interpolator[_T], count: int) -> list[_T]: ...

ChromaticSchemeId: TypeAlias = Literal["Accent","Blues","BrBG","BuGn","BuPu","Category10","Dark2","GnBu","Greens","Greys","Observable10","OrRd","Oranges","PRGn","Paired","Pastel1","Pastel2","PiYG","PuBu","PuBuGn","PuOr","PuRd","Purples","RdBu","RdGy","RdPu","RdYlBu","RdYlGn","Reds","Set1","Set2","Set3","Spectral","Tableau10","YlGn","YlGnBu","YlOrBr","YlOrRd"]
ChromaticInterpolatorId: TypeAlias = Literal["Blues","BrBG","BuGn","BuPu","Cividis","Cool","CubehelixDefault","GnBu","Greens","Greys","Inferno","Magma","OrRd","Oranges","PRGn","PiYG","Plasma","PuBu","PuBuGn","PuOr","PuRd","Purples","Rainbow","RdBu","RdGy","RdPu","RdYlBu","RdYlGn","Reds","Sinebow","Spectral","Turbo","Viridis","Warm","YlGn","YlGnBu","YlOrBr","YlOrRd"]
class SchemeSpec(TypedDict):
    id: ChromaticSchemeId
    version: NotRequired[Literal[1]]
    size: NotRequired[int | None]
    reverse: NotRequired[bool]
class SchemeInfo(TypedDict):
    id: ChromaticSchemeId
    family: Literal["Categorical", "Sequential", "Diverging"]
    sizes: list[int]
class ChromaticCatalog(TypedDict):
    version: Literal[1]
    schemes: list[SchemeInfo]
    interpolators: list[ChromaticInterpolatorId]
def chromatic_catalog() -> ChromaticCatalog: ...
def chromatic_scheme(name: ChromaticSchemeId, size: int | None = None, reverse: bool = False) -> list[ColorValue]: ...
def chromatic(name: ChromaticInterpolatorId, reverse: bool = False) -> Interpolator[ColorValue]: ...

class RegisteredInterpolationFactory(_FactoryBase[InterpolationResult]):
    def __init__(self, registry: ShapeRegistry, operation_id: str, version: int | str, parameters: Mapping[str, object] | None = ...) -> None: ...
    def __call__(self, a: InterpolationInput, b: InterpolationInput) -> Interpolator[InterpolationResult]: ...
    def copy(self) -> Self: ...
    def dispose(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...
def registered_interpolation(registry: ShapeRegistry, operation_id: str, version: int | str, parameters: Mapping[str, object] | None = ...) -> RegisteredInterpolationFactory: ...
