from collections.abc import Iterable, Mapping, Sequence
from typing import Literal, Self, TypeAlias, TypedDict, overload
from . import _Owned, ShapeRegistry
from ._interpolation import InterpolationInput, InterpolationResult, Interpolator, MissingValue, _FactoryBase

ScaleFamily: TypeAlias = Literal["linear", "log", "pow", "sqrt", "symlog", "identity", "radial", "ordinal", "band", "point", "quantile", "quantize", "threshold", "sequential", "sequential_log", "sequential_pow", "sequential_sqrt", "sequential_symlog", "sequential_quantile", "diverging", "diverging_log", "diverging_pow", "diverging_sqrt", "diverging_symlog", "utc", "local"]
ScaleTimeUnit: TypeAlias = Literal["Seconds", "Milliseconds", "Microseconds", "Nanoseconds"]
class ScaleKey:
    @overload
    def __init__(self, kind: Literal["Integer", "Unsigned", "Timestamp"], value: int) -> None: ...
    @overload
    def __init__(self, kind: Literal["Number"], value: float) -> None: ...
    @overload
    def __init__(self, kind: Literal["Text"], value: str) -> None: ...
    @overload
    def __init__(self, kind: Literal["Boolean"], value: bool) -> None: ...
    @overload
    def __init__(self, kind: Literal["Null"], value: None = ...) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> object: ...
ScaleArgument: TypeAlias = None | bool | int | float | str | ScaleKey | MissingValue
class WeekInterval(TypedDict):
    Week: Literal["Sunday", "Monday"]
class CalendarInterval(TypedDict):
    unit: Literal["SourceTick", "Millisecond", "Second", "Minute", "Hour", "Day", "UnixDay", "Month", "Year"] | WeekInterval
    step: int
class NumericLocale(TypedDict, total=False):
    decimal: str
    thousands: str | None
    grouping: Sequence[int] | None
    currency: tuple[str, str]
    numerals: Sequence[str] | None
    percent: str
    minus: str
    nan: str
class TimeLocale(TypedDict, total=False):
    dateTime: str
    date: str
    time: str
    periods: tuple[str, str]
    days: Sequence[str]
    shortDays: Sequence[str]
    months: Sequence[str]
    shortMonths: Sequence[str]
class TimeZoneTransition(TypedDict):
    at_millis: str
    offset_seconds: int
class TimeCoverage(TypedDict):
    start: str
    end: str
class TimeZoneRules(TypedDict):
    version: Literal[1]
    zone: str
    revision: str
    tzdata: str
    coverage: TimeCoverage
    initial_offset_seconds: int
    transitions: Sequence[TimeZoneTransition]
class LocalCalendar(TypedDict):
    Local: TimeZoneRules
CalendarZone: TypeAlias = Literal["Utc"] | LocalCalendar
class InterpolationFactorySpec(TypedDict, total=False):
    kind: Literal["Value", "Number", "Round", "String", "Date", "Array", "NumberArray", "Object", "Hue", "Rgb", "Hsl", "HslLong", "Lab", "Hcl", "HclLong", "Cubehelix", "CubehelixLong"]
    gamma: float
class InverseExtent(TypedDict):
    found: bool
    lower: ScaleArgument
    upper: ScaleArgument
class StandaloneScale(_Owned):
    def __init__(self, family: ScaleFamily = ..., *, registry: ShapeRegistry | None = ..., domain: Iterable[ScaleArgument] = ..., range: Iterable[InterpolationInput] = ..., clamp: bool = ..., round: bool = ..., unknown: InterpolationInput = ..., implicit: bool = ..., base: float = ..., exponent: float = ..., constant: float = ..., padding: float = ..., padding_inner: float = ..., padding_outer: float = ..., align: float = ..., factory: _FactoryBase[object] | InterpolationFactorySpec = ..., interpolator: Interpolator[object] = ..., unit: ScaleTimeUnit = ..., zone: CalendarZone = ...) -> None: ...
    @classmethod
    def from_json(cls, text: str, registry: ShapeRegistry | None = ...) -> StandaloneScale: ...
    @classmethod
    def from_spec(cls, spec: Mapping[str, object], registry: ShapeRegistry | None = ...) -> StandaloneScale: ...
    def to_json(self) -> str: ...
    def spec(self) -> dict[str, object]: ...
    def mapped(self, training: Literal["Authored", "Eligible"] = ...) -> dict[str, object]: ...
    def copy(self) -> Self: ...
    def configure(self, *, domain: Iterable[ScaleArgument] = ..., range: Iterable[InterpolationInput] = ..., clamp: bool = ..., round: bool = ..., unknown: InterpolationInput = ..., implicit: bool = ..., base: float = ..., exponent: float = ..., constant: float = ..., padding: float = ..., padding_inner: float = ..., padding_outer: float = ..., align: float = ..., factory: _FactoryBase[object] | InterpolationFactorySpec = ..., interpolator: Interpolator[object] = ..., unit: ScaleTimeUnit = ..., zone: CalendarZone = ...) -> Self: ...
    def reconfigure(self, spec: Mapping[str, object]) -> StandaloneScale: ...
    def domain(self) -> tuple[ScaleArgument, ...]: ...
    def range(self) -> tuple[InterpolationResult, ...]: ...
    def map(self, value: ScaleArgument = ...) -> InterpolationResult: ...
    def map_value(self, value: ScaleArgument = ...) -> dict[str, object]: ...
    def invert(self, value: float) -> InterpolationResult: ...
    def invert_extent(self, value: InterpolationInput) -> InverseExtent: ...
    def ticks(self, count: float = ..., *, interval: CalendarInterval | None = ..., budget: int = ...) -> tuple[ScaleArgument, ...]: ...
    def format(self, value: ScaleArgument, *, count: float = ..., specifier: str | None = ..., pattern: str | None = ..., locale: NumericLocale | TimeLocale | None = ...) -> str: ...
    def nice(self, count: float = ..., *, interval: CalendarInterval | None = ...) -> Self: ...
    def train(self, values: Iterable[ScaleArgument]) -> Self: ...
    def thresholds(self) -> tuple[float | None, ...]: ...
    def quantiles(self, count: float) -> tuple[float | None, ...]: ...
    def step(self) -> float: ...
    def bandwidth(self) -> float: ...
    def extent(self, value: ScaleArgument) -> tuple[float, float] | None: ...
    def center(self, value: ScaleArgument) -> float | None: ...
    def floor(self, value: int, interval: CalendarInterval) -> int: ...
    def ceil(self, value: int, interval: CalendarInterval) -> int: ...
    def round_time(self, value: int, interval: CalendarInterval) -> int: ...
    def offset(self, value: int, interval: CalendarInterval, steps: float = ...) -> int: ...
