from collections.abc import Sequence
from . import Plot, PlotBuilder, Stat, Layer, MappingValue

def with_extensions(builder: PlotBuilder) -> PlotBuilder: ...
def density_histogram(field: MappingValue, edges: Sequence[float]) -> Stat: ...
def chamfered_bars(native: bool = ...) -> Layer: ...

def load_plot(value: str) -> Plot: ...
