'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const reject=(fn,code)=>assert.throws(fn,e=>e.code===code),registry=c.ExtensionRegistry.example();assert.equal(c.ExtensionRegistry,c.ShapeRegistry);
const base=9007199254741001n,d=c.Data.columns({x:new Float64Array([-10,-2,2,10]),y:new Float64Array([0,1,2,3])},{keys:[base,base+1n,base+2n,base+3n],name:'source'});
function builder(name='example.fold',limit=10,version=1){return c.plot(d).withRegistry(registry).aes(c.aes().x('x').y('y')).layer(c.points()).xAxis(c.xAxis().coordinateScale(c.scaleRegistered(name,version,{limit})).range(100,500).visible(false)).yAxis(c.yAxis().range(300,100).visible(false));}
function guide(name,side,dx,dy){return c.axisGuide(name,'x').side(side).translate(dx,dy).ticks([0,2,10].map(v=>[v,`${name} ${v}`]));}
const p=builder().guide(guide('top','Top',0,0)).guide(guide('lower','Bottom',10,30)).title(c.title('Folded values / one scale / two guides')).build(),wire=p.toJson();assert.equal(JSON.parse(wire).version,10);reject(()=>c.Plot.fromJson(wire),'CHART_UNSUPPORTED_CAPABILITY');const loaded=c.Plot.fromJson(wire,registry);assert.equal(loaded.toJson(),wire);reject(()=>builder('example.fold',10,2).build(),'CHART_UNSUPPORTED_CAPABILITY');reject(()=>builder('example.fold',-1).build(),'CHART_NUMERICAL_DOMAIN');
const native=builder('example.native_fold').build();reject(()=>native.toJson(),'CHART_UNSUPPORTED_CAPABILITY');const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.exportOptions(600,400).dpi(72).basis('current');reject(()=>output.request(native,options).prepare(),'CHART_UNSUPPORTED_CAPABILITY');native.free();
const request=output.request(p,options),copy=registry.copy();registry.free();p.free();let frame=request.prepare();const scene=frame.scene(),points=scene.items.filter(i=>i.primitive.Point).map(i=>i.primitive.Point.center);assert.deepEqual(points.map(p=>p.x),[500,180,180,500]);
for(const [name,offset] of [['top',0],['lower',10]])scene.items.forEach((item,i)=>{const text=item.primitive.Text;if(text&&text.text.startsWith(name+' ')){const v=Number(text.text.split(' ')[1]);assert.equal(scene.items[i-1].primitive.Rule.from.x,100+40*v+offset);}});
assert.deepEqual(scene.targets.flat().map(t=>BigInt(t.Source.key)).sort((a,b)=>a<b?-1:1),[base,base+1n,base+2n,base+3n]);fs.writeFileSync(path.join(out,'provider.plot.json'),wire);fs.writeFileSync(path.join(out,'provider.scene.json'),JSON.stringify(scene));for(const format of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`provider.${format}`),frame.export(format));const second=output.request(loaded,options).prepare();assert.deepEqual(second.export('png'),frame.export('png'));second.free();loaded.free();frame.free();frame=request.prepare();assert.deepEqual(Buffer.from(frame.export('png')),fs.readFileSync(path.join(out,'provider.png')));frame.free();copy.free();request.free();output.free();d.free();console.log('PASS WASM provider: exact noninjective mark and guide positions, v10 registration, invalid versions/parameters, native-only rejection, copied registry and retained request after disposal, SVG/PDF/PNG.');
