'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs'));
const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.exportOptions(600,400).dpi(72).basis('current');
function guide(name,source,side,dx,dy){return c.axisGuide(name,source).side(side).translate(dx,dy).ticks([[2,name+' two'],[8,name+' eight']]);}
function positions(frame){const items=frame.scene().items,result={};items.forEach((item,i)=>{const text=item.primitive.Text;if(text&&['top','lower','far'].includes(text.text.split(' ')[0])){const rule=items[i-1].primitive.Rule;assert.equal(rule.from.x,rule.to.x);result[text.text]=rule.from;}});return result;}
function check(values,top=[180,420],lower=[190,430],far=[200,440]){for(const [name,expected]of[['top',top],['lower',lower],['far',far]])for(const [i,label]of['two','eight'].entries())assert.ok(Math.abs(values[name+' '+label].x-expected[i])<1e-10);assert.ok(Math.abs(values['far two'].y-values['lower two'].y-30)<1e-10);}
const base=9007199254741001n,d=c.Data.columns({x:new Float64Array([0,5,10]),y:new Float64Array([1,2,3])},{keys:[base,base+1n,base+2n],name:'source'}),p=c.plot(d).aes(c.aes().x('x').y('y')).layer(c.points()).xAxis(c.xAxis().scale(c.scaleLinear().domain(0,10)).range(100,500).visible(false)).yAxis(c.yAxis().range(300,100).visible(false)).axis(c.xAxis().name('other').side('Top').scale(c.scaleLinear().domain(0,20)).range(100,500).visible(false)).guide(guide('top','x','Top',0,0)).guide(guide('lower','x','Bottom',10,30)).guide(guide('far','x','Bottom',20,60)).build();
const wire=p.toJson(),payload=JSON.parse(wire);assert.equal(payload.version,8);assert.equal(payload.definition.axes.length,3);assert.equal(payload.definition.guides.length,3);assert.equal(new Set(payload.definition.guides.map(g=>g.scale)).size,1);
const roundtrip=c.Plot.fromJson(wire);assert.equal(roundtrip.toJson(),wire);const request=output.request(p,options);let frame=request.prepare();check(positions(frame));assert.deepEqual(frame.scene().targets.flat().map(t=>BigInt(t.Source.key)).sort((a,b)=>a<b?-1:1),[base,base+1n,base+2n]);const png=frame.export('png');frame.free();frame=output.request(roundtrip,options).prepare();assert.deepEqual(frame.export('png'),png);frame.free();roundtrip.free();
const edited=p.edit().guide(guide('top','other','Top',0,0)).build(),changed=JSON.parse(edited.toJson());assert.deepEqual(changed.guides,payload.guides);assert.deepEqual(changed.axes,payload.axes);assert.equal(changed.definition.guides[0].scale,payload.axes.other);frame=output.request(edited,options).prepare();check(positions(frame),[140,260]);frame.free();edited.free();
const chart=p.chart();chart.present(output,options).free();chart.setWindows(chart.range('x',{Numeric:[0,20]}).windows);frame=chart.present(output,options);check(positions(frame),[140,260],[150,270],[160,280]);frame.free();frame=request.prepare();assert.deepEqual(frame.export('png'),png);frame.free();
assert.throws(()=>c.plot(d).layer(c.points()).guide(guide('bad','missing','Top',0,0)).build(),e=>e.code==='CHART_MISSING_RESOURCE');
chart.free();p.free();d.free();request.free();output.free();console.log('PASS WASM independent guides: shared positions, two translated guides on one side, named scale navigation, stable guide identities during scale replacement, v8 round trips, exact source IDs and retained publication.');
