'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const joint=process.argv.includes('--joint'),cases=JSON.parse(fs.readFileSync(path.join(root,`fixtures/parity/ggplot2/positional-pipeline-binned-${joint?'compositions':'vectors'}.json`))).cases;
const configurations=t=>[['numeric',1]],mapping=()=> 'v';
function dataFor(t){const values=t.inputs.map(v=>v==='Infinity'?Infinity:v==='-Infinity'?-Infinity:v),i=t.kind==='mean'?t.groups:values.map((_,i)=>i+1);return c.Data.columns({v:c.column(values,{kind:'float64'}).nullable(true),i:c.column(i.map(BigInt),{kind:'int64'})});}
function layer(t,m){const p=c.points().name('marks');return t.kind==='mean'?p.stat(c.summary().x(mapping(t,m)).group('i')).after_stat(c.stat_aes().x(1).y('Mean')):p;}
function build(t,d,m){const transform={reverse:'Reverse',log10:{Log:{base:10}}}[t.family]??null;let scale=c.scale_binned({bins:{limits:t.limit_mode==='explicit'?[1,10]:null,breaks:t.cuts==='fixed'?{Explicit:[1,4,10]}:{Nice:3},right:true,oob:"Squish"},transform});if(joint&&t.cuts!=='nice')scale=c.scale_binned({bins:{breaks:{Nice:3},oob:'Squish',right:true},transform,breaks_function:{operation:{id:'example.breaks_n',version:'1'},parameters:t.cuts==='mixed'?'mixed_unnamed':'domain'}});let axis=(t.axis==='x'?c.x_axis():c.y_axis()).scale(scale).guide_geometry({labels:'Preserve'}).oob_function({operation:{id:'example.scale_vector',version:'1'},parameters:{mode:t.mode==='default'?'default':'oob_'+t.mode}});if(joint)axis=axis.limits_function({operation:{id:'example.numeric_limits',version:'1'},parameters:{mode:t.control,...(t.control==='fixed'?{bounds:[1,10]}:{})}});const draft=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').aes(c.aes().x(t.axis==='x'?mapping(t,m):'i').y(t.axis==='x'?'i':mapping(t,m))).layer(layer(t,m));return (t.axis==='x'?draft.x_axis(axis):draft.y_axis(axis)).build();}
const scalar=v=>v&&typeof v==='object'?v.number:v;
function compare(a,b){if(typeof a==='number'&&typeof b==='number')assert.ok(Math.abs(a-b)<5e-14,`${a} != ${b}`);else if(Array.isArray(a)&&Array.isArray(b)){assert.equal(a.length,b.length);a.forEach((v,i)=>compare(v,b[i]));}else assert.deepEqual(a,b);}
function check(t,chart,frame,m){const semantics=chart.semantics(),state=semantics.layers[0],positions=state.point_positions,dim=t.axis==='x'?0:1;compare(positions.map(p=>scalar(p[dim])),t.result.mapped.filter(v=>v!==null));compare(positions.map(p=>scalar(p[1-dim])),t.kind==='mean'?positions.map(()=>1):t.result.mapped.flatMap((v,i)=>v===null?[]:[i+1]));const ticks=frame.guides().guides.find(g=>g.spec.side===(dim===0?'Bottom':'Left')).ticks,expected=t.result.breaks.flatMap((v,i)=>typeof v==='number'?[[v,t.result.labels[i]]]:[]);compare(ticks.map(t=>t.label),expected.map(([,label])=>label??''));function tickNumber(v){const x=v.Number;return t.family==='reverse'?-x:t.family==='log10'?Math.log10(x):x;}compare(ticks.map(t=>tickNumber(t.value)),expected.map(([v])=>v));return {positions,ticks,domains:state.domains};}
function sample(t){return (joint?(t.cuts==='domain'&&t.control==='fixed'):t.cuts==='nice')&&t.population==='ordinary'&&['point_x','mean'].includes(t.kind)&&t.limit_mode==='automatic'&&['reverse','index'].includes(t.mode);}
for(const [index,t] of cases.entries())for(const [unit,m] of configurations(t)){
 const owned=[];
 try{
  const d=dataFor(t,unit,m);owned.push(d);const p=build(t,d,m);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,40);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
  for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layer(t,m)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!t.result.error,JSON.stringify(t));records.push({index,unit,state,...check(t,chart,frame,m)});if(state==='original'&&sample(t,unit))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.family}-${t.kind}-${t.limit_mode}-${t.mode}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${index}/${unit}: ${error.stack}`);assert.ok(['CHART_SCHEMA_CONFLICT','CHART_NUMERICAL_DOMAIN'].includes(error.code));records.push({index,unit,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,joint?2680:1152);
function capture(t,chart,m,owned){try{const request=output.request(chart,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!t.result.error);return check(t,chart,frame,m);}catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${JSON.stringify(t)}: ${error.stack}`);return {error:error.code};}}
for(const family of ['identity','reverse','log10'])for(const kind of ['point_x','mean']){
 const selected=Object.fromEntries(cases.filter(t=>t.family===family&&t.kind===kind&&(joint?t.control==='fixed':t.limit_mode==='explicit')&&t.mode==='index'&&t.cuts==='nice').map(t=>[t.population,t]));
 for(const [unit,m] of configurations(selected.ordinary)){
  const owned=[];
  try{
   const original=dataFor(selected.ordinary,unit,m);owned.push(original);const p=build(selected.ordinary,original,m);owned.push(p);const chart=p.chart();owned.push(chart);const wire=p.to_json(),request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene();
   for(const population of ['missing','empty']){const t=selected[population],replacement=dataFor(t,unit,m);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const actual=capture(t,chart,m,owned);let expected;try{const fresh=build(t,replacement,m);owned.push(fresh);const batch=fresh.chart();owned.push(batch);expected=capture(t,batch,m,owned);}catch(error){assert.ok(error instanceof c.ChartError&&t.result.error);expected={error:error.code};}assert.deepEqual(actual,expected);assert.equal(p.to_json(),wire);assert.deepEqual(held.scene(),scene);records.push({family,kind,unit,replacement:population,...actual});}
  }finally{for(const obj of owned.reverse())obj.dispose();}
 }
}
assert.equal(records.length,joint?2692:1164);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));output.dispose();options.dispose();registry.dispose();console.log('PASS',records.length,'binned positional vector host states');
