'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,640).dpi(96).basis('current');
let cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-temporal-functions.json'))).cases.concat(JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-duration-functions.json'))).cases,JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-temporal-fractional-statistics.json'))).cases);
const automatic=process.argv[4]==='automatic';if(automatic)cases=cases.filter(t=>t.kind==='datetime');
const calendar=process.argv[4]==='calendar';if(calendar)cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-calendar-functions.json'))).cases;
function origin(t){return (t.epoch??1704067200)*1000;}
function calendarScale(t){const zone=t.zone==='UTC'?'Utc':{Local:{version:1,zone:t.zone,revision:'0',tzdata:'explicit-2024-US-transitions',coverage:{start:'1710000000000',end:'1740000000000'},initial_offset_seconds:-18000,transitions:[{at_millis:'1710054000000',offset_seconds:-14400},{at_millis:'1730613600000',offset_seconds:-18000}]}};return c.scale_calendar({domain:[String(origin(t)),String(origin(t)+86400000)],unit:'Milliseconds',zone,range:[{kind:'Number',value:0},{kind:'Number',value:1}],factory:{kind:'Value'},clamp:false,unknown:{kind:'Missing'}});}
function rejected(t){return Boolean(t.result.error);}
function mapping(t){return t.kind==='duration'?'t':{field:'t',origin:String(origin(t))};}
function dataFor(t){const factor=t.kind==='date'?86400000:1000;const values=(t.kind==='duration'?c.column(t.inputs.map(v=>v??0),{kind:'float64'}):c.timestamps(t.inputs.map(v=>v===null?1704067200000:Math.round(v*factor)),'ms','UTC')).validity(t.inputs.map(v=>v!==null));return c.Data.columns({t:values},{keys:t.inputs.map((_,i)=>100+i)});}
function layerFor(t){const layer=c.points().name('marks');return t.context==='summary'?layer.stat(c.summary().x(mapping(t))).after_stat(c.stat_aes().x(1).y('Mean')):layer;}
function build(t,d){const summary=t.context==='summary';let axis=(summary?c.y_axis():c.x_axis());if(calendar)axis=axis.scale(calendarScale(t));else if(!automatic)axis=axis.scale(t.kind==='duration'?c.scale_duration():t.kind==='date'?c.scale_date():c.scale_utc());axis=axis.range(100,540).guide_geometry({labels:'Preserve'}).oob(t.oob[0].toUpperCase()+t.oob.slice(1)).limitsFunction({operation:{id:'example.numeric_limits',version:'1'},parameters:{mode:t.control}});const p=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').aes(c.aes().x(summary?1:mapping(t)).y(summary?mapping(t):1)).layer(layerFor(t));return(summary?p.y_axis(axis).x_axis(c.x_axis().visible(false)):p.x_axis(axis).y_axis(c.y_axis().visible(false))).build();}
function numeric(v){return v===null?NaN:Number(v);}
function equal(a,b){return a===b||Number.isNaN(a)&&Number.isNaN(b)||Math.abs(a-b)<=3e-12*Math.max(1,Math.abs(b));}
function check(t,chart,frame){const summary=t.context==='summary',dimension=summary?'y':'x';const points=frame.scene().items.filter(i=>i.layer!=null&&i.primitive.Point).map(i=>(i.primitive.Point.center[dimension]-100)/440),expected=t.result.point_positions.filter(v=>v!==null&&Number.isFinite(numeric(v))).map(numeric);assert.equal(points.length,expected.length,JSON.stringify({t,points,expected}));assert.ok(points.every((a,i)=>equal(a,expected[i])),JSON.stringify({t,points,expected}));const ticks=frame.guides().guides.find(g=>g.spec.side===(summary?'Left':'Bottom')).ticks,wanted=t.result.positions.flatMap((position,i)=>position!==null&&Number.isFinite(numeric(position))?[[t.result.labels[i],numeric(position)]]:[]);assert.equal(ticks.length,wanted.length,JSON.stringify({t,ticks,wanted}));for(const[label,position]of wanted)assert.ok(ticks.some(tick=>tick.label===label&&equal((tick.position-100)/440,position)),JSON.stringify({t,ticks,label,position}));const semantics=chart.semantics();return{points,ticks,domains:semantics.layers[0].domains,limits:semantics.positional_limits??{}};}
function sample(t){if(calendar)return t.context==='points'&&t.population==='spaced'&&t.control==='identity'&&t.oob==='censor';return t.oob==='censor'&&((t.population==='fractional'&&t.control==='identity')||(t.population==='all_missing'&&t.control==='missing_lower'&&t.context==='points'))||t.oob==='keep'&&t.population==='spaced'&&t.control==='single'&&t.context==='points'||t.context==='summary'&&['thirds','sevenths'].includes(t.population)&&t.control==='identity'&&t.oob==='censor';}
for(const[index,t]of cases.entries()){
 const owned=[];
 try{const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,29);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
 for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layerFor(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!rejected(t),JSON.stringify(t));records.push({index,state,...check(t,chart,frame)});if(state==='original'&&sample(t))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.kind}-${t.context}-${t.population}-${t.control}${calendar?'-'+t.zone.replace('/','-')+'-'+t.epoch:''}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&rejected(t),`${JSON.stringify(t)}: ${error.stack}`);assert.equal(error.code,'CHART_NUMERICAL_DOMAIN');records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,calendar?412:automatic?445:1292);
const groups=calendar?['UTC','America/New_York'].flatMap(zone=>[1710046800,1730606400].map(epoch=>['datetime',zone,epoch])):(automatic?['datetime']:['date','datetime','duration']).map(kind=>[kind,null,null]);
for(const[kind,zone,epoch]of groups)for(const context of ['points','summary']){
 const owned=[];
 try{const selected=Object.fromEntries(cases.filter(t=>t.kind===kind&&t.context===context&&t.control==='identity'&&t.oob==='censor'&&(!calendar||t.zone===zone&&t.epoch===epoch)).map(t=>[t.population,t]));const original=dataFor(selected.spaced);owned.push(original);const p=build(selected.spaced,original);owned.push(p);const chart=p.chart();owned.push(chart);const request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene(),wire=p.to_json();
  for(const population of (calendar?['constant','missing','spaced','constant']:['constant','missing','all_missing','empty','fractional','spaced'])){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied'in chart.commit(update));function capture(current){try{const state=current.semantics();return{domains:state.layers[0].domains,limits:state.positional_limits??{}};}catch(error){assert.ok(error instanceof c.ChartError&&rejected(t));return{error:error.code};}}const actual=capture(chart);let expected;try{const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);expected=capture(batch);}catch(error){assert.ok(error instanceof c.ChartError&&rejected(t));expected={error:error.code};}assert.deepEqual(actual,expected);assert.deepEqual(held.scene(),scene);assert.equal(p.to_json(),wire);records.push({kind,context,replacement:population,...(calendar?{zone,epoch}:{}),...actual});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,calendar?444:automatic?457:1328);fs.writeFileSync(path.join(out,'position-temporal-records.json'),JSON.stringify(records,null,2));options.dispose();output.dispose();registry.dispose();console.log('PASS WASM:',records.length,'temporal positional callback states.');
