'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const shared=process.argv.includes('--shared'),binned=process.argv.includes('--binned'),broadcast=process.argv.includes('--broadcast');
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const cases=(broadcast?[binned?'positional-pipeline-binned-broadcast-facets':'positional-pipeline-broadcast-facets']:binned?['positional-pipeline-binned-facets']:['positional-pipeline-facets','positional-pipeline-facet-arities']).flatMap(file=>JSON.parse(fs.readFileSync(path.join(root,`fixtures/parity/ggplot2/${file}.json`))).cases);
if(shared)cases.splice(0,cases.length,...cases.filter(t=>t.kind==='mean'));
function dataFor(t){return c.Data.columns({v:c.column(t.inputs.map(v=>v==='Infinity'?Infinity:v==='-Infinity'?-Infinity:v),{kind:'float64'}).nullable(true),i:c.column(t.inputs.map((_,i)=>BigInt(i+1)),{kind:'int64'}),g:c.column(t.groups.map(BigInt),{kind:'int64'}),f:c.column(t.facets,{kind:'string'})});}
function layer(t){let p=c.points().name('marks');if(broadcast)p=p.facet_target('Broadcast');if(shared)return p.from_transform('mean').after_stat(c.stat_aes().x(1).y('Mean'));return t.kind==='mean'?p.stat(c.summary().x('v').group('g')).after_stat(c.stat_aes().x(1).y('Mean')):p;}
function build(t,d){let scale={identity:c.scale_linear,reverse:c.scale_reverse,log10:()=>c.scale_log(10)}[t.transform]();if(binned)scale=c.scale_binned({bins:{breaks:{Nice:3},oob:'Squish',right:true},transform:{reverse:'Reverse',log10:{Log:{base:10}}}[t.transform]??null});const axis=c.y_axis().scale(scale).guide_geometry({labels:'Preserve'}).oob_function({operation:{id:'example.scale_vector',version:'1'},parameters:{mode:t.mode==='default'?'default':'oob_'+t.mode}});let draft=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').layer(layer(t)).aes(c.aes().x('i').y('v')).y_axis(axis).facet(c.facet_wrap('f').columns(3).order(t.panels==='occupied'?[['A'],['B']]:[['A'],['B'],['C']]).free_y(t.scales==='free_y'));if(shared){const target=broadcast?'Broadcast':'Match';draft=draft.transform(c.transform('mean',c.summary().x('v').group('g')).facet_target(target)).transform(c.transform('copy',c.identity_stat()).from_transform('mean').facet_target(target)).layer(c.points().name('copy').from_transform('copy').facet_target(target).after_stat(c.stat_aes().x(2).y('Mean')));}return draft.build();}
const scalar=v=>v&&typeof v==='object'?v.number:v;
function compare(a,b){if(typeof a==='number'&&typeof b==='number')assert.ok(Math.abs(a-b)<5e-14,`${a} != ${b}`);else if(Array.isArray(a)&&Array.isArray(b)){assert.equal(a.length,b.length);a.forEach((v,i)=>compare(v,b[i]));}else assert.deepEqual(a,b);}
function check(t,chart,frame){const panels=chart.semantics().panels,guides=frame.guides().guides;assert.equal(panels.length,t.panels==='occupied'?2:3);assert.equal(t.result.panels.length,panels.length);return {panels:panels.map((panel,index)=>{const wanted=t.result.panels[index],state=panel.layers[0],positions=state.point_positions;compare(positions.map(p=>scalar(p[1])),wanted.mapped.filter(v=>v!==null));if(t.kind==='point')compare(positions.map(p=>scalar(p[0])),wanted.x.filter((_,i)=>wanted.mapped[i]!==null));const ticks=guides.find(g=>JSON.stringify(g.scope)===JSON.stringify([{Panel:panel.key}])&&g.spec.side==='Left').ticks,expected=wanted.breaks.flatMap((v,i)=>typeof v==='number'?[[v,wanted.labels[i]]]:[]);compare(ticks.map(t=>t.label),expected.map(([,label])=>label??''));compare(ticks.map(t=>t.value.Number).map(v=>t.transform==='reverse'?-v:t.transform==='log10'?Math.log10(v):v),expected.map(([v])=>v));const entry={key:panel.key,positions,ticks,domains:state.domains,limits:panel.positional_limits??{}};if(shared){assert.equal(panel.layers.length,2);panel.layers.forEach((other,i)=>{compare(other.point_positions.map(p=>scalar(p[1])),wanted.mapped.filter(v=>v!==null));compare(other.point_positions.map(p=>scalar(p[0])),positions.map(()=>i+1));});entry.layers=panel.layers.map(other=>({positions:other.point_positions,domains:other.domains,operations:other.operations.map(op=>({operation:op.operation,counts:op.counts}))}));}return entry;})};}
for(const [index,t] of cases.entries()){
 const owned=[];
 try{
  const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,40);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
  for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layer(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!t.result.error,JSON.stringify(t));records.push({index,state,...check(t,chart,frame)});
   if(state==='original'&&t.population==='ordinary'&&t.mode==='index'&&(!binned||t.panels==='occupied'))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.kind}-${t.scales}-${t.transform}.${fmt}`),frame.export(fmt));
  }
 }catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${index}: ${error.stack}`);assert.ok(['CHART_SCHEMA_CONFLICT','CHART_NUMERICAL_DOMAIN'].includes(error.code));records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,broadcast?(binned?(shared?360:744):(shared?184:376)):(binned?(shared?342:696):(shared?182:417)));
for(const kind of (shared?['mean']:['point','mean']))for(const scales of ['fixed','free_y']){
 const selected=Object.fromEntries(cases.filter(t=>t.kind===kind&&t.scales===scales&&t.transform==='identity'&&t.mode==='index'&&(!binned||t.panels==='occupied')).map(t=>[t.population,t])),owned=[];
 try{
  const original=dataFor(selected.ordinary);owned.push(original);const p=build(selected.ordinary,original);owned.push(p);const chart=p.chart();owned.push(chart);const wire=p.to_json(),request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene();
  for(const population of ['missing','empty']){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);const ar=output.request(chart,options);owned.push(ar);const af=ar.prepare();owned.push(af);const br=output.request(batch,options);owned.push(br);const bf=br.prepare();owned.push(bf);const actual=check(t,chart,af);assert.deepEqual(actual,check(t,batch,bf));assert.equal(p.to_json(),wire);assert.deepEqual(held.scene(),scene);records.push({kind,scales,replacement:population,...actual});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,broadcast?(binned?(shared?364:752):(shared?188:384)):(binned?(shared?346:704):(shared?186:425)));fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));output.dispose();options.dispose();registry.dispose();console.log('PASS',records.length,'positional facet vector host states');
