'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const invalid=process.argv.includes('--gradient-invalid'),nonfinite=process.argv.includes('--gradient-nonfinite'),remap=process.argv.includes('--gradient-remap'),continuous=process.argv.includes('--continuous-constructors')||remap||nonfinite||invalid,constructors=process.argv.includes('--discrete-constructors'),qualitative=process.argv.includes('--qualitative-types'),ordinal=process.argv.includes('--ordinal-types')||qualitative||constructors,functions=process.argv.includes('--functions'),cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2',invalid?'gradient-invalid-constructors.json':nonfinite?'gradient-nonfinite-constructors.json':remap?'gradient-remap-constructors.json':continuous?'continuous-paint-constructors.json':constructors?'discrete-paint-constructors.json':qualitative?'qualitative-type-palettes.json':ordinal?'ordinal-type-palettes.json':functions?'binned-constructor-functions.json':'binned-constructor-palettes.json'))).cases,records=[],registry=c.ExtensionRegistry.example();
if(constructors||continuous)for(const t of cases)t.palette_name=t.constructor+'-'+t.configuration;
const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const dataFor=t=>c.Data.columns({x:c.column(t.inputs.map((_,i)=>i),{kind:'float64'}),v:c.column(ordinal?t.inputs:t.inputs.map(v=>v===null?null:Number(v)),{kind:ordinal?'string':'float64'}).nullable(true)},{name:'data'});
const layer=()=>((functions||ordinal||continuous)?c.points().aesthetic_value('Shape',{kind:'Number',value:21}):c.points()).name('marks');
function build(t,d){
 const palette=(functions||ordinal||continuous)?null:t.palette.length===1?{Named:t.palette[0]}:{Values:t.palette.map(v=>({kind:'Color',value:{space:'Rgb',channels:{r:parseInt(v.slice(1,3),16),g:parseInt(v.slice(3,5),16),b:parseInt(v.slice(5,7),16),opacity:1}}}))};
 const scale={training:'Eligible',function:{Interpolated:{normalization:{Ggplot:{family:'Linear',domain:[0,1],reverse:false,rescaler:'Range'}},output:'Identity',unknown:{kind:'Missing'}}},ggplot:{Binned:{palette:{Discrete:palette},limits:null,oob:'Squish',breaks:{Nice:t.count??5},right:true}},guide:'Hidden'};
 if(continuous){const name=t.constructor,custom=t.configuration==='custom',binned=name.startsWith('steps')||['fermenter','viridis_b'].includes(name),values=t.args.values??null;let recipe;
  if(['distiller','fermenter','viridis_c','viridis_b'].includes(name)){const countPalette=name.startsWith('viridis')?{Viridis:{option:custom?'Magma':'Viridis',begin:custom?.2:0,end:custom?.8:1,alpha:custom?.5:1,reverse:custom}}:{Brewer:{id:custom?'RdBu':'Blues',reverse:!custom}};if(binned){scale.ggplot.Binned.palette={Discrete:countPalette};recipe=null;}else recipe={CountGradient:{palette:countPalette,count:name==='distiller'?7:6,values}};
  }else{let colors=['gradient','steps'].includes(name)?(custom?['red','blue']:['#132B43','#56B1F7']):['gradient2','steps2'].includes(name)?(custom?['red','white','blue']:['#832424','white','#3A3A98']):(custom?['#ff000040','#ffffff80','#0000ffcc']:['red','white','blue']);if(t.args.colours!==undefined)colors=Array.isArray(t.args.colours)?t.args.colours:[t.args.colours];recipe={Gradient:{colors,values}};}
  if(!binned)scale.ggplot={Continuous:{limits:null,oob:'Censor'}};else if(recipe!==null)scale.ggplot.Binned.palette=null;
  if(recipe!==null)scale.function.Interpolated.output={Interpolate:{operation:'GgplotPalette',spec:recipe}};
  if(['gradient2','steps2'].includes(name))scale.function.Interpolated.normalization.Ggplot.rescaler={Midpoint:custom?1:0};
 }
 if(ordinal){scale.function={Ordinal:{domain:[],range:[],unknown:{Explicit:null}}};scale.ggplot={Discrete:{limits:null,levels:null,drop:true,na_translate:true,palette:{OrdinalColors:t.palette??[]}}};scale.missing_paint_is_na=!qualitative;if(qualitative)scale.ggplot.Discrete.palette={Qualitative:{palettes:t.palette.map(p=>({values:p.values,names:p.names===null?null:p.names.map(v=>({Text:v}))})),fallback:{h:[15,375],chroma:100,luminance:65,start:0,reverse:false}}};}
 if(constructors){const custom=t.configuration==='custom';scale.ggplot.Discrete.palette={hue:{Hue:{h:custom?[30,300]:[15,375],chroma:custom?50:100,luminance:custom?80:65,start:custom?10:0,reverse:custom}},grey:{Grey:{start:custom?.1:.2,end:custom?.9:.8}},brewer:{Brewer:{id:custom?'RdBu':'Blues',reverse:custom}},viridis_d:{Viridis:{option:custom?'Magma':'Viridis',begin:custom?.2:0,end:custom?.8:1,alpha:custom?.5:1,reverse:custom}}}[t.constructor];scale.missing_paint_is_na=['brewer','viridis_d'].includes(t.constructor);}
 if(functions){scale.ggplot.Binned.palette=null;scale.palette_function={operation:{id:'example.scale_palette',version:'1'},parameters:{mode:t.mode,channel:'colour',count:true}};}
 let m=c.aes().x('x').y(1);m=t.channel==='fill'?m.fill('v').fill_scale('v'):m.color('v').color_scale('v');let authored=c.color_mapped('v',scale);if(constructors&&t.constructor==='grey')authored=authored.missing('#FF0000');return c.plot(d).profile('Ggplot2_4_0_3').with_registry(registry).aes(m).scale(authored).layer(layer()).build();
}
const paint=raw=>{const v=({white:'#FFFFFF',red:'#FF0000',blue:'#0000FF',green:'#00FF00',black:'#000000',yellow:'#FFFF00',orange:'#FFA500',purple:'#A020F0',grey50:'#7F7F7F'}[raw]??raw);return v===null?{red:0,green:0,blue:0,alpha:0}:({red:parseInt(v.slice(1,3),16),green:parseInt(v.slice(3,5),16),blue:parseInt(v.slice(5,7),16),alpha:v.length===9?parseInt(v.slice(7,9),16):255});};
function check(t,chart){const styles=chart.semantics().layers[0].styles??[];assert.equal(styles.length,t.result.point_count,JSON.stringify(t));const wanted=(ordinal||continuous)?t.result.mapped.filter(v=>v!==null||t.channel==='fill'):t.result.point_colours;styles.forEach((style,i)=>assert.deepEqual(style[t.channel==='fill'?'fill':'color'],paint(wanted[i]),JSON.stringify(t)));return styles;}
for(const [index,t] of cases.entries()){
 const owned=[];try{
  let d,p,wire,restored,chart,styles;try{
   d=dataFor(t);owned.push(d);p=build(t,d);owned.push(p);wire=p.to_json();if(!constructors&&!continuous)assert.equal(JSON.parse(wire).version,qualitative?50:ordinal?49:functions?37:48);if(nonfinite)assert.equal(JSON.parse(wire).version,52);restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);chart=restored.chart();owned.push(chart);styles='error'in t.result?chart.semantics():check(t,chart);
  }catch(e){if(!(e instanceof c.ChartError))throw e;assert.ok('error'in t.result,JSON.stringify(t));records.push({index,state:'error'});continue;}
  assert.ok(!('error'in t.result),JSON.stringify(t));records.push({index,state:'original',styles});
  const edited=restored.edit().layer('marks',layer()).build();owned.push(edited);const ec=edited.chart();owned.push(ec);records.push({index,state:'layer_edit',styles:check(t,ec)});
  if(invalid&&t.population==='empty'&&t.configuration==='zero'&&t.constructor==='gradientn'){const request=output.request(restored,options);owned.push(request);const frame=request.prepare();owned.push(frame);for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.channel}-empty-invalid.${fmt}`),frame.export(fmt));}
  if(t.population==='ordinary'){
   const request=output.request(restored,options);owned.push(request);const frame=request.prepare();owned.push(frame);const scene=frame.scene();if(ordinal||continuous||t.count===5)for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.channel}-${functions?t.mode:t.palette_name}.${fmt}`),frame.export(fmt));
   for(const population of ['missing','empty','ordinary']){const expected=cases.find(x=>((ordinal||continuous)?['channel','palette_name']:['channel',functions?'mode':'palette_name','count']).every(k=>x[k]===t[k])&&x.population===population),replacement=dataFor(expected);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(d,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok(JSON.stringify(chart.commit(update)).includes('Applied'));const bp=build(expected,replacement);owned.push(bp);const batch=bp.chart();owned.push(batch);const actual=check(expected,chart);assert.deepEqual(actual,check(expected,batch));assert.equal(restored.to_json(),wire);assert.deepEqual(frame.scene(),scene);records.push({index,state:'replacement',population,styles:actual});}
  }
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,invalid?240:nonfinite?468:remap?288:continuous?480:constructors?208:qualitative?206:ordinal?154:functions?324:288);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));options.dispose();output.dispose();registry.dispose();console.log(`PASS ${records.length} constructor palette states and ${invalid?6:nonfinite?156:remap?96:continuous?120:(qualitative||constructors)?48:functions?36:30} publication files`);
