'use strict';
// GG-04: actual host continuous legend and break suppression semantics.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],colorbar=process.argv.includes("--colorbar"),transforms=process.argv.includes("--transforms"),intervals=process.argv.includes("--intervals")||transforms;
const cases=JSON.parse(fs.readFileSync(path.join(root,transforms?'fixtures/parity/ggplot2/continuous-interval-transforms.json':'fixtures/parity/ggplot2/continuous-guide-selection.json'))).cases.filter(t=>(intervals?['bins','coloursteps']:colorbar?['default','none','legend','colourbar']:['default','none','legend']).includes(t.guide));
function descriptor(t){const result={missing_paint_is_na:t.channel==='colour',training:'Eligible',
 guide:t.breaks==='null'||t.guide==='none'?'Hidden':{[({colourbar:'Colorbar',bins:'ContinuousBins',coloursteps:'ContinuousSteps'})[t.guide]??'Continuous']:{breaks:t.breaks==='uneven'?[0,.5,3,4]:t.breaks==='outside'?[-2,6]:t.breaks==='empty'?[]:null}},
 function:{Interpolated:{normalization:{Ggplot:{family:'Linear',domain:[0,4],reverse:false,rescaler:'Range'}},output:{Interpolate:{operation:'PowerRange',range:[0,1],exponent:1,absolute:false}},unknown:{kind:'Missing'}}},
 ggplot:{Continuous:{limits:[0,4],oob:'Censor'}},palette_function:{operation:{id:'example.scale_palette',version:'1'},parameters:{mode:t.palette_mode??'full',channel:t.channel}}};
 if(transforms){const tr=t.transform==='log10'?{Log:{base:10}}:{Registered:{selection:{call:{operation:{id:'example.scale_transform_vector',version:'1'},parameters:{family:t.transform}}}}};Object.assign(result.function.Interpolated.normalization.Ggplot,{family:{Ggplot:{transform:tr}},domain:[1,16]});result.ggplot.Continuous.limits=[1,16];if(t.breaks==='uneven')result.guide[t.guide==='bins'?'ContinuousBins':'ContinuousSteps'].breaks=[1,2,8,16];}return result;}

const layer=t=>t.channel==='colour'?c.points().name('marks'):c.points().name('marks').numeric_scale(t.channel==='size'?'Size':'Alpha','v',descriptor(t));
function build(t){const values=t.inputs.map(v=>typeof v==='string'?Number(v):v),data=c.Data.columns({x:c.column(values.map((_,i)=>i),{kind:'float64'}),v:c.column(values,{kind:'float64'}).nullable(true)},{name:'data'});let draft=c.plot(data).profile('Ggplot2_4_0_3').with_registry(registry);
 if(t.channel==='colour')draft=draft.aes(c.aes().x('x').y(1).color('v').color_scale('v')).scale(c.color_mapped('v',descriptor(t)));else draft=draft.aes(c.aes().x('x').y(1));return [data,draft.layer(layer(t)).build()];}
function check(t,chart){const state=chart.semantics().layers[0],entries=(t.channel==='colour'?(state.color_legend?.numeric_breaks??[]):Object.values(state.numeric_value_guides??{}).flat()).filter(e=>e.visible),actual={values:entries.map(e=>transforms?e.transformed:e.value),labels:entries.map(e=>e.label)},wanted=t.result.guides;
 const expected=wanted.length?{values:transforms?wanted[0].scale_values:intervals?wanted[0].source_values:t.guide==='colourbar'?t.result.raw_breaks:wanted[0].values,labels:wanted[0].labels}:{values:[],labels:[]};
 if(transforms){assert.deepEqual(actual.labels,expected.labels,JSON.stringify(t));assert.equal(actual.values.length,expected.values.length);actual.values.forEach((a,i)=>assert.ok(Math.abs(a-expected.values[i])<=4e-14*Math.max(1,Math.abs(a),Math.abs(expected.values[i])),JSON.stringify(t)));if(t.palette_mode==='index'){const styles=state.styles??[];assert.equal(styles.length,t.result.mapped.length);styles.forEach((style,i)=>{const mapped=t.result.mapped[i];if(t.channel==='size')assert.ok(Math.abs(style.radius-mapped)<=4e-14*Math.max(1,Math.abs(mapped)));else if(t.channel==='alpha')assert.equal(style.color.alpha,Math.floor(mapped*255+.5));else assert.deepEqual(style.color,{red:parseInt(mapped.slice(1,3),16),green:parseInt(mapped.slice(3,5),16),blue:parseInt(mapped.slice(5,7),16),alpha:255});});}}else assert.deepEqual(actual,expected,JSON.stringify(t));const ramp=state.color_legend?.colorbar??[];
 if(t.guide==='colourbar'&&t.channel==='colour'&&wanted.length){assert.equal(ramp.length,300);ramp.forEach((sample,i)=>{assert.ok(Math.abs(sample.value-wanted[0].decor_values[i])<=8e-15);const text=wanted[0].decor_colors[i];assert.deepEqual(sample.color,{red:parseInt(text.slice(1,3),16),green:parseInt(text.slice(3,5),16),blue:parseInt(text.slice(5,7),16),alpha:255});});}else assert.equal(ramp.length,0);
 return {keys:actual,styles:state.styles??[],...(colorbar?{colorbar:ramp}:{})};}
const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
for(const [index,t] of cases.entries()){const owned=[];try{
 const [data,p]=build(t);owned.push(data,p);const wire=p.to_json(),restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
 if(t.guide==='colourbar'&&t.breaks!=='null'){const old=JSON.parse(wire);assert.equal(old.version,57);old.version=56;assert.throws(()=>c.Plot.from_json(JSON.stringify(old),registry));}
 if(intervals&&t.breaks!=='null'){const old=JSON.parse(wire);assert.equal(old.version,58);old.version=57;assert.throws(()=>c.Plot.from_json(JSON.stringify(old),registry));}
 for(const state of ['original','layer_edit','theme_edit']){const current=state==='original'?restored:state==='layer_edit'?restored.edit().layer('marks',layer(t)).build():restored.edit().theme(c.theme()).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);records.push({index,state,...check(t,chart)});assert.equal(restored.to_json(),wire);}
 if((t.population==='ordinary'||t.palette_mode==='index')&&['default','colourbar','bins','coloursteps'].includes(t.guide)){const request=output.request(restored,options);owned.push(request);const frame=request.prepare();owned.push(frame);for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${transforms?t.transform+'-'+t.palette_mode+'-':''}${t.channel}-${t.breaks}${t.guide!=='default'?'-'+t.guide:''}.${fmt}`),frame.export(fmt));}
 }finally{for(const obj of owned.reverse())obj.dispose();}}
assert.equal(records.length,transforms?324:intervals?216:colorbar?351:243);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));options.dispose();output.dispose();registry.dispose();console.log('PASS WASM:',records.length,'continuous guide-selection states;',fs.readdirSync(out).filter(f=>f.endsWith('.svg')).length*3,'publications');
