'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const family=process.argv[4]??"continuous";
const labelPipelines=process.argv.includes('--guide-label-pipelines');
const guideSelection=process.argv.includes('--guide-selection')||labelPipelines;
const cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2',labelPipelines?'binned-guide-label-pipelines.json':guideSelection?'binned-guide-selection.json':'scale-pipeline-draws.json'))).cases.filter(t=>t.family===family);
if(guideSelection){assert.equal(family,'binned');for(const t of cases)t.guide_mode=t.guide_kind==='none'?'hidden':t.guide_kind==='default'?'bins':t.guide_kind;}
function descriptor(t){const call={operation:{id:t.operation??'example.scale_vector',version:'1'},parameters:{mode:t.mode,family:t.family}};const result={missing_paint_is_na:t.channel==='colour',training:'Eligible',function:{Interpolated:{normalization:{Ggplot:{family:'Linear',domain:[1,10],reverse:false,rescaler:'Range'}},output:'Identity',unknown:{kind:'Missing'}}},ggplot:family==='continuous'?{Continuous:{limits:[1,10],oob:'Censor'}}:{Binned:{limits:[1,10],oob:'Squish',breaks:{Nice:5},right:true}},guide:t.guide_mode==='hidden'?'Hidden':(family==='continuous'?{Continuous:{labels:'Automatic'}}:{[({bins:'BinnedBins',coloursteps:'BinnedSteps'})[t.guide_mode]??'BinnedLegend']:'Automatic'}),oob_function:call,rescaler_function:call,palette_function:{operation:{id:'example.scale_palette',version:'1'},parameters:{mode:'full',channel:t.channel}}};if(t.label_mode)result.guide[Object.keys(result.guide)[0]]={Registered:{operation:{id:'example.scale_labels',version:'1'},parameters:t.label_mode}};if(['automatic','callback'].includes(t.limit_mode))result.ggplot.Binned.limits=null;if(t.limit_mode==='callback')result.limits_function={operation:{id:'example.numeric_limits',version:'1'},parameters:{mode:'identity'}};return result;}
function layer(t){return t.channel==='colour'?c.points().name('marks'):c.points().name('marks').numeric_scale(t.channel==='size'?'Size':'Alpha','v',descriptor(t));}
function dataFor(t,name="data"){return c.Data.columns({x:c.column(t.inputs.map((_,i)=>i),{kind:'float64'}),v:c.column(t.inputs.map(v=>v==='Infinity'?Infinity:v==='-Infinity'?-Infinity:v),{kind:'float64'}).nullable(true)},{name});}
function build(t,d){const draft=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3');if(t.channel==='colour'){let scale=c.color_mapped('v',descriptor(t));if(t.na_mode&&t.na_mode!=='NA')scale=scale.missing(paint(t.na_mode==='green'?'#00ff00':'#00000000'));return draft.aes(c.aes().x('x').y(1).color('v').color_scale('v')).scale(scale).layer(layer(t)).build();}return draft.aes(c.aes().x('x').y(1)).layer(layer(t)).build();}
function compare(a,b){if(typeof a==='number'&&typeof b==='number')assert.ok(Math.abs(a-b)<5e-14,`${a} != ${b}`);else if(Array.isArray(a)&&Array.isArray(b)){assert.equal(a.length,b.length);a.forEach((v,i)=>compare(v,b[i]));}else if(a&&b&&typeof a==='object'&&typeof b==='object'){assert.deepEqual(Object.keys(a).sort(),Object.keys(b).sort());for(const k of Object.keys(a))compare(a[k],b[k]);}else assert.deepEqual(a,b);}
function paint(v){if(v==='black')v='#000000';return v===null?{red:0,green:0,blue:0,alpha:0}:Object.fromEntries(['red','green','blue','alpha'].map((k,i)=>[k,i===3?(v.length===9?parseInt(v.slice(7,9),16):255):parseInt(v.slice(1+2*i,3+2*i),16)]));}
function check(t,chart,index=0){const state=chart.semantics().layers[index],styles=state.styles??[],wanted=t.result.mapped;assert.equal(styles.length,t.result.point_count,JSON.stringify(t));compare(styles.map(s=>s.color),t.result.point_colours.map(paint));const entries=(t.channel==='colour'?(state.color_legend?.numeric_breaks??[]):Object.values(state.numeric_value_guides??{}).flat()).filter(e=>e.visible);const mapped=v=>['Missing','Null'].includes(v.kind)?null:(typeof v.value==='object'?v.value.number:v.value);const boundaries=entries.length&&t.guide_mode==='coloursteps'?[...new Set([...entries.map(e=>e.transformed),...t.calls[0].range])].sort((a,b)=>a-b):[];compare(entries.length?[{values:entries.map((e,i)=>t.guide_mode==='bins'?i/(entries.length-1):t.guide_mode==='coloursteps'?boundaries.indexOf(e.transformed)/(boundaries.length-1):e.value),labels:entries.map(e=>e.label??null),mapped:entries.map(e=>mapped(e.mapped))}]:[],t.result.keys);if(t.channel==='size')compare(styles.map(s=>typeof s.radius==='object'?s.radius.number:s.radius),wanted.filter(v=>v!==null));return {styles,numeric_scales:Object.fromEntries(Object.entries(state.numeric_scales??{}).map(([k,v])=>[k,v.scale])),numeric_value_guides:Object.values(state.numeric_value_guides??{}),color_legend:state.color_legend?Object.fromEntries(Object.entries(state.color_legend).filter(([k])=>k!=='id')):null};}
for(const [index,t] of cases.entries()){
 const owned=[];
 try{
  const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,['bins','coloursteps'].includes(t.guide_mode)?44:t.family==='binned'&&t.guide_mode!=='hidden'?39:38);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
  for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layer(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const actual=check(t,chart);assert.ok(!t.result.error,JSON.stringify(t));records.push({index,state,...actual});}
  const sample=(!labelPipelines||t.label_mode==='indexed')&&(t.guide_mode==='hidden'||(['bins','coloursteps'].includes(t.guide_mode)&&t.limit_mode==='full'))&&((t.population==='ordinary'&&['default','rescale_index','rescale_short'].includes(t.mode))||(t.population==='missing'&&t.mode==='default'));
  if(sample){const request=output.request(restored,options);owned.push(request);const frame=request.prepare();owned.push(frame);for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${guideSelection?t.guide_mode+'-'+t.limit_mode+'-':''}${t.channel}-${t.population}-${t.mode}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${index}: ${error.stack}`);assert.ok(['CHART_VALIDATION','CHART_NUMERICAL_DOMAIN'].includes(error.code));records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
for(const replacementLabels of (labelPipelines?['indexed','missing']:[undefined]))for(const replacementGuide of (labelPipelines?['bins','coloursteps']:guideSelection?['hidden','bins','coloursteps']:['hidden']))for(const channel of ['colour','size','alpha'])for(const mode of ['default','rescale_index']){
 const selected=Object.fromEntries(cases.filter(t=>t.label_mode===replacementLabels&&t.guide_mode===replacementGuide&&t.channel===channel&&t.mode===mode).map(t=>[t.population,t])),owned=[];
 try{
  const original=dataFor(selected.ordinary);owned.push(original);const p=build(selected.ordinary,original);owned.push(p);const chart=p.chart();owned.push(chart);const wire=p.to_json(),request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene();
  for(const population of ['missing','empty','ordinary']){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);const actual=check(t,chart);assert.deepEqual(actual,check(t,batch));assert.equal(p.to_json(),wire);assert.deepEqual(held.scene(),scene);records.push({channel,mode,replacement:population,...(guideSelection?{guide:replacementGuide}:{}),...(labelPipelines?{label_mode:replacementLabels}:{}),...actual});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
for(const variant of ['missing_registration','native_only','invalid_parameters','downgrade']){
 const t=structuredClone(cases[0]),owned=[];
 if(variant==='missing_registration')t.operation='example.missing_vector';if(variant==='native_only')t.operation='example.native_scale_vector';if(variant==='invalid_parameters')t.mode='invalid';
 try{const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);let wire=p.to_json();if(variant==='downgrade'){wire=JSON.parse(wire);wire.version=37;const restored=c.Plot.from_json(JSON.stringify(wire),registry);owned.push(restored);}assert.fail('expected rejection: '+variant);}
 catch(error){assert.ok(error instanceof c.ChartError,error.stack);records.push({rejection:variant,code:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,labelPipelines?268:guideSelection?1068:283);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));output.dispose();registry.dispose();console.log('PASS',records.length,family+' vector pipeline host states');
