'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,640).dpi(96).basis('current');
let cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-facet-functions.json'))).cases.concat(JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-facet-temporal-functions.json'))).cases,JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-facet-bin-functions.json'))).cases);
function rejected(t){return Boolean(t.result.error);}
function mapping(t){return ['date','datetime'].includes(t.kind)?{field:'v',origin:'1704067200000'}:'v';}
function family(t){return t.kind==='binned'?'binned_'+t.transform:t.kind??t.transform;}
function dataFor(t){let values=c.column(t.inputs.map(v=>v??0),{kind:'float64'});if(['date','datetime'].includes(t.kind)){const factor=t.kind==='date'?86400000:1000;values=c.timestamps(t.inputs.map(v=>v===null?1704067200000:Math.round(v*factor)),'ms','UTC');}return c.Data.columns({v:values.validity(t.inputs.map(v=>v!==null)),panel:c.categorical(t.groups)},{keys:[100,101,102,103]});}
function layerFor(t){const layer=c.points().name('marks');return t.context==='summary'?layer.stat(c.summary().x(mapping(t))).after_stat(c.stat_aes().x(1).y('Mean')):layer;}
const authored=process.argv[4]==='authored';if(authored)cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-facet-authored-limits.json'))).cases;
const automatic=process.argv[4]==='automatic';if(automatic)cases=cases.filter(t=>t.kind==='datetime');
function build(t,d){const summary=t.context==='summary',free=t.policy==='free',scale=t.kind==='binned'?c.scale_binned({transform:{identity:null,sqrt:'Sqrt',reverse:'Reverse'}[t.transform]}):{identity:c.scale_linear,sqrt:c.scale_sqrt,reverse:c.scale_reverse,date:c.scale_date,datetime:c.scale_utc,duration:c.scale_duration}[family(t)]();let axis=(summary?c.y_axis():c.x_axis());if(!automatic)axis=axis.scale(scale);axis=axis.guide_geometry({labels:'Preserve'}).oob(t.oob[0].toUpperCase()+t.oob.slice(1));if(t.authored)axis=axis.numericLimits(t.limits);else if(t.control!=='automatic')axis=axis.limitsFunction({operation:{id:'example.numeric_limits',version:'1'},parameters:{mode:t.control}});const p=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').aes(c.aes().x(summary?1:mapping(t)).y(summary?mapping(t):1)).layer(layerFor(t)).facet(c.facet_wrap('panel').columns(3).order(t.levels.map(v=>[v])).empty('Keep').free_x(free&&!summary).free_y(free&&summary));return(summary?p.y_axis(axis).x_axis(c.x_axis().visible(false)):p.x_axis(axis).y_axis(c.y_axis().visible(false))).build();}

function numeric(v){return v===null?NaN:Number(v);}
function equal(a,b){return a===b||Number.isNaN(a)&&Number.isNaN(b)||Math.abs(a-b)<=3e-12*Math.max(1,Math.abs(b));}
function retained(chart){return chart.semantics().panels.map(p=>({key:p.key,domains:p.layers.map(l=>l.domains),limits:p.positional_limits??{}}));}
function check(t,chart,frame){const summary=t.context==='summary',dimension=summary?'y':'x',scene=frame.scene(),guides=frame.guides().guides,result=[];assert.equal(scene.panels.length,t.result.panels.length);
 for(const[i,panel]of scene.panels.entries()){const expected=t.result.panels[i],key=panel.key;assert.deepEqual(key.values,[{Text:expected.key}]);const plot=panel.plot,start=plot.origin[dimension]+(summary?plot.height:0),length=summary?-plot.height:plot.width;
 const points=scene.items.flatMap((item,i)=>JSON.stringify(scene.item_panels[i])===JSON.stringify(key)&&item.layer!=null&&item.primitive.Point?[(item.primitive.Point.center[dimension]-start)/length]:[]),wanted=expected.point_positions.filter(v=>v!==null&&Number.isFinite(numeric(v))).map(numeric);assert.equal(points.length,wanted.length,JSON.stringify({t,key,points,wanted}));assert.ok(points.every((a,i)=>equal(a,wanted[i])),JSON.stringify({t,key,points,wanted}));
 const ticks=guides.find(g=>JSON.stringify(g.scope)===JSON.stringify([{Panel:key}])&&g.spec.side===(summary?'Left':'Bottom')).ticks,expectedTicks=expected.positions.flatMap((position,i)=>position!==null&&Number.isFinite(numeric(position))?[[expected.labels[i],numeric(position)]]:[]);assert.equal(ticks.length,expectedTicks.length,JSON.stringify({t,key,ticks,expectedTicks}));for(const[i,tick]of ticks.entries()){const[label,position]=expectedTicks[i];assert.ok(tick.label===label&&equal((tick.position-start)/length,position),JSON.stringify({t,key,tick,label,position}));}result.push({key,points,ticks});}
 return{panels:result,retained:retained(chart)};}
function sample(t){if(t.authored)return t.control==='partial_lower'&&t.population==='missing'&&t.oob==='censor';if(t.kind==='binned')return t.control==='automatic'&&t.population==='balanced'&&t.oob==='censor';if(t.kind)return t.control==='identity'&&t.oob==='censor'&&(t.context==='points'&&t.population==='balanced'||t.context==='summary'&&t.population==='fractional');return t.control==='identity'&&t.oob==='censor'&&(t.transform==='identity'&&t.population==='balanced'||t.transform==='sqrt'&&t.context==='summary'&&t.population==='constant'||t.transform==='reverse'&&t.context==='points'&&t.population==='empty_panel');}
for(const[index,t]of cases.entries()){
 const owned=[];
 try{const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,authored?31:t.control==='automatic'?18:29);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
 for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layerFor(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!rejected(t),JSON.stringify(t));records.push({index,state,...check(t,chart,frame)});if(state==='original'&&sample(t))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.context}-${family(t)}-${t.policy}-${t.population}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&rejected(t),`${JSON.stringify(t)}: ${error.stack}`);assert.equal(error.code,'CHART_NUMERICAL_DOMAIN');records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,authored?1434:automatic?649:5360);
for(const context of ['points','summary'])for(const transform of (authored?['identity','sqrt','reverse']:automatic?['datetime']:['identity','sqrt','reverse','date','datetime','duration','binned_identity','binned_sqrt','binned_reverse']))for(const policy of ['fixed','free']){
 const owned=[];
 try{const selected=Object.fromEntries(cases.filter(t=>t.context===context&&family(t)===transform&&t.policy===policy&&t.control===(authored?'partial_lower':transform.startsWith('binned_')?'automatic':'identity')&&t.oob==='censor').map(t=>[t.population,t]));const original=dataFor(selected.balanced);owned.push(original);const p=build(selected.balanced,original);owned.push(p);const chart=p.chart();owned.push(chart);const request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene(),wire=p.to_json();
  for(const population of ['constant','missing','balanced','constant']){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied'in chart.commit(update));function capture(current){try{return{panels:retained(current)};}catch(error){assert.ok(error instanceof c.ChartError);return{error:error.code};}}const actual=capture(chart);let expected;try{const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);expected=capture(batch);}catch(error){assert.ok(error instanceof c.ChartError);expected={error:error.code};}assert.deepEqual(actual,expected);assert.deepEqual(held.scene(),scene);assert.equal(p.to_json(),wire);records.push({context,transform,policy,replacement:population,...actual});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,authored?1482:automatic?665:5504);fs.writeFileSync(path.join(out,'position-facet-records.json'),JSON.stringify(records,null,2));options.dispose();output.dispose();registry.dispose();console.log('PASS WASM:',records.length,'faceted positional callback states.');
