'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const cases=[...JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/palette-functions.json'))).cases.filter(t=>t.family==='discrete'),...JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/discrete-palette-lookup.json'))).cases,...JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/discrete-palette-missing-paint.json'))).cases];
const key=v=>v===null?'Null':{Text:v};
function descriptor(t){const s={missing_paint_is_na:t.channel==='colour',training:'Eligible',function:{Ordinal:{domain:[],range:[],unknown:{Explicit:null}}},ggplot:{Discrete:{limits:t.limits==='full'?['a','b','c','d'].map(key):null,levels:null,drop:true,na_translate:true,palette:{Hue:{h:[15,375],chroma:100,luminance:65,start:0,reverse:false}}}},palette_function:{operation:{id:t.operation??'example.scale_palette',version:'1'},parameters:{mode:t.mode,channel:t.channel}}};if(t.guide_mode==='hidden')s.guide='Hidden';if(t.guide_mode==='first')s.guide={Discrete:{breaks:[key('a')]}};return s;}
function layer(t){return t.channel==='colour'?c.points().name('marks'):c.points().name('marks').numeric_scale(t.channel==='size'?'Size':'Alpha','v',descriptor(t));}
function dataFor(t){return c.Data.columns({x:c.column(t.inputs.map((_,i)=>i),{kind:'float64'}),v:c.column(t.inputs,{kind:'string'}).nullable(true)});}
function build(t,d){const draft=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3');if(t.channel==='colour'){let scale=c.color_mapped('v',descriptor(t));if(t.na_mode&&t.na_mode!=='NA')scale=scale.missing(paint(t.na_mode==='green'?'#00ff00':'#00000000'));return draft.aes(c.aes().x('x').y(1).color('v').color_scale('v')).scale(scale).layer(layer(t)).build();}return draft.aes(c.aes().x('x').y(1)).layer(layer(t)).build();}
function compare(a,b){if(typeof a==='number'&&typeof b==='number')assert.ok(Math.abs(a-b)<5e-14,`${a} != ${b}`);else if(Array.isArray(a)&&Array.isArray(b)){assert.equal(a.length,b.length);a.forEach((v,i)=>compare(v,b[i]));}else if(a&&b&&typeof a==='object'&&typeof b==='object'){assert.deepEqual(Object.keys(a).sort(),Object.keys(b).sort());for(const k of Object.keys(a))compare(a[k],b[k]);}else assert.deepEqual(a,b);}
function paint(v){return v===null?{red:0,green:0,blue:0,alpha:0}:Object.fromEntries(['red','green','blue','alpha'].map((k,i)=>[k,i===3?(v.length===9?parseInt(v.slice(7,9),16):255):parseInt(v.slice(1+2*i,3+2*i),16)]));}
function check(t,chart){const state=chart.semantics().layers[0];let spec,entries;if(t.channel==='colour'){compare((state.styles??[]).map(s=>s.color),t.result.mapped.filter(v=>v!==null).map(paint));if(!state.color_legend){assert.equal(t.result.keys?.length??0,0);return {mapped:null,domain:null,guide:[],styles:state.styles??[]};}spec=state.color_legend.mapping;entries=state.color_legend.entries;}else{spec=state.numeric_scales[t.channel==='size'?'Size':'Alpha'].scale;entries=Object.values(state.discrete_value_guides??{}).flat();}const ordinal=spec.function.Ordinal,domain=ordinal.domain.map(k=>typeof k==='object'?k.Text??null:null);function fallback(){if(t.channel!=='colour'||spec.missing_paint_is_na)return null;const missing=state.color_legend.missing;return '#'+['red','green','blue'].map(k=>missing[k].toString(16).padStart(2,'0')).join('')+(missing.alpha===255?'':missing.alpha.toString(16).padStart(2,'0'));}function sample(v){if(v===null||!domain.includes(v))return fallback();const index=domain.indexOf(v),raw=ordinal.range[index];return ['Number','Text'].includes(raw.kind)?raw.value:(spec.palette_fallback_indices??[]).includes(index)?fallback():null;}const actual=t.inputs.map(sample);compare(actual,t.result.mapped);const expected=t.result.keys?.[0]??{values:[],labels:[],mapped:[]};if(t.channel==='colour')compare(entries,expected.labels.map((label,i)=>[label??'NA',paint(expected.mapped[i])]));else compare({values:entries.map(e=>typeof e.key==='object'?e.key.Text??null:null),labels:entries.map(e=>e.label),mapped:entries.map(e=>sample(typeof e.key==='object'?e.key.Text??null:null))},expected);return {mapped:actual,domain,guide:entries,styles:state.styles??[]};}
for(const [index,t] of cases.entries()){
 const owned=[];
 try{
  const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,37);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
  for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layer(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const actual=check(t,chart);assert.ok(!t.result.error,JSON.stringify(t));records.push({index,state,...actual});}
  let sample=null;if(!t.guide_mode&&!t.na_mode&&t.limits==='none'&&t.mode==='named'&&['ordinary','missing'].includes(t.population))sample=`${t.channel}-${t.population}`;if(t.na_mode&&t.mode==='missing'&&t.population==='missing')sample=`na-${t.na_mode.toLowerCase()}`;
  if(sample){const request=output.request(restored,options);owned.push(request);const frame=request.prepare();owned.push(frame);for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${sample}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${index}: ${error.stack}`);assert.equal(error.code,'CHART_VALIDATION');records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
for(const channel of ['colour','size','alpha'])for(const mode of ['full','named']){
 const selected=Object.fromEntries(cases.filter(t=>!t.guide_mode&&!t.na_mode&&t.channel===channel&&t.limits==='none'&&t.mode===mode).map(t=>[t.population,t])),owned=[];
 try{
  const original=dataFor(selected.ordinary);owned.push(original);const p=build(selected.ordinary,original);owned.push(p);const chart=p.chart();owned.push(chart);const wire=p.to_json(),request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene();
  for(const population of ['missing','all_missing','empty','ordinary']){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);const actual=check(t,chart);assert.deepEqual(actual,check(t,batch));assert.equal(p.to_json(),wire);assert.deepEqual(held.scene(),scene);records.push({channel,mode,replacement:population,...actual});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
for(const variant of ['missing_registration','native_only','invalid_parameters','downgrade']){
 const t=structuredClone(cases[0]),owned=[];if(variant==='missing_registration')t.operation='example.missing_palette';if(variant==='native_only')t.operation='example.native_scale_palette';if(variant==='invalid_parameters')t.mode='invalid';
 try{const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);let wire=p.to_json();if(variant==='downgrade'){wire=JSON.parse(wire);wire.version=36;const restored=c.Plot.from_json(JSON.stringify(wire),registry);owned.push(restored);}assert.fail(`expected rejection: ${variant}`);}catch(error){assert.ok(error instanceof c.ChartError,error.stack);records.push({rejection:variant,code:error.code});}finally{for(const obj of owned.reverse())obj.dispose();}
}
const expected=cases.reduce((n,t)=>n+(t.result.error?1:2),0)+28;assert.equal(records.length,expected);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records,null,2));output.dispose();registry.dispose();console.log(`PASS WASM: ${records.length} discrete palette states including 24 replacements and four rejection contracts.`);
