'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,640).dpi(96).basis('current');
const cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-missing.json'))).cases.concat(JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-duration-missing.json'))).cases);
function rejected(t){return Boolean(t.result.error)||Boolean(t.result.positions?.error);}
function dataFor(t){const values=c.column(t.inputs.map(v=>v??0),{kind:'float64'}).validity(t.inputs.map(v=>v!==null));return c.Data.columns(t.context==='summary'?{x:c.column(t.inputs.map(()=>1),{kind:'float64'}),y:values}:{x:values},{keys:t.inputs.map((_,i)=>100+i)});}
function layerFor(t){const layer=c.points().name('marks');return t.context==='summary'?layer.stat(c.summary().x('y')).after_stat(c.stat_aes().x(1).y('Mean')):layer;}
function build(t,d){const summary=t.context==='summary';let scale={identity:c.scale_linear,sqrt:c.scale_sqrt,reverse:c.scale_reverse,log10:()=>c.scale_log(10),duration:c.scale_duration}[t.transform]();if(t.limit_control==='fixed')scale=scale.domain(1,4);let axis=(summary?c.y_axis():c.x_axis()).scale(scale).range(100,540).guide_geometry({labels:'Preserve'}).oob(t.oob[0].toUpperCase()+t.oob.slice(1)).missingValue({missing:null,zero:0,five:5,negative:-1}[t.replacement]);if(t.limit_control==='function')axis=axis.limitsFunction({operation:{id:'example.numeric_limits',version:'1'},parameters:{mode:'identity'}});const p=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').aes(c.aes().x('x').y(summary?'y':1)).layer(layerFor(t));return(summary?p.y_axis(axis).x_axis(c.x_axis().visible(false)):p.x_axis(axis).y_axis(c.y_axis().visible(false))).build();}
function numeric(v){return v===null?NaN:Number(v);}
function equal(a,b){return a===b||Number.isNaN(a)&&Number.isNaN(b)||Math.abs(a-b)<=3e-12*Math.max(1,Math.abs(b));}
function check(t,chart,frame){const summary=t.context==='summary',dimension=summary?'y':'x';const points=frame.scene().items.filter(i=>i.layer!=null&&i.primitive.Point).map(i=>(i.primitive.Point.center[dimension]-100)/440),expected=(t.result.coordinate_positions??t.result.point_positions).filter(v=>v!==null&&Number.isFinite(numeric(v))).map(numeric);assert.equal(points.length,expected.length,JSON.stringify({t,points,expected}));assert.ok(points.every((a,i)=>equal(a,expected[i])),JSON.stringify({t,points,expected}));const ticks=frame.guides().guides.find(g=>g.spec.side===(summary?'Left':'Bottom')).ticks,wanted=t.result.positions.flatMap((position,i)=>position!==null&&Number.isFinite(numeric(position))?[[t.result.labels[i],numeric(position)]]:[]);assert.equal(ticks.length,wanted.length,JSON.stringify({t,ticks,wanted}));for(const[label,position]of wanted)assert.ok(ticks.some(tick=>tick.label===label&&equal((tick.position-100)/440,position)),JSON.stringify({t,ticks,label,position}));const semantics=chart.semantics();return{points,ticks,domains:semantics.layers[0].domains,limits:semantics.positional_limits??{}};}
function sample(t){return t.replacement==='negative'&&t.oob==='censor'&&((t.population==='mixed'&&t.limit_control==='auto'&&['identity','sqrt','log10','duration'].includes(t.transform))||(t.population==='all_missing'&&t.limit_control==='auto'&&t.transform==='sqrt'&&t.context==='points')||(t.population==='mixed'&&t.limit_control==='function'&&t.transform==='log10'&&t.context==='summary'));}
for(const[index,t]of cases.entries()){
 const owned=[];
 try{const d=dataFor(t);owned.push(d);const p=build(t,d);owned.push(p);const wire=p.to_json();if(t.replacement!=='missing')assert.equal(JSON.parse(wire).version,30);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
 for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layerFor(t)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!rejected(t),JSON.stringify(t));records.push({index,state,...check(t,chart,frame)});if(state==='original'&&sample(t))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.context}-${t.transform}-${t.population}-${t.limit_control}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&rejected(t),`${JSON.stringify(t)}: ${error.stack}`);assert.equal(error.code,'CHART_NUMERICAL_DOMAIN');records.push({index,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,2520);for(const [context,transform] of [['points','identity'],['points','sqrt'],['summary','log10'],['points','duration'],['summary','duration']]){
 const owned=[];
 try{const selected=Object.fromEntries(cases.filter(t=>t.context===context&&t.transform===transform&&t.replacement==='negative'&&t.limit_control==='auto'&&t.oob==='censor').map(t=>[t.population,t]));const original=dataFor(selected.mixed);owned.push(original);const p=build(selected.mixed,original);owned.push(p);const chart=p.chart();owned.push(chart);const request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene(),wire=p.to_json();
 for(const population of ['constant','all_missing','empty','mixed']){const t=selected[population],replacement=dataFor(t);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const fresh=build(t,replacement);owned.push(fresh);const batch=fresh.chart();owned.push(batch);const actual=chart.semantics(),expected=batch.semantics();assert.deepEqual(actual.layers[0].domains,expected.layers[0].domains);assert.deepEqual(actual.positional_limits??{},expected.positional_limits??{});assert.deepEqual(held.scene(),scene);assert.equal(p.to_json(),wire);records.push({context,transform,replacement:population,domains:actual.layers[0].domains,limits:actual.positional_limits??{}});}
 }finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,2540);fs.writeFileSync(path.join(out,'position-missing-records.json'),JSON.stringify(records,null,2));options.dispose();output.dispose();registry.dispose();console.log('PASS WASM:',records.length,'positional missing-value states.');
