// FIX-GG14 independent WASM precomputed theme controls authors.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const columns=(data,options)=>c.Data.columns(Object.fromEntries(Object.entries(data).map(([k,v])=>[k,v.every(x=>typeof x==='number')?new Float64Array(v):v])),options);
const output=new c.Output(fs.readFileSync(path.join(ROOT,'fixtures/capability/fonts/NotoSans-Regular.ttf')));
for(let mode=0;mode<16;mode++){
 const data=columns({x:[1,2,3,4],y:[2,1,4,3],g:["A","A","B","B"]}),presets=['Grey','Bw','Linedraw','Light','Dark','Minimal','Classic','Void','Test'];
 let themed=c.theme().reference_preset(presets[Math.min(mode,8)],{});
 if(mode===9)themed=c.theme().reference_preset('Grey',{base_size:16,ink:'#123456',paper:'#F8EEDD',accent:'#D020A0'});
 else if(mode===10)themed=themed.update_elements({complete:false,elements:{'axis.text':'Blank','axis.text.x':{Element:{kind:'Text',properties:{'inherit.blank':{Bool:false},colour:{Text:'red'},size:{Relative:1.5}}}}}});
 else if(mode===11)themed=themed.update_elements({complete:false,elements:{'axis.ticks.length.y':{Value:{Unit:[{value:-2,unit:'mm'}]}},'axis.line.y':{Element:{kind:'Line',properties:{colour:{Text:'#008080'},linewidth:{Number:1},arrow:{Arrow:{angle:25,length_mm:4,ends:"Both",closed:true}},"arrow.fill":{Text:"red"},lineend:{Text:"square"},linetype:{Text:"dashed"}}}}}});
 if(mode===12)themed=themed.update_elements({complete:false,elements:{'panel.spacing.x':{Value:{Unit:[{value:8,unit:'mm'}]}},'legend.position':{Value:{Text:'bottom'}},'strip.background':{Element:{kind:'Rect',properties:{fill:{Text:'#CCEEDD'}}}}}});
 else if(mode===13)themed=themed.update_elements({complete:false,elements:{'axis.text.theta':{Element:{kind:'Text',properties:{colour:{Text:'#CC2200'},size:{Number:14}}}}}});
 if(mode===14)themed=c.theme().reference_preset('Test',{base_family:'Fixture Font'}).fonts([{family:'Fixture Font',face:'plain',font:{id:'1',revision:'0',kind:'Font',byte_len:String(fs.statSync(path.join(ROOT,'fixtures/capability/fonts/NotoSans-Regular.ttf')).size)},weight:400}]).update_elements({complete:false,elements:{'axis.text.x':{Element:{kind:'Text',properties:{angle:{Number:35}}}}}});
 if(mode===15)themed=themed.update_elements({"complete": false, "elements": {"legend.frame": {"Element": {"kind": "Rect", "properties": {"fill": "Missing", "colour": {"Text": "red"}}}}, "legend.ticks": {"Element": {"kind": "Line", "properties": {"colour": {"Text": "#00AA55"}, "linewidth": {"Number": 1.0}}}}, "legend.title.position": {"Value": {"Text": "left"}}, "legend.position": {"Value": {"Text": "bottom"}}}});
 if(mode===12)themed=themed.update_elements({"complete": false, "elements": {"panel.widths": {"Value": {"Unit": [{"value": 1.0, "unit": "null"}, {"value": 3.0, "unit": "null"}]}}, "strip.placement": {"Value": {"Text": "outside"}}, "strip.clip": {"Value": {"Text": "off"}}, "legend.box": {"Value": {"Text": "horizontal"}}, "legend.box.just": {"Value": {"Text": "top"}}, "legend.spacing.x": {"Value": {"Unit": [{"value": 6.0, "unit": "mm"}]}}, "legend.title.position": {"Value": {"Text": "left"}}, "legend.key.spacing.x": {"Value": {"Unit": [{"value": 2.0, "unit": "mm"}]}}}});
 const context=new c.ThemeContext(themed),captured=context.get();context.update({complete:false,elements:{}});context.set(captured).dispose();context.replace({complete:false,elements:{}});themed=context.get();context.dispose();captured.dispose();
 let builder=c.plot(data).profile('Ggplot2_4_0_3').aes(c.aes().x('x').y('y')).layer(c.line()).layer(mode===12?c.points().aes(c.aes().size("x")):c.points()).title(c.title(mode===14?'Thème • Δοκιμή • Пример':'Reference theme')).subtitle(c.subtitle('Inheritance and physical controls')).caption(c.caption('Explicit shared text service')).theme(themed);
 if(mode===12)builder=builder.aes(c.aes().x("x").y("y").color("g").color_scale("groups")).scale(c.color_discrete("groups").domain(["A","B"])).facet(c.facet_wrap("g").columns(2).reference({}));
 else if(mode===13)builder=builder.coordinate({Radial:{}});
 if(mode===14)builder=builder.layer(c.points().text_defaults().text_label("g"));
 if(mode===15)builder=builder.aes(c.aes().x("x").y("y").color("x").color_scale("values")).scale(c.color_mapped("values",{"training": "Eligible", "function": {"Interpolated": {"normalization": {"Sequential": {"family": "Linear", "domain": [1.0, 4.0], "clamp": false}}, "output": {"Interpolate": {"operation": "GgplotPalette", "spec": {"Gradient": {"colors": ["#112244", "#FFCC22"], "values": [0.0, 1.0]}}}}, "unknown": {"kind": "Missing"}}}, "ggplot": {"Continuous": {"limits": [1.0, 4.0], "empty_population": false, "nonfinite_population": false, "oob": "Censor"}}, "guide": {"Colorbar": {"breaks": [1.0, 2.0, 3.0, 4.0]}}}));
 const p=builder.build(),wire=p.to_json(),restored=c.Plot.from_json(wire),request=output.request(restored,c.export_options(600,360).dpi(144)),frame=request.prepare(),scene=frame.scene();
 const originalRequest=output.request(p,c.export_options(600,360).dpi(144)),originalFrame=originalRequest.prepare();assert.deepEqual(originalFrame.scene(),scene);originalFrame.dispose();originalRequest.dispose();
 fs.writeFileSync(path.join(out,`theme-${mode}.plot.json`),wire);fs.writeFileSync(path.join(out,`theme-${mode}.scene.json`),JSON.stringify(scene));for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`theme-${mode}.${fmt}`),frame.export(fmt));
 if(mode===14){for(const dpi of [300,600])for(const text of ['preserve','outline']){const variantRequest=output.request(restored,c.export_options(600,360).dpi(dpi).text(text)),variant=variantRequest.prepare();assert.deepEqual(variant.scene(),scene);for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`theme-${mode}.${text}-${dpi}.${fmt}`),variant.export(fmt));variant.dispose();variantRequest.dispose();}}
 frame.dispose();request.dispose();restored.dispose();p.dispose();data.dispose();
}
output.dispose();console.log('PASS WASM theme controls: sixteen authors, 60 publications including text/outline at300/600dpi.');
