// GG2-03: typed endpoint helpers through actual WASM and the common scale engine.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs'));
const out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const fixture=process.argv.includes('--named-limits')?'named-limit-dispatch.json':'scale-limit-helpers.json';
const cases=JSON.parse(fs.readFileSync(path.join(ROOT,'fixtures/parity/ggplot2',fixture))).cases;
const output=new c.Output(fs.readFileSync(path.join(ROOT,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,640).dpi(96).basis('current'),records=[];
function temporal(t){return ['date','datetime'].includes(t.family);}
function dataFor(t,values=t.inputs){const v=temporal(t)?c.timestamps(values.map(v=>BigInt(Math.round(v*86400000))),'ms','UTC'):c.column(t.family==='character'?values.map(String):values,{kind:t.family==='character'?'category':'float64'});return c.Data.columns({v,i:values.map((_,i)=>i+1)},{keys:values.map((_,i)=>i+1)});}
function axisFor(t){const v=t.authored,limits=temporal(t)?{[t.family==='date'?'Date':'Datetime']:v.map(v=>v===null?null:{Timestamp:{value:String(v*86400),unit:'Seconds'}})}:t.family==='character'?{Discrete:v.map(v=>v===null?'Null':{Text:String(v)})}:{Numeric:v};return (t.axis==='x'?c.xlim(limits):c.ylim(limits)).range(t.axis==='x'?100:540,t.axis==='x'?540:100).guide_geometry({labels:'Preserve'});}
function build(t,d,origin){const v=temporal(t)?{field:'v',origin:String(origin)}:'v',mapping=c.aes().x(t.axis==='x'?v:'i').y(t.axis==='y'?v:'i');let p=c.plot(d).profile('Ggplot2_4_0_3').aes(mapping).layer(c.points().name('marks'));return (t.axis==='x'?p.x_axis(axisFor(t)).y_axis(c.y_axis().visible(false)):p.y_axis(axisFor(t)).x_axis(c.x_axis().visible(false))).build();}
function checked(t,chart,frame,expected=true){const scene=frame.scene(),points=t.inputs.map(()=>null);for(let i=0;i<scene.items.length;i++){const item=scene.items[i],targets=scene.targets[i];if(targets.length&&item.primitive.Point){assert.equal(targets.length,1);assert(targets[0].Source);points[Number(targets[0].Source.key)-1]=(t.axis==='x'?item.primitive.Point.center[t.axis]-100:540-item.primitive.Point.center[t.axis])/440;}}
 const ticks=frame.guides().guides.find(g=>g.spec.side===(t.axis==='x'?'Bottom':'Left')).ticks;
 if(expected){points.forEach((v,i)=>{const w=t.result.point_positions[i];assert(v===null&&w===null||v!==null&&w!==null&&Math.abs(v-w)<=1e-12,JSON.stringify({t,points}));});const wanted=t.result.labels.map((label,i)=>[t.result.break_positions[i],label===null?'NA':label]).filter(v=>v[0]!==null).sort((a,b)=>a[0]-b[0]);const actual=ticks.map(tick=>[(t.axis==='x'?tick.position-100:540-tick.position)/440,tick.label]).sort((a,b)=>a[0]-b[0]);assert.equal(actual.length,wanted.length);actual.forEach((v,i)=>{assert.equal(v[1],wanted[i][1],JSON.stringify(t));assert(Math.abs(v[0]-wanted[i][0])<=1e-12,JSON.stringify({t,actual,wanted}));});}

 return {points,ticks,domains:chart.semantics().layers[0].domains};
}
for(const [index,t] of cases.entries())for(const origin of (temporal(t)&&!t.result.error?[0,123456789]:[0])){const owned=[];try{const d=dataFor(t);owned.push(d);let p;try{p=build(t,d,origin);owned.push(p);}catch(error){assert(t.result.error&&error.code,JSON.stringify({t,error}));records.push({index,origin,rejected:error.code});continue;}assert(!t.result.error,JSON.stringify(t));const wire=p.to_json();assert.equal(JSON.parse(wire).version,temporal(t)?43:t.family==='numeric'?31:22);const restored=c.Plot.from_json(wire);owned.push(restored);assert.equal(restored.to_json(),wire);let edit=restored.edit();owned.push(edit);edit=t.axis==='x'?edit.x_axis(axisFor(t)):edit.y_axis(axisFor(t));owned.push(edit);const edited=edit.build();owned.push(edited);let chart,frame,held;
 for(const [state,current] of [['original',p],['restored',restored],['edited',edited]]){chart=current.chart();const request=output.request(current,options);frame=request.prepare();owned.push(chart,request,frame);held=frame.scene();records.push({index,origin,state,...checked(t,chart,frame)});if(state==='original'&&origin===0&&['ascending','descending'].includes(t.mode))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.family}-${t.axis}-${t.mode}.${fmt}`),frame.export(fmt));}
 if(temporal(t)&&t.mode==='lower_missing'){const replacement=dataFor(t,[-2,0,2,4,6]);owned.push(replacement);let tb=chart.transaction();owned.push(tb);tb=tb.replace(d,replacement);owned.push(tb);const tx=tb.build();owned.push(tx);assert('Applied' in chart.commit(tx));const fresh=build(t,replacement,origin),batch=fresh.chart(),ar=output.request(chart,options),br=output.request(batch,options),af=ar.prepare(),bf=br.prepare();owned.push(fresh,batch,ar,br,af,bf);const actual=checked(t,chart,af,false);assert.deepEqual(actual,checked(t,batch,bf,false));assert.deepEqual(af.export('png'),bf.export('png'));assert.deepEqual(frame.scene(),held);assert.equal(p.to_json(),wire);records.push({index,origin,state:'replaced',...actual});}
}finally{for(const obj of owned.reverse())obj.dispose();}}
// Exact endpoint wire values remain decimal strings above the Number boundary.
{const owned=[];try{const epoch=9007199254740991n;
 const exactData=values=>c.Data.columns({v:c.timestamps(values.map(v=>epoch+BigInt(v)),'ns','UTC')},{keys:values.map((_,i)=>i+1)});
 const exactPlot=(data,endpoint)=>c.plot(data).profile('Ggplot2_4_0_3').aes(c.aes().x({field:'v',origin:String(epoch)}).y(1)).layer(c.points()).x_axis(c.x_axis().scale(c.scale_utc()).temporal_limits([null,{Timestamp:{value:String(endpoint),unit:'Nanoseconds'}}])).build();
 const d=exactData([-2,0,2,4]),p=exactPlot(d,epoch+2n),wire=p.to_json(),restored=c.Plot.from_json(wire);owned.push(d,p,restored);assert.equal(restored.to_json(),wire);let chart,snapshot;
 for(const [state,current] of [['original',p],['restored',restored]]){chart=current.chart();owned.push(chart);snapshot=chart.semantics();const layer=snapshot.layers[0];assert.deepEqual(layer.domains.x,{minimum:-2,maximum:2});assert.equal(layer.targets.length,3);records.push({index:'exact_ns',state,domains:layer.domains,count:layer.targets.length});}
 const replacement=exactData([-4,0,4]);owned.push(replacement);let tb=chart.transaction();owned.push(tb);tb=tb.replace(d,replacement);owned.push(tb);const tx=tb.build();owned.push(tx);assert('Applied' in chart.commit(tx));const layer=chart.semantics().layers[0];assert.deepEqual(layer.domains.x,{minimum:-4,maximum:0});assert.equal(layer.targets.length,2);assert.deepEqual(snapshot.layers[0].domains.x,{minimum:-2,maximum:2});assert.equal(p.to_json(),wire);records.push({index:'exact_ns',state:'replaced',domains:layer.domains,count:layer.targets.length});
 for(const delta of [9007199254740993n,-9007199254740993n]){assert.throws(()=>{const bad=exactPlot(d,epoch+delta),bc=bad.chart();owned.push(bad,bc);bc.semantics();},error=>{assert.equal(error.code,'CHART_PRECISION_LOSS');records.push({index:'exact_ns',delta:String(delta),rejected:error.code});return true;});}
}finally{for(const obj of owned.reverse())obj.dispose();}}

assert.equal(records.length,181);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));options.dispose();output.dispose();console.log('PASS',records.length,'typed helper states');
