'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const registry=c.ExtensionRegistry.example(),records=[],output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),options=c.export_options(640,360).dpi(96).basis('current');
const cases=JSON.parse(fs.readFileSync(path.join(root,'fixtures/parity/ggplot2/positional-pipeline-temporal.json'))).cases,units=[['s',1n],['ms',1000n],['us',1000000n],['ns',1000000000n]];
const configurations=t=>t.family==='duration'?units.slice(0,1):units,factor=(t,m)=>m*(t.family==='date'?86400n:1n),origin=(t,m)=>t.family==='duration'?0n:BigInt(t.origin)*factor(t,m),mapping=(t,m)=>t.family==='duration'?'v':{field:'v',origin:String(origin(t,m))};
function dataFor(t,unit,m){const values=t.inputs,i=t.kind==='mean'?t.groups:values.map((_,i)=>i+1),v=t.family==='duration'?c.column(values,{kind:'float64'}).nullable(true):c.timestamps(values.map(v=>BigInt(v??0)*factor(t,m)),unit,'UTC').validity(values.map(v=>v!==null));return c.Data.columns({v,i:c.column(i.map(BigInt),{kind:'int64'})});}
function layer(t,m){const p=c.points().name('marks');return t.kind==='mean'?p.stat(c.summary().x(mapping(t,m)).group('i')).after_stat(c.stat_aes().x(1).y('Mean')):p;}
function build(t,d,m){let scale={duration:c.scale_duration,date:c.scale_date,datetime:c.scale_utc}[t.family]();if(t.limit_mode==='explicit')scale=t.family==='duration'?scale.domain(t.origin+1,t.origin+10):scale.time_domain(BigInt(t.origin+1)*factor(t,m),BigInt(t.origin+10)*factor(t,m));const axis=(t.axis==='x'?c.x_axis():c.y_axis()).scale(scale).guide_geometry({labels:'Preserve'}).oob_function({operation:{id:'example.scale_vector',version:'1'},parameters:{mode:t.mode==='default'?'default':'oob_'+t.mode}}),draft=c.plot(d).with_registry(registry).profile('Ggplot2_4_0_3').aes(c.aes().x(t.axis==='x'?mapping(t,m):'i').y(t.axis==='x'?'i':mapping(t,m))).layer(layer(t,m));return (t.axis==='x'?draft.x_axis(axis):draft.y_axis(axis)).build();}
const scalar=v=>v&&typeof v==='object'?v.number:v,absolute=(t,m,v)=>t.family==='duration'?v:Number(origin(t,m))/Number(factor(t,m))+v/Number(factor(t,m));
function compare(a,b){if(typeof a==='number'&&typeof b==='number')assert.ok(Math.abs(a-b)<5e-14,`${a} != ${b}`);else if(Array.isArray(a)&&Array.isArray(b)){assert.equal(a.length,b.length);a.forEach((v,i)=>compare(v,b[i]));}else assert.deepEqual(a,b);}
function check(t,chart,frame,m){const semantics=chart.semantics(),state=semantics.layers[0],positions=state.point_positions,dim=t.axis==='x'?0:1;compare(positions.map(p=>absolute(t,m,scalar(p[dim]))),t.result.mapped.filter(v=>v!==null));compare(positions.map(p=>scalar(p[1-dim])),t.kind==='mean'?positions.map(()=>1):t.result.mapped.flatMap((v,i)=>v===null?[]:[i+1]));const limits=semantics.positional_limits[String(dim)];compare(limits.map(v=>absolute(t,m,scalar(v))),t.result.limits);const ticks=frame.guides().guides.find(g=>g.spec.side===(dim===0?'Bottom':'Left')).ticks,expected=t.result.breaks.flatMap((v,i)=>typeof v==='number'?[[v,t.result.labels[i]]]:[]);compare(ticks.map(t=>t.label),expected.map(([,label])=>label??''));function tickNumber(v){if('Number' in v)return absolute(t,m,v.Number);const stamp=v.Timestamp;return Number(stamp.value)/({Seconds:1,Milliseconds:1000,Microseconds:1e6,Nanoseconds:1e9}[stamp.unit]*(t.family==='date'?86400:1));}compare(ticks.map(t=>tickNumber(t.value)),expected.map(([v])=>v));return {positions,limits,ticks,domains:state.domains};}
function sample(t,unit){return unit===(t.family==='duration'?'s':'ms')&&t.population==='ordinary'&&((t.kind==='point_x'&&((t.limit_mode==='explicit'&&t.mode==='default')||(t.limit_mode==='automatic'&&t.mode==='index')))||(t.kind==='mean'&&t.limit_mode==='automatic'&&['reverse','index'].includes(t.mode)));}
for(const [index,t] of cases.entries())for(const [unit,m] of configurations(t)){
 const owned=[];
 try{
  const d=dataFor(t,unit,m);owned.push(d);const p=build(t,d,m);owned.push(p);const wire=p.to_json();assert.equal(JSON.parse(wire).version,40);const restored=c.Plot.from_json(wire,registry);owned.push(restored);assert.equal(restored.to_json(),wire);
  for(const state of ['original','edited']){const current=state==='original'?restored:restored.edit().layer('marks',layer(t,m)).build();if(current!==restored)owned.push(current);const chart=current.chart();owned.push(chart);const request=output.request(current,options);owned.push(request);const frame=request.prepare();owned.push(frame);assert.ok(!t.result.error,JSON.stringify(t));records.push({index,unit,state,...check(t,chart,frame,m)});if(state==='original'&&sample(t,unit))for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`${t.family}-${t.kind}-${t.limit_mode}-${t.mode}.${fmt}`),frame.export(fmt));}
 }catch(error){assert.ok(error instanceof c.ChartError&&t.result.error,`${index}/${unit}: ${error.stack}`);assert.ok(['CHART_SCHEMA_CONFLICT','CHART_NUMERICAL_DOMAIN'].includes(error.code));records.push({index,unit,error:error.code});}
 finally{for(const obj of owned.reverse())obj.dispose();}
}
assert.equal(records.length,1691);
for(const family of ['duration','date','datetime'])for(const kind of ['point_x','mean']){
 const selected=Object.fromEntries(cases.filter(t=>t.family===family&&t.kind===kind&&t.limit_mode==='explicit'&&t.mode==='index').map(t=>[t.population,t]));
 for(const [unit,m] of configurations(selected.ordinary)){
  const owned=[];
  try{
   const original=dataFor(selected.ordinary,unit,m);owned.push(original);const p=build(selected.ordinary,original,m);owned.push(p);const chart=p.chart();owned.push(chart);const wire=p.to_json(),request=output.request(p,options);owned.push(request);const held=request.prepare();owned.push(held);const scene=held.scene();
   for(const population of ['missing','empty']){const t=selected[population],replacement=dataFor(t,unit,m);owned.push(replacement);const tx=chart.transaction();owned.push(tx);const builder=tx.replace(original,replacement);owned.push(builder);const update=builder.build();owned.push(update);assert.ok('Applied' in chart.commit(update));const fresh=build(t,replacement,m);owned.push(fresh);const batch=fresh.chart();owned.push(batch);const ar=output.request(chart,options);owned.push(ar);const af=ar.prepare();owned.push(af);const br=output.request(batch,options);owned.push(br);const bf=br.prepare();owned.push(bf);const actual=check(t,chart,af,m);assert.deepEqual(actual,check(t,batch,bf,m));assert.equal(p.to_json(),wire);assert.deepEqual(held.scene(),scene);records.push({family,kind,unit,replacement:population,...actual});}
  }finally{for(const obj of owned.reverse())obj.dispose();}
 }
}
assert.equal(records.length,1727);fs.writeFileSync(path.join(out,'records.json'),JSON.stringify(records));output.dispose();options.dispose();registry.dispose();console.log('PASS',records.length,'temporal positional vector host states');
