'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'../..'),c=require(path.join(path.resolve(process.argv[2]),'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
let draft=c.plot(c.Data.columns({x:[0,8],y:[0,8]})).aes(c.aes().x('x').y('y')).xAxis(c.xAxis().scale(c.scaleLinear().domain(0,8)).visible(false)).yAxis(c.yAxis().scale(c.scaleLinear().domain(0,8)).visible(false)).title(c.title('Arcs and pies / corners, padding and source identity'));
const cases=[['Quarter',0,48,0,Math.PI/2,0,0,null],['Annulus',27,48,0,Math.PI*2,0,0,null],['Rounded',20,48,.1,2.3,9,0,null],['Padded',20,48,0,1.2,4,.18,60],['Reverse',20,48,2.8,-1.2,6,.1,null],['Swapped radii',48,20,0,4.9,5,0,null],['Tiny wedge',20,48,0,.08,20,0,null],['Signed inner',-10,48,0,1.6,0,0,null]];
for(const [i,[name,inner,outer,start,end,corner,pad,padRadius]]of cases.entries()){
 const x=i%4*2+1,y=6.5-Math.floor(i/4)*2.3,data=c.Data.columns({x:[x],y:[y]},{name:`arc-${i}`}),parameters={datum:{inner_radius:inner,outer_radius:outer,start_angle:start,end_angle:end,pad_angle:pad},corner_radius:corner,pad_radius:padRadius};
 draft=draft.layer(c.shapeArc().name(`arc-${i}`).data(data).arcParameters(parameters).color('#2162a8')).layer(c.labels().id(`arc-label-${i}`).at(x-.8,y+1.1).text(name).style(c.textStyle().size(.95)));
}
for(const [i,[name,inner,pad,corner,start,end,order]]of [['Pie / source order',0,0,0,0,Math.PI*2,'Input'],['Donut / descending',32,.06,7,.4,.4+Math.PI*2,'ValuesDescending']].entries()){
 const x=2+i*4,data=c.Data.columns({x:[x,x,x,x],y:[1.45,1.45,1.45,1.45],weight:[1,2,3,2],slice:['A','B','C','D']},{name:`pie-${i}`,keys:[9007199254741001n,9007199254741003n,9007199254741005n,9007199254741007n]});
 const layer=c.shapePie().name(`pie-${i}`).data(data).aes(c.aes().color('slice').colorScale('slices')).pieOrder(order).pieAngles({start_angle:start,end_angle:end,pad_angle:pad}).shapeValue('PieValue','weight').shapeValue('InnerRadius',inner).shapeValue('OuterRadius',65).shapeValue('CornerRadius',corner);
 draft=draft.layer(layer).layer(c.labels().id(`pie-label-${i}`).at(x-1,2.75).text(name).style(c.textStyle().size(.95)));
}
const plot=draft.scale(c.colorDiscrete('slices').palette(['#2162a8','#5b9cce','#e4ad4b','#b55037'])).legend(c.legend().scale('slices').title('Source slice')).build();fs.writeFileSync(path.join(out,'figure.plot.json'),plot.toJson());const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),requests=[300,600].map(dpi=>[dpi,output.request(plot,c.exportOptions(680,640).dpi(dpi))]);plot.free();
for(const [dpi,request]of requests){const frame=request.prepare(),scene=frame.scene();assert.equal(scene.items.filter(i=>'ShapePath'in i.primitive).length,16);scene.items.forEach((item,i)=>{if('ShapePath'in item.primitive){assert.equal(item.primitive.ShapePath.anchors.length,1);assert.equal(scene.targets[i].length,1);}});fs.writeFileSync(path.join(out,`figure-${dpi}.scene.json`),JSON.stringify(scene,null,2));for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(out,`figure-${dpi}.${fmt}`),frame.export(fmt));frame.free();request.free();}
console.log('PASS WASM arc/pie gallery: eight arcs and two four-slice compositions at 300/600 DPI; immutable exports after plot disposal.');
