'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),root=path.resolve(__dirname,'../..'),c=require(path.resolve(process.argv[2],'authoring.cjs')),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const output=new c.Output(fs.readFileSync(path.join(root,'fixtures/capability/fonts/NotoSans-Regular.ttf'))),offsets=['None','Expand','Diverging','Silhouette','Wiggle'];
for(const preset of ['Editorial','Terminal','Grayscale']){
 const folder=path.join(out,preset);fs.mkdirSync(folder,{recursive:true});const rows=[];
 for(const [oi,offset]of offsets.entries())for(const [kind,form]of ['Area','Bars'].entries())for(let sample=0;sample<6;sample++)for(const [g,name]of ['A','B','C'].entries()){if(sample===2&&g===1)continue;rows.push([sample,sample===3&&g===2?-2:(sample+2*g)%4+1,name,offset,form,2*oi+kind,9007199254741001n+BigInt(oi*100+kind*30+sample*3+g)]);}
 const data=c.Data.columns({x:new Float64Array(rows.map(r=>r[0])),y:new Float64Array(rows.map(r=>r[1])),group:c.categorical(rows.map(r=>r[2])),offset:c.categorical(rows.map(r=>r[3])),form:c.categorical(rows.map(r=>r[4])),slot:rows.map(r=>r[5])},{keys:rows.map(r=>r[6]),name:'stacks'});
 let draft=c.plot(data).aes(c.aes().x('x').x2('x').y('y').y2(0).group('group').color('group')).theme(c.theme().preset(preset)).title(c.title(`Stack offsets / InsideOut / ${preset}`)).subtitle(c.subtitle('Signed heights, a missing sample, and explicit zero filling')).facet(c.facetGrid('offset','form').freeY(true).gap(12)).xAxis(c.xAxis().scale(c.scaleLinear().domain(-.5,5.5))).scale(c.colorDiscrete('group').domain(['A','B','C'])).legend(c.legend().scale('group').title('Series'));
 for(const [oi,offset]of offsets.entries())for(let kind=0;kind<2;kind++){const layer=kind===0?c.shapeArea():c.bars().width(15),slot=2*oi+kind;draft=draft.layer(layer.name(`${offset}-${kind}`).filter(c.filter('slot').minimum(slot).maximum(slot)).position(c.shapeStack(['A','B','C']).stackOrder('InsideOut').stackOffset(offset).stackMissing('Zero')));}
 const p=draft.build();fs.writeFileSync(path.join(folder,'figure.plot.json'),p.toJson());const requests=[300,600].map(dpi=>[dpi,output.request(p,c.exportOptions(600,740).dpi(dpi))]);p.free();for(const [dpi,request]of requests){const f=request.prepare(),scene=f.scene();assert.equal(scene.items.filter(i=>'ShapePath'in i.primitive).length,15);assert.equal(scene.targets.flat().length,170);scene.items.forEach((i,n)=>{if('ShapePath'in i.primitive)assert.equal(i.primitive.ShapePath.anchors.length,scene.targets[n].length);});fs.writeFileSync(path.join(folder,`figure-${dpi}.scene.json`),JSON.stringify(scene,null,2));for(const fmt of ['svg','pdf','png'])fs.writeFileSync(path.join(folder,`figure-${dpi}.${fmt}`),f.export(fmt));f.free();request.free();}
}
console.log('PASS WASM stack gallery: five offsets, InsideOut rank, sparse areas/bars, 170 actual targets, three themes and immutable 300/600 DPI outputs.');
