"""Adapt literal tables from pinned upstream source, independently of oracle outputs."""
from pathlib import Path
import re,shutil,sys,subprocess
ROOT=Path(__file__).resolve().parents[2]
source=ROOT/'tools/reference/node/node_modules/d3-scale-chromatic/src'
out=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT/'crates/chart-core/src/scales/chromatic'
out.mkdir(parents=True,exist_ok=True)
exports=(source/'index.js').read_text();schemes={}
for line in exports.splitlines():
 match=re.search(r'(?:default as |scheme as )scheme(\w+).*from "([^"]+)"',line)
 if not match:continue
 name,file=match.groups();text=(source/file).read_text()
 arrays=[s for s in re.findall(r'"([a-f0-9]+)"',text) if len(s)>=6 and len(s)%6==0]
 fixed='/categorical/' in file
 schemes[name]=[(None if fixed else len(s)//6,[int(s[i:i+6],16) for i in range(0,len(s),6)]) for s in arrays]
assert len(schemes)==38 and sum(map(len,schemes.values()))==218
lookup={}
for name,packed in re.findall(r'export (default|var \w+ =) ramp\(colors\("([0-9a-f]+)"\)\)',(source/'sequential-multi/viridis.js').read_text()):
 id='Viridis' if name=='default' else name.split()[1].title()
 lookup[id]=[int(packed[i:i+6],16) for i in range(0,len(packed),6)]
assert len(lookup)==4 and all(len(v)==256 for v in lookup.values())
ramps=sorted(re.findall(r'(?:default as |warm as |cool as |magma as |inferno as |plasma as )interpolate(\w+)',exports))
assert len(ramps)==38
lines=['//! Literal data adapted from d3-scale-chromatic 3.1.0; see LICENSE.','//! Generated by tools/reference/extract_chromatic.py from pinned source, not oracle samples.']
for typ,names in [('SchemeId',sorted(schemes)),('InterpolatorId',ramps)]:
 lines+=['/// Stable built-in catalog identity.','#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]',f'pub enum {typ} {{']
 for name in names:lines +=[f'    /// The pinned {name} catalog entry.',f'    {name},']
 lines+=['}',f'impl {typ} {{','    /// Every supported catalog identity, in stable name order.',f'    pub const ALL: [Self; {len(names)}] = ['+', '.join('Self::'+n for n in names)+'];','    /// Stable serialized name.',"    pub fn name(self) -> &'static str { match self {"]
 for name in names:lines +=[f'        Self::{name} => "{name}",']
 lines+=['    }}','}',f'impl std::str::FromStr for {typ} {{','    type Err = crate::Diagnostic;', '    fn from_str(name: &str) -> Result<Self, Self::Err> { match name {']
 for name in names:lines +=[f'        "{name}" => Ok(Self::{name}),']
 lines+=['        _ => Err(super::error(crate::DiagnosticCode::Validation, format!("Unknown chromatic identity: {name}"))),','    }}','}']
lines+=['pub(super) fn table(id: SchemeId, size: Option<usize>) -> Option<&\'static [u32]> { match (id, size) {']
for name,arrays in sorted(schemes.items()):
 for size,array in arrays:lines+=[f'    (SchemeId::{name}, '+('None' if size is None else f'Some({size})')+') => Some(&['+', '.join(f'0x{x:06x}' for x in array)+']),']
lines+=['    _ => None,','}}',"pub(super) fn sizes(id: SchemeId) -> &'static [usize] { match id {"]
for name,arrays in sorted(schemes.items()):lines+=[f'    SchemeId::{name} => &['+', '.join(str(len(a)) for _,a in arrays)+'],']
lines+=['}}','pub(super) fn lookup(id: InterpolatorId) -> Option<&\'static [u32]> { match id {']
for name,array in sorted(lookup.items()):lines+=[f'    InterpolatorId::{name} => Some(&['+', '.join(f'0x{x:06x}' for x in array)+']),']
lines+=['    _ => None,','}}']
(out/'data.rs').write_text('\n'.join(lines)+'\n')
subprocess.run(['rustfmt','--edition','2024',str(out/'data.rs')],check=True)
shutil.copy2(source.parent/'LICENSE',out/'LICENSE')
print(f'PASS extracted 218 scheme arrays and four 256-color tables from pinned source into {out}')
