"""Retain the R named-color facts as a sorted, allocation-free runtime lookup table."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
source = json.loads((root / 'fixtures/parity/ggplot2/color-names.json').read_text())
rows = sorted(source['catalog'], key=lambda row: row['input'])
assert len(rows) == 657 and len({row['input'] for row in rows}) == 657
lines = ['// R 4.6.1 grDevices named-color facts; generated by tools/reference/r/color_name_records.py.',
         'pub(super) const NAMES: &[(&str, u32)] = &[']
for row in rows:
    red, green, blue, alpha = row['rgba']
    assert alpha == 255
    lines.append(f'    ("{row["input"]}", 0x{red:02x}{green:02x}{blue:02x}),')
lines.append('];')
(root / 'crates/chart-core/src/color/r_names.rs').write_text('\n'.join(lines) + '\n')
print('PASS 657 R named-color records')
