# GG13 independent coordinate protocol and draw inventory; no core implementation implied.
library(ggplot2);library(grid)
stopifnot(as.character(getRversion())=='4.6.1',as.character(packageVersion('ggplot2'))=='4.0.3')
pdf(file=tempfile(fileext='.pdf'),width=8,height=6)
cases=list()
numfields=function(x){x[vapply(x,function(v)is.atomic(v)&&!is.function(v),logical(1))]}
capture=function(name,p,controls=list()) {
 entry=list(name=name,controls=controls);warnings=character()
 withCallingHandlers(tryCatch({
  b=ggplot_build(p);co=b$layout$coord;entry$build=list(ok=TRUE);entry$data=b$data
  entry$coord=list(class=class(co),clip=co$clip,is_linear=co$is_linear(),aspect=lapply(b$layout$panel_params,co$aspect))
  entry$panels=lapply(b$layout$panel_params,numfields)
  entry$projected=lapply(b$data,function(d){lapply(split(d,d$PANEL),function(v)co$transform(v,b$layout$panel_params[[as.integer(v$PANEL[1])]]))})
  entry$munch=lapply(b$data,function(d){lapply(split(d,d$PANEL),function(v)tryCatch(ggplot2:::coord_munch(co,v,b$layout$panel_params[[as.integer(v$PANEL[1])]],segment_length=.01),error=function(e)list(error=conditionMessage(e))))})
  entry$draw=tryCatch({g=ggplot_gtable(b);grid.newpage();grid.draw(g);list(ok=TRUE,layout=g$layout,widths=as.character(g$widths),heights=as.character(g$heights))},error=function(e)list(ok=FALSE,error=conditionMessage(e)))
 },error=function(e)entry$build<<-list(ok=FALSE,error=conditionMessage(e))),warning=function(w){warnings<<-c(warnings,conditionMessage(w));invokeRestart('muffleWarning')})
 entry$warnings=warnings;cases[[length(cases)+1L]]<<-entry
}
d=data.frame(x=c(1,2,4,8),y=c(1,4,2,8));p=ggplot(d,aes(x,y))+geom_path()+geom_point()
capture('cartesian',p+coord_cartesian())
capture('fixed-ratio-one',p+coord_fixed(ratio=1))
capture('fixed-ratio-two',p+coord_fixed(ratio=2))
capture('cartesian-zoom',p+coord_cartesian(xlim=c(2,4),ylim=c(2,4)))
capture('cartesian-no-expand',p+coord_cartesian(expand=FALSE))
capture('cartesian-clip-off',p+coord_cartesian(xlim=c(2,4),clip='off'))
capture('flip-interval',ggplot(transform(d,ymin=y-1,ymax=y+1),aes(x,y,ymin=ymin,ymax=ymax))+geom_errorbar()+coord_flip())
capture('transform-log',p+coord_transform(x='log10',y='sqrt'))
capture('transform-reverse',p+coord_transform(x='reverse'))
capture('scale-log-stat-summary',ggplot(d,aes(x,y))+stat_summary_bin(fun=mean,bins=2)+scale_x_log10())
capture('coord-log-stat-summary',ggplot(d,aes(x,y))+stat_summary_bin(fun=mean,bins=2)+coord_transform(x='log10'))
capture('secondary-transform',p+scale_y_continuous(sec.axis=sec_axis(~.*2+1))+coord_transform(y='sqrt'))
capture('secondary-flip',p+scale_y_continuous(sec.axis=sec_axis(~.*2+1))+coord_flip())
rad=data.frame(x=c(0,1,2,3,4),y=c(1,2,3,2,1));rp=ggplot(rad,aes(x,y))+geom_path()+geom_point()
capture('polar-x',rp+coord_polar(theta='x'))
capture('polar-y',rp+coord_polar(theta='y'))
capture('polar-start-direction',rp+coord_polar(start=pi/2,direction=-1))
capture('polar-bars',ggplot(rad,aes(x,y))+geom_col()+coord_polar())
capture('polar-ribbon',ggplot(transform(rad,ymin=y-.4,ymax=y+.4),aes(x,ymin=ymin,ymax=ymax))+geom_ribbon()+coord_polar())
capture('radial-full',rp+coord_radial())
capture('radial-partial-hole',rp+coord_radial(start=pi/4,end=pi*1.5,inner.radius=.3))
capture('radial-reverse',rp+coord_radial(reverse='thetar',r.axis.inside=TRUE))
capture('radial-rotated-labels',ggplot(transform(rad,label=letters[1:5]),aes(x,y,label=label))+geom_text()+coord_radial(rotate.angle=TRUE))
capture('radial-secondary-guides',rp+coord_radial(inner.radius=.4)+guides(theta=guide_axis_theta(),theta.sec=guide_axis_theta(),r=guide_axis(),r.sec=guide_axis()))
capture('polar-seam',ggplot(data.frame(x=c(.01,.99),y=c(1,1)),aes(x,y))+geom_path()+scale_x_continuous(limits=c(0,1),expand=c(0,0))+coord_polar())
jsonlite::write_json(list(reference='ggplot2 4.0.3 / R 4.6.1',cases=cases),'fixtures/parity/ggplot2/coordinate-controls.json',auto_unbox=TRUE,pretty=TRUE,digits=17,na='null',null='null')
dev.off();cat('Captured',length(cases),'GG13 coordinate cases\n')
