"""Emit immutable reference-only palette tables; shared families retain core recipes."""
import json,subprocess
from pathlib import Path
root=Path(__file__).resolve().parents[3]
palettes=json.loads((root/'fixtures/parity/ggplot2/named-palette-catalog.json').read_text())['palettes']
lines=['// Generated by tools/reference/r/extract_named_palettes.py; do not edit.', '// scales 1.4.0 registry / R 4.6.1 grDevices palette outputs; see docs/adr/018-scale-compatibility-and-resources.md.', 'use super::NamedPalette;', 'use crate::scales::chromatic::{SchemeId, ggplot::ViridisOption};', 'pub(super) const PALETTES: &[(&str, NamedPalette)] = &[']
for name,p in sorted(palettes.items()):
 kind=p['kind']
 if kind in ('gradient','manual'):
  colors=', '.join('0x'+v[1:]+('FF' if len(v)==7 else '') for v in p['colors'])
  value=f'NamedPalette::{kind.title()}(&[{colors}])'
 elif kind=='brewer':value=f"NamedPalette::Brewer(SchemeId::{p['id']})"
 elif kind=='viridis':value=f"NamedPalette::Viridis(ViridisOption::{p['option'].title()})"
 else:value=f'NamedPalette::{kind.title()}'
 lines.append(f'    ({json.dumps(name)}, {value}),')
lines.append('];')
(root/'crates/chart-core/src/scales/ggplot_named_data.rs').write_text('\n'.join(lines)+'\n')
subprocess.run(['rustfmt','--edition','2024',str(root/'crates/chart-core/src/scales/ggplot_named_data.rs')],check=True)
print('PASS',len(palettes),'named palette definitions')
