pdf(file = tempfile(fileext = ".pdf"))
stopifnot(as.character(getRversion())=='4.6.1',as.character(packageVersion('ggplot2'))=='4.0.3')
library(ggplot2)
pdf(file=tempfile(fileext='.pdf'))
enc=function(x)lapply(unname(x),function(v)if(is.na(v))NULL else v)
d=data.frame(x=1:4,y=c(1,2,1,2),g=factor(c('A','B','A','B')),v=c(1,4,9,16))
cases=list()
for(mode in c('colour','shape','size','alpha','linetype','colour_shape','size_alpha'))for(over in c(FALSE,TRUE)) {
 a=aes(x,y)
 if(mode%in%c('colour','colour_shape'))a$colour=quote(g)
 if(mode%in%c('shape','colour_shape'))a$shape=quote(g)
 if(mode%in%c('size','size_alpha'))a$size=quote(v)
 if(mode%in%c('alpha','size_alpha'))a$alpha=quote(v)
 if(mode=='linetype')a$linetype=quote(g)
 p=ggplot(d,a)+if(mode=='linetype')geom_line()else geom_point()
 if(over)p=p+guides(colour=guide_legend(override.aes=list(size=5,alpha=.5)),shape=guide_legend(override.aes=list(size=5,alpha=.5)),size=guide_legend(override.aes=list(size=5,alpha=.5)),alpha=guide_legend(override.aes=list(size=5,alpha=.5)),linetype=guide_legend(override.aes=list(size=5,alpha=.5)))
 b=ggplot_build(p);gt=ggplot_gtable(b)
 cases[[length(cases)+1]]=list(mode=mode,override=over,guides=lapply(b$plot$guides$params,function(g)list(title=g$title,key=lapply(g$key,enc),layers=lapply(g$decor,function(layer)lapply(layer$data,enc)))))
}
jsonlite::write_json(list(reference='ggplot2 4.0.3 / R 4.6.1',cases=cases),'fixtures/parity/ggplot2/legend-keys.json',auto_unbox=TRUE,pretty=TRUE,digits=17,null='null',na='null')
invisible(dev.off())
