# GG10 development-only oracle: no model dependency is adopted by this capture.
stopifnot(as.character(getRversion())=='4.6.1',as.character(packageVersion('ggplot2'))=='4.0.3')
library(ggplot2)
set.seed(20260915) # rq pfn uses sampling; retain a reproducible oracle stream.
cases=list()
capture=function(name,controls,fn){warnings=character();messages=character();result=withCallingHandlers(tryCatch(list(ok=TRUE,value=fn()),error=function(e)list(ok=FALSE,error=conditionMessage(e))),warning=function(w){warnings<<-c(warnings,conditionMessage(w));invokeRestart('muffleWarning')},message=function(m){messages<<-c(messages,conditionMessage(m));invokeRestart('muffleMessage')});cases[[length(cases)+1]]<<-list(name=name,controls=controls,result=result,warnings=warnings,messages=messages)}
built=function(p){b=ggplot_build(p);v=b$data[[1]];list(values=v[intersect(names(v),c('x','y','ymin','ymax','se','PANEL','group','quantile'))],method=if(is.character(b$plot$layers[[1]]$computed_stat_params$method))b$plot$layers[[1]]$computed_stat_params$method else if(identical(b$plot$layers[[1]]$computed_stat_params$method,stats::loess))'loess' else if(identical(b$plot$layers[[1]]$computed_stat_params$method,mgcv::gam))'gam' else if(identical(b$plot$layers[[1]]$computed_stat_params$method,stats::lm))'lm' else if(identical(b$plot$layers[[1]]$computed_stat_params$method,stats::glm))'glm' else 'function',formula=deparse(b$plot$layers[[1]]$computed_stat_params$formula))}
d=data.frame(x=as.double(0:7),y=c(1,3,4,8,8,12,12,16),w=c(1,2,1,3,0,1,2,1))
for(level in c(.8,.95,.99))capture(paste0('lm-weighted-',level),list(data=d,method='lm',formula='y~x',level=level,xseq=c(0,2,4,7)),function()built(ggplot(d,aes(x,y,weight=w))+geom_smooth(method='lm',formula=y~x,level=level,xseq=c(0,2,4,7))))
for(formula in list(y~x,y~0+x,y~x+I(x^2),y~x+I(2*x))){capture(paste0('lm-formula-',length(cases)),list(data=d,formula=deparse(formula),xseq=c(0,2,4,7)),function(){fit=lm(formula,d,weights=w);list(coefficients=coef(fit),rank=fit$rank,df=fit$df.residual,prediction=ggplot2:::predictdf(fit,c(0,2,4,7),TRUE,.95))})}
e=transform(d,y=2+3*x);capture('lm-exact-weighted',list(data=e),function()built(ggplot(e,aes(x,y,weight=w))+geom_smooth(method='lm',formula=y~x,n=5)))
for(mode in c('se-false','zoom','filter','fullrange','negative-weight','one-distinct-x')){z=d;if(mode=='negative-weight')z$w[1]=-1;if(mode=='one-distinct-x')z$x=1;capture(paste0('lm-',mode),list(data=z,mode=mode,limits=c(1,6),n=5),function(){p=ggplot(z,aes(x,y,weight=w))+geom_smooth(method='lm',formula=y~x,n=5,se=mode!='se-false',fullrange=mode=='fullrange');if(mode=='zoom')p=p+coord_cartesian(xlim=c(1,6));if(mode=='filter')p=p+scale_x_continuous(limits=c(1,6));if(mode=='fullrange')p=p+scale_x_continuous(limits=c(-2,9));built(p)})}
for(family in c('gaussian','binomial','poisson'))for(level in c(.8,.95)){
 z=d;z$y=switch(family,gaussian=d$y,binomial=c(0,0,1,0,1,1,0,1),poisson=c(0,1,1,3,2,4,5,7));fam=get(family,asNamespace('stats'))();capture(paste('glm',family,level,sep='-'),list(data=z,family=family,link=fam$link,level=level,xseq=c(0,2,4,7)),function(){fit=glm(y~x,z,weights=w,family=fam);list(coefficients=coef(fit),converged=fit$converged,iterations=fit$iter,link_prediction=predict(fit,data.frame(x=c(0,2,4,7)),type='link',se.fit=TRUE),built=built(ggplot(z,aes(x,y,weight=w))+geom_smooth(method='glm',formula=y~x,method.args=list(family=fam),level=level,xseq=c(0,2,4,7))))})
}
capture('glm-nonconverged',list(data=d,family='poisson',maxit=1),function()built(ggplot(d,aes(x,y,weight=w))+geom_smooth(method='glm',formula=y~x,method.args=list(family=poisson(),control=glm.control(maxit=1)),n=5)))
l=data.frame(x=seq(-2,2,length.out=41));l$y=sin(l$x)+.1*cos(7*l$x);l$w=1+(seq_len(nrow(l))%%3)
for(mode in c('default','span-half','degree-one','symmetric','extrapolate')){args=list();if(mode=='degree-one')args$degree=1;if(mode=='symmetric')args$family='symmetric';grid=if(mode=='extrapolate')c(-3,-2,0,2,3)else seq(-2,2,length.out=7);capture(paste0('loess-',mode),list(data=l,span=if(mode=='span-half').5 else .75,method_args=args,xseq=grid),function()built(ggplot(l,aes(x,y,weight=w))+geom_smooth(method=if(mode=='default')NULL else 'loess',formula=y~x,span=if(mode=='span-half').5 else .75,method.args=args,xseq=grid)))}
for(n in c(999,1000)){z=data.frame(x=seq(0,10,length.out=n));z$y=sin(z$x)+.2*cos(3*z$x);capture(paste0('automatic-',n),list(data=z,n=9),function()built(ggplot(z,aes(x,y))+geom_smooth(n=9)))}
for(panel_n in c(600,1000)){z=data.frame(x=rep(seq(0,10,length.out=panel_n),2),panel=rep(c('A','B'),each=panel_n));z$y=sin(z$x)+.2*cos(3*z$x);capture(paste0('automatic-facets-',panel_n),list(data=z,n=5,largest_group_panel=panel_n),function()built(ggplot(z,aes(x,y))+geom_smooth(n=5)+facet_wrap(~panel)))}
q=data.frame(x=c(0,0,1,1,2,2,3,3),y=c(0,2,0,3,2,5,3,8),w=c(1,2,1,0,3,1,2,1));grid=c(0,1,2,3)
for(method in c('br','fn','pfn','sfn'))for(weighted in c(FALSE,TRUE)){z=q;if(!weighted)z$w=1;capture(paste('quantile',method,weighted,sep='-'),list(data=z,method='rq',solver=method,quantiles=c(.25,.5,.75),xseq=grid),function(){fits=lapply(c(.25,.5,.75),function(tau){fit=quantreg::rq(y~x,z,tau=tau,weights=w,method=method);r=z$y-predict(fit,z);list(tau=tau,coefficients=coef(fit),objective=sum(z$w*r*(tau-(r<0))))});list(fits=fits,built=built(ggplot(z,aes(x,y,weight=w))+geom_quantile(method.args=list(method=method),quantiles=c(.25,.5,.75),xseq=grid)))})}
for(mode in c('ties','singular','negative-weight','rqss')){z=q;if(mode=='ties')z$y=c(0,0,1,1,2,2,3,3);if(mode=='singular')z$x=1;if(mode=='negative-weight')z$w[1]=-1;capture(paste0('quantile-',mode),list(data=z,method=if(mode=='rqss')'rqss'else 'rq',lambda=1,xseq=grid),function()built(ggplot(z,aes(x,y,weight=w))+geom_quantile(method=if(mode=='rqss')'rqss'else 'rq',lambda=1,xseq=grid)))}
packages=c('ggplot2','mgcv','nlme','MASS','quantreg','SparseM','MatrixModels','Matrix')
jsonlite::write_json(list(reference='ggplot2 4.0.3 / R 4.6.1',seed=20260915,dependencies=setNames(lapply(packages,function(p)if(requireNamespace(p,quietly=TRUE))as.character(packageVersion(p))else NULL),packages),cases=cases),'fixtures/parity/ggplot2/model-controls.json',auto_unbox=TRUE,digits=17,na='null',null='null')
cat('captured',length(cases),'cases\n')
