"""Remove only the oracle PDF's wall-clock creation time for deterministic fixtures.

Use the bundled artifact Python with pypdf. Page content streams must remain identical.
No geometry, text, fonts, tolerances or expected values are regenerated by this step.
"""
from pathlib import Path
import sys
from pypdf import PdfReader, PdfWriter

directory = Path(sys.argv[1]) / 'artifacts'
for path in sorted(directory.glob('*.pdf')):
    reader = PdfReader(path)
    content = [page.get_contents().get_data() for page in reader.pages]
    writer = PdfWriter(clone_from=reader)
    writer.add_metadata({'/CreationDate': 'D:20000101000000Z'})
    temporary = path.with_suffix('.normalized.pdf')
    writer.write(temporary)
    checked = PdfReader(temporary)
    assert [page.get_contents().get_data() for page in checked.pages] == content, path
    temporary.replace(path)
print(f'PASS normalized PDF creation metadata; retained page streams: {len(list(directory.glob("*.pdf")))}.')
