// FIX-S05: pinned radial conversion, every curve, boundary helpers and all link factories.
import * as d3 from 'd3-shape';
import fs from 'node:fs';import path from 'node:path';
import {root,provenance,writeJson,digest}from './provenance.mjs';
const out=path.resolve(process.argv[2]||path.join(root,'fixtures/shapes'));
class Context {constructor(){this.operations=[];}moveTo(...args){this.operations.push({op:'moveTo',args});}lineTo(...args){this.operations.push({op:'lineTo',args});}bezierCurveTo(...args){this.operations.push({op:'bezierCurveTo',args});}closePath(){this.operations.push({op:'closePath'});}}
const names={angle:'angle',radius:'radius',start_angle:'startAngle',end_angle:'endAngle',inner_radius:'innerRadius',outer_radius:'outerRadius'},cases=[];
function curve(c){let f=d3['curve'+c.kind];for(const p of ['alpha','beta','tension'])if(p in c)f=f[p](c[p]);return f;}
function coordinate(c){return 'Column'in c?d=>d[c.Column]:c.Constant;}
function finish(id,family,input,config,g,helper=null){const context=new Context();g.context(context)(input);const svg=g.context(null)(input),finite=context.operations.every(op=>!op.args||op.args.every(Number.isFinite));cases.push({id,family,input,config,helper,finite,operations:JSON.parse(JSON.stringify(context.operations,(_,v)=>typeof v==='number'&&!Number.isFinite(v)?{number:String(v)}:v)),svg});}
function emit(id,family,input,config={},helper=null){const g=d3[family]();for(const[k,v]of Object.entries(config)){if(k==='curve')g.curve(curve(v));else if(k==='defined')g.defined(Array.isArray(v)?(_,i)=>v[i]:v);else if(k==='digits')g.digits(v);else g[names[k]](v===null?null:coordinate(v));}finish(id,family,input,config,helper?g['line'+helper]():g,helper);}
const rows=Array.from({length:13},(_,i)=>[i*Math.PI/6,20+i*2,i*Math.PI/6+.12,8+i%3]),runs={spiral:rows,seam:[[-.2,20,0,5],[6,30,6.2,8],[.2,25,.3,6],[7,40,7.2,9]],negative:[[0,-10,.3,-4],[Math.PI/2,20,2,5],[Math.PI,-5,4,-2],[5,0,5.5,0]],duplicate:[[0,0,0,0],[0,0,0,0],[1,20,1,5],[1,20,1,5],[2,10,2,4]]};
const curves=Object.keys(d3).filter(n=>n.startsWith('curve')).map(n=>n.slice(5)).sort();
for(const kind of curves){for(const[label,input]of Object.entries(runs)){emit(`${kind}-${label}-line`,'lineRadial',input,{curve:{kind}});if(kind!=='Bundle')emit(`${kind}-${label}-area`,'areaRadial',input,{curve:{kind},inner_radius:{Column:3},end_angle:{Column:2}});}
 for(const n of [0,1,2,3,4]){const input=rows.slice(0,n+2),defined=input.map((_,i)=>i<n);emit(`${kind}-defined-${n}`,'lineRadial',input,{curve:{kind},defined});if(kind!=='Bundle')emit(`${kind}-area-defined-${n}`,'areaRadial',input,{curve:{kind},defined});}
 for(const p of ['alpha','beta','tension'])if(typeof d3['curve'+kind][p]==='function')for(const v of [0,0.2,0.75,1]){emit(`${kind}-${p}-${v}`,'lineRadial',rows,{curve:{kind,[p]:v}});if(kind!=='Bundle')emit(`${kind}-${p}-${v}-area`,'areaRadial',rows,{curve:{kind,[p]:v}});}}
const configs=[{}, {start_angle:{Constant:1.234567},inner_radius:{Constant:2.345678},end_angle:null,outer_radius:null},{start_angle:{Column:2},inner_radius:{Column:3},end_angle:{Column:0},outer_radius:{Column:1}},{start_angle:{Column:0},inner_radius:{Constant:-5},end_angle:{Constant:2.34567},outer_radius:{Column:1}}];
for(const[i,c]of configs.entries())for(const kind of ['Linear','Basis','Cardinal','Natural','Step']){const config={...c,curve:{kind},digits:0,defined:rows.map((_,i)=>i!==5)};emit(`controls-${i}-${kind}`,'areaRadial',rows,config);for(const helper of ['StartAngle','EndAngle','InnerRadius','OuterRadius'])emit(`helper-${i}-${kind}-${helper}`,'areaRadial',rows,config,helper);}
for(const digits of [0,3,12,null]){emit(`line-constants-${digits}`,'lineRadial',rows,{angle:{Column:2},radius:{Constant:12.34567},digits});emit(`area-shared-${digits}`,'areaRadial',rows,{angle:{Column:0},radius:{Column:1},digits});}
const links=[{source:[0,10,1,20],target:[2,40,3,30]},{source:[Math.PI/2,20],target:[3*Math.PI/2,60]},{source:[6.2,50],target:[.1,20]},{source:[-4,-20],target:[8,40]},{source:[0,0],target:[0,0]},{source:[2,10],target:[2,10]},{source:[0,10],target:[1,10]},{source:[-10,30],target:[10,40]}];
function link(id,radial,input,config){const g=radial?d3.linkRadial():d3.link(curve(config.curve||{kind:'BumpX'}));for(const[k,v]of Object.entries(config)){if(k==='curve')continue;if(k==='source'||k==='target')g[k](typeof v==='string'?d=>d[v.toLowerCase()]:()=>v.Constant);else if(k==='digits')g.digits(v);else g[k](coordinate(v));}finish(id,radial?'linkRadial':'link',input,config,g);}
for(const kind of curves)for(const[i,input]of links.entries())link(`link-${kind}-${i}`,false,input,{curve:{kind}});
for(const[i,input]of links.entries())link(`linkRadial-${i}`,true,input,{});
for(const digits of [0,3,12,null]){for(const radial of [false,true])for(const swap of [false,true]){const config={digits,source:swap?'Target':'Source',target:swap?'Source':'Target',[radial?'angle':'x']:{Column:2},[radial?'radius':'y']:{Column:3}};link(`link-controls-${radial}-${swap}-${digits}`,radial,links[0],config);}}
for(const radial of [false,true])link(`link-constant-${radial}`,radial,links[0],{source:{Constant:[1,10]},target:{Constant:[2,20]},[radial?'radius':'y']:{Constant:12.345678}});
const points=[];for(const angle of [0,Math.PI/2,Math.PI,Math.PI*1.5,Math.PI*2,-Math.PI/2,Math.PI*4+.1,-3,1e16,-1e16])for(const radius of [0,-1,1,100])points.push({angle,radius,point:d3.pointRadial(angle,radius)});
writeJson(path.join(out,'radial.json'),{schema_version:1,points,cases});writeJson(path.join(out,'radial-manifest.json'),{schema_version:1,references:['d3-shape','d3-path'].map(provenance),points:points.length,cases:cases.length,generator_sha256:digest(fs.readFileSync(new URL(import.meta.url))),cases_sha256:digest(fs.readFileSync(path.join(out,'radial.json')))});console.log('PASS independent radial/link oracle:',points.length,'points and',cases.length,'paths');
